### ISSUE TITLE
highlighter for R language

### ISSUE THREAD

**Issue by dpastoor** [alecthomas/chroma#1]
Hi,

I'd be happy to give a whirl on adding R, but taking a look at the python script used to extract I didn't (quickly) see any doc on where to specify the language to try to extract.

Here is the relevant class info: http://pygments.org/docs/lexers/#lexers-for-the-r-s-languages

```
class pygments.lexers.r.SLexer
Short names: | splus, s, r
-- | --
*.S, *.R, .Rhistory, .Rprofile, .Renviron
text/S-plus, text/S, text/x-r-source, text/x-r, text/x-R, text/x-r-history, text/x-r-profile
```

**Comment by alecthomas** [comment]
Hi @dpastoor ! If you check out the "Lexers" section in the [README](https://github.com/alecthomas/chroma#lexers), it has an example line for running the translator if you'd like to send a PR. If not, I will get to it later today sometime.

**Comment by alecthomas** [comment]
Actually I will do it now!

**Comment by dpastoor** [comment]
That'd be amazing! This looks super super promising, I look forward to testing it out!

**Comment by dpastoor** [comment]
Just wanted to confirm that I've tried and it looks great! 

I will try to make a couple additional examples and add a PR to the readme.

Thanks for the amazing package!
