### ISSUE TITLE
Garbled output for Markdown under certain circumstances

### ISSUE THREAD

**Issue by curio77** [alecthomas/chroma#10]
Playing with the `chroma` command, I've noticed that its terminal output at least is garbled for Markdown under certain circumstances.  I don't know if this is just a terminal output issue or limited to Markdown.

The following sample correctly outputs as the same textual content with highlighting:

```markdown
# Headline

- foo
- foo bar
```
The following sample, however:

```markdown
# Headline

- foo €€€
- foo bar
```

outputs as this:

```markdown
# Headline

- foo €€€bar
```

Apparently, it's the Unicode characters causing trouble.  The same happens with, e.g., German umlauts. The sample file is encoded as UTF-8.

**Comment by alecthomas** [comment]
Interesting! I think this will be a bug where I'm doing a byte `len()` on a string (or similar) rather than correctly using the utf8 length.

**Comment by curio77** [comment]
Wow, that was quick! :-)
