### ISSUE TITLE
lexers.Analyse not working

### ISSUE THREAD

**Issue by mkchoi212** [alecthomas/chroma#101]
I'm currently trying to detect the type of language with the following code

```go
var lexer chroma.Lexer
for _, block := range [][]string{c.CurrentLines, c.ForeignLines} {
  if lexer = lexers.Analyse(strings.Join(block, "\n")); lexer != nil {
    break
  }
}
```

However, `lexers.Analyse` always returns `nil`; note that the input lines were about 10 lines of Swift code.

The weird thing is I tried this
```go
lexer := lexers.Analyse("let foo = 3\nstruct Animal { let name: String });
```
which still returned `nil`.

Any ideas?

**Comment by mkchoi212** [comment]
Here's some dummy `C` code I tested... with no success.
```c
void FL_add(FL_HEADER *cur, FL_HEADER *b) {
  FL_HEADER *p_next = cur->next;
  
  if(p_next) {
    cur->next = b;
    b->prev = cur;
    b->next = p_next;
    p_next->prev = b;
  } else {
    cur->next = b;
    b->prev = cur;
  }
}
```

**Comment by alecthomas** [comment]
https://github.com/alecthomas/chroma/blob/master/README.md#whats-missing-compared-to-pygments

Analyse has not been implemented for many languages.

**Comment by mkchoi212** [comment]
@alecthomas  Swift and C are both in the list!

**Comment by alecthomas** [comment]
What list?

**Comment by mkchoi212** [comment]
I meant `master/lexers`

**Comment by alecthomas** [comment]
I was linking to this paragraph:

> Though the Chroma API supports content detection, very few languages support them. I have plans to implement a statistical analyser at some point, but not enough time.

Sorry I'm a bit short I'm on mobile.

**Comment by mkchoi212** [comment]
Ah gotcha! Thanks for the clarification
