### ISSUE TITLE
How to specify a multi word language

### ISSUE THREAD

**Issue by kkvero** [alecthomas/chroma#1015]
How to specify a multi word language to use syntax highlighting with Chroma? 
For example how to specify a language like "Go HTML Template".
When specifying code blocks like:
```go
```go html template
{{- $count := .Get "count"  -}}
//```
```
With spaces?
But then it highlights `$` with red when rendered in browser  (gives & a red background) (for the rest, the highlighting is applied).
(Specifically my environment is a markdown file used with SSG Hugo.)

**Comment by CIAvash** [comment]
Since you mentioned Hugo, they list the languages [here](https://gohugo.io/content-management/syntax-highlighting/#list-of-chroma-highlighting-languages).

**Comment by kkvero** [comment]
Thanks! It is correct! 
(When I was trying that spelling variant, the editor misleadingly removed the highlighting completely. But now double checking in browser, in browser the highlighting is present and is ok.) Thanks!
