### ISSUE TITLE
command line go installation does not work

### ISSUE THREAD

**Issue by mikepruett3** [alecthomas/chroma#1016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I try to run the following

`go install github.com/alecthomas/chroma/v2`

I get errors, and cannot continue. I would like to be able to use go install vs cloning the repo and manually doing it.

### To Reproduce

I get the following error on windows:

```
go: 'go install' requires a version when current directory is not in a module
        Try 'go install github.com/alecthomas/chroma/v2@latest' to install the latest version
```

I try adding the @latest to the end of the command, and get this error:

`package github.com/alecthomas/chroma/v2 is not a main package`

Not sure how to proceed.
Trying from Windows 10 using go version go1.22.4 windows/amd64

**Comment by alecthomas** [comment]
Use `go get` to add modules to your project, not `go install`.
