### ISSUE TITLE
Add support for Go Template

### ISSUE THREAD

**Issue by regisphilibert** [alecthomas/chroma#105]
These days we write a lot about Go Template snippets using our favorite Go staticgenerator : Hugo. Chroma is now the default syntax highlighter for Hugo but lacks Go Template highlighting. 
This would be a must.

Tks.

**Comment by bep** [comment]
I agree ... That would be really useful; the Hugo docs site has millions of Go template samples. We use `html` as the highlighter style, but that is suboptimal; but I guess that should be the extension starting point for Chroma.

**Comment by bep** [comment]
Just a note: 

This should probably be two lexers (with reuse):

1. A Go HTML template lexer
2. A Go Text template lexer 

I have no idea what they should be named...

**Comment by alecthomas** [comment]
That would be excellent.

**Comment by alecthomas** [comment]
Give that a try. It also interprets literal Go strings (backticks) as templates, as they are commonly used for this purpose. eg.

<img width="386" alt="screen shot 2018-03-18 at 22 06 32" src="https://user-images.githubusercontent.com/41767/37565196-a9ea36aa-2af8-11e8-8cfe-570067e61f50.png">
