### ISSUE TITLE
Syntax Highlighting problem with default monokai theme

### ISSUE THREAD

**Issue by laozhu** [alecthomas/chroma#106]
1. hugo version 0.32.4
2. with `monokai` theme
3. javascript language

```markdown
```javascript
function foo(x = 1, y = 2) { // 这里给x, y设置了默认值
  console.log(x, y)
}
foo() // 1, 2
foo(3, 4) // 3, 4
```

But something went wrong with inline comments, preview below.

![image](https://user-images.githubusercontent.com/1212457/35254753-900da6ec-0026-11e8-918a-690965f34dad.png)

**Comment by kaushalmodi** [comment]
Looks like many languages need that auto insertion of newline at the end. Should that be made the default (i.e. the current default reverted?).

**Comment by adeesent** [comment]
Can we just add EnsureNL, similar to the lexers/make.go into lexers/javascript.go? As I can see it solves this problem.

**Comment by alecthomas** [comment]
Fixed, thanks @adeesent !
