### ISSUE TITLE
Possible to place referencing numbers in code?

### ISSUE THREAD

**Issue by Jos512** [alecthomas/chroma#107]
I was wondering if it's possible with Chroma to place 'special numbers' in the code block that are later referenced in the text when explaining the code, like this:

![2018-01-26_16-27-01](https://user-images.githubusercontent.com/13403160/35446707-e22dfbac-02b5-11e8-8663-086eb76417e8.png)

(Image taken from [this webpage](http://designingforperformance.com/basics-of-page-speed/#critical-rendering-path).)

I'm already very happy with Chroma and the work the contributors put into it. But just am curious about whether this feature is possible.

**Comment by alecthomas** [comment]
That's an interesting feature, but I think it's outside the scope of Chroma.
