### ISSUE TITLE
Any chance to add support for ASCII art?

### ISSUE THREAD

**Issue by kowalcj0** [alecthomas/chroma#108]
Hi,

I'm using:
* `Hugo v0.35`
*  `pastie` Chroma style
* [minimo](https://themes.gohugo.io/theme/minimo/) theme

When I surround ASCII art with GitHub flavoured code fences but without any language, then in VIM it looks like this:
![ascii-vim](https://user-images.githubusercontent.com/910451/35778686-a1d2e08a-09b9-11e8-8930-00355606ba6b.png)
It looks the same in terminal:
![ascii-terminal](https://user-images.githubusercontent.com/910451/35778925-2bd13158-09bd-11e8-8cc1-05d9472ea20c.png)
Here's the page source code generated by Hugo
![ascii-src-html](https://user-images.githubusercontent.com/910451/35778691-bf580842-09b9-11e8-955e-7d71469c8519.png)
and this is how it's rendered in various browsers (Chrome 64, Firefox 58, Vivaldi 1.14)
![ascii-browser](https://user-images.githubusercontent.com/910451/35778696-c68ea058-09b9-11e8-950d-645f1bbcf21f.png)

When I set the language to e.g.: `bash`:
![ascii-bash-vim](https://user-images.githubusercontent.com/910451/35778710-f21adff2-09b9-11e8-8747-dbe23708d649.png)
the the page source code looks like this:
![ascii-src-bash](https://user-images.githubusercontent.com/910451/35778715-ff5062a0-09b9-11e8-82c1-8cd77de7747b.png)
and this is how it's rendered:
![ascii-bash-browser](https://user-images.githubusercontent.com/910451/35778720-09b7236e-09ba-11e8-99df-9341559aed62.png)
It looks a lil better than without any language, but it's not the same thing as in vim or in terminal.

Cheers

**Comment by alecthomas** [comment]
I imagine this is a function of the theme you choose. Have you tried any others?

**Comment by kowalcj0** [comment]
No haven't tried other themes, but will try. Can we leave this ticket open for few days?
