### ISSUE TITLE
JSX - closing tags do not match opening tags

### ISSUE THREAD

**Issue by will-stone** [alecthomas/chroma#111]
Hi. Thanks for this project! I've just started using Hugo and it's great to have this functionality inbuilt.

I've noticed that the closing tags of JSX do not match the opening tags when using the JS highlighter:

<img width="582" alt="image" src="https://user-images.githubusercontent.com/654103/35887583-aa076bd4-0b8c-11e8-82b0-d7915d43f11c.png">

Let me know if you need more detail, or if I can help in any way.

**Comment by alecthomas** [comment]
JSX is not supported at all. It's just sheer luck that that highlights at all.

**Comment by will-stone** [comment]
I’ve only ever written JS and some PHP (back in the day) so not sure if I’m the best person to try this, but could this be ported over? https://github.com/fcurella/jsx-lexer/blob/master/jsx/lexer.py With JSX being so popular these days, I’m sure there would be many silently grateful.

**Comment by alecthomas** [comment]
Thanks for the pointer. I translated it mechanically, and it does seem a bit buggy, but it's better than nothing and can perhaps be tweaked to improve it.

**Comment by will-stone** [comment]
Oooo, nice! I look forward to the release. Thank-you.
