### ISSUE TITLE
Chroma highlighting using pygmentOptions=“linenos=table” in Hugo a bug?

### ISSUE THREAD

**Issue by joshuasheppard** [alecthomas/chroma#114]
I initially opened [an issue](https://github.com/halogenica/beautifulhugo/issues/97) with Beautiful Hugo since this appeared related to styling but I was [eventually pointed here](https://discourse.gohugo.io/t/chroma-highlighting-using-pygmentoptions-linenos-table-bug/9694).

I'm seeing an issue where it appears that when I switched over to Chroma in Hugo, I ran into a situation where when I use pygmentOptions = "linenos=table" in config.toml I see a vertical line artifact on the right hand side of any code that doesn't run the full width or trigger the horizontal scrollbars. See the [other issue](https://github.com/halogenica/beautifulhugo/issues/97) I opened for more discussion.

Is there some other setting that I'm missing? Is this expected behavior?

Hugo v0.30.2 (Still an issue in v0.36)
beautifulhugo 7cdd0e0
Chroma style monokai
Chrome browser

**Comment by alecthomas** [comment]
That should fix it I think.

For future reference, I'd appreciate it if you were to include the steps to reproduce a bug, rather than linking to external sources. It would make my life much easier and expedite the bug fix.

**Comment by joshuasheppard** [comment]
@alecthomas thank you for addressing this so quickly! :)

And for calling me on my laziness. Reporting it in other places while tracking this down doesn't give me the excuse to be lazy when reporting it here. I need to remember that in the future.

To that end, is there an example you can point me at that I should seek to emulate? Is providing a Hugo version, Beautiful Hugo version, Chroma style with the addition of a code block I'm seeing the issue enough? Or is there another replication format you'd prefer? :)

**Comment by xurizaemon** [comment]
Looks like that wound up in the issue template: https://github.com/alecthomas/chroma/blob/master/.github/ISSUE_TEMPLATE/bug_report.md, or visible at https://github.com/alecthomas/chroma/issues/new?assignees=&labels=&template=bug_report.md&title=
