### ISSUE TITLE
Bug in yaml highlighting

### ISSUE THREAD

**Issue by ahmetb** [alecthomas/chroma#119]
Try highlighting the following yaml content in Chroma:

```yaml
apiVersion: apps/v1beta1
```

note that you will get this, where the trailing `1` is treated as a different token, although it's part of the value string:

![image](https://user-images.githubusercontent.com/159209/36229025-c2c26882-118a-11e8-8b1e-2abb4f03ec35.png)

I think this is a small bug in Chroma’s interpretation of the syntax

**Comment by alecthomas** [comment]
Fixed in 50a6b50.
