### ISSUE TITLE
Javascript language lexer outdated

### ISSUE THREAD

**Issue by steambap** [alecthomas/chroma#12]
Javascript language lexer treats ES6 keywords like class / static as reserved keywords and it is missing ES7 keywords like async / await.

**Comment by alecthomas** [comment]
> Javascript language lexer treats ES6 keywords like class / static as reserved keywords

Are you saying that they should not be reserved keywords, or just saying that they are treated correctly but async/await are not?

I'll add asnyc/await!

**Comment by steambap** [comment]
I just checked ES2015 keywords on [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords)

`class / const / debugger / export / extends / import / super` are keywords, and should not be reserved keywords.  `static` is a reserved keywords, I was wrong.
