### ISSUE TITLE
JS highlighting weirdly colors the second half of a division expression

### ISSUE THREAD

**Issue by looeee** [alecthomas/chroma#125]
I'm using Chroma in Hugo and finding that when I highlight code as JS there it styles the second half of a division expression weirdly. 

![hugo_highlight_bug](https://user-images.githubusercontent.com/5307958/36887345-bb1ce262-1e2b-11e8-9b01-3156265b3dff.png)

I'm not using  any custom styling except setting the background color.

The style being applied to the oddly colored part is:

```css
color: #960050;
background-color: #1e0010;
```

Here's my code (using Hugo shortcode for highlighting):

```js
{{< highlight js >}}
var percentComplete = xhr.loaded / xhr.total * 100;
{{< /highlight >}}
```

Comments are colored grey, so it's not incorrectly flagging it as a comment which I originally thought.

**Comment by looeee** [comment]
I've found where this is being applied from. It's incorrectly being styled as "monokai error":

https://github.com/alecthomas/chroma/blob/8f289191c9ca8548d0a188f42ac3b2a37db68dbd/styles/monokai.go#L10

**Comment by alecthomas** [comment]
I tracked this down to the regex dealing with regular expression literals (eg. `/someregex/`). It thinks this is a regex without a terminating `/`... I have not had time to debug the regex yet.

**Comment by Jos512** [comment]
The 

~~~js
var percentComplete = xhr.loaded / xhr.total * 100;
~~~

Shows as this HTML when made by Chroma:

~~~html
<span class="kd">var</span> <span class="nx">percentComplete</span> <span class="o">=</span> <span class="nx">xhr</span><span class="p">.</span><span class="nx">loaded</span> <span class="err">/</span><span class="err"> </span><span class="err">x</span><span class="err">h</span><span class="err">r</span><span class="err">.</span><span class="err">t</span><span class="err">o</span><span class="err">t</span><span class="err">a</span><span class="err">l</span><span class="err"> </span><span class="err">*</span><span class="err"> </span><span class="err">1</span><span class="err">0</span><span class="err">0</span><span class="err">;</span>
~~~

The first `err` class happens here after the 'loaded' word. That word got the `nx` class. That class name is for the 'NameOther' token.

[This line](https://github.com/alecthomas/chroma/blob/c4123fc163de72aea0a1006c52b74d11799cc1cd/lexers/j/javascript.go#L42) in the JavaScript lexer is the only one that sets the 'NameOther' token.

Further than that I, unfortunately, did not come with my debugging. But I thought I can at least post it here, perhaps this can help someone else with resolving this issue.

**Comment by davidfeng88** [comment]
I just tried something as simple as
```js
c = a / b;
```
Result:
```html
<span class="nx">c</span> <span class="o">=</span> <span class="nx">a</span> <span class="err">/ b;</span>
```

`c` => "nx", NameOther.
`=` => "o", Operator.
`a` => "nx", NameOther.
`/ b;` => "err", Error.
Everything was all right before `/ b;`. My guess is that in the [javascript lexer](https://github.com/alecthomas/chroma/blob/c4123fc163de72aea0a1006c52b74d11799cc1cd/lexers/j/javascript.go) the lexer saw the `/` and thinks it's the beginning of a regex. After it scans the whole line, it did not find the ending `/`, thus declaring that the whole part of `/ b;` as an error.

----
A similar example I found:
```js
a / b; // comment
```
Result:
```html
<span class="nx">a</span> <span class="sr">/ b; /</span><span class="err">/ comment</span>
```
`a` => "nx", NameOther.
`/ b; /` => "sr". LiteralStringRegex.
`/ comment` => "err", Error.
When the lexer saw the first `/`, it began to search the next `/` and claim everything in between as a regex, therefore `/ b; /` is a literal string regex. Then the `/ comment` is an error similar to the previous example.

----
I don't really know how the lexer works. I'm definitely not a regex expert either. Maybe lowering the priority of the "slashstartsregex" rule would help? @alecthomas @Jos512

**Comment by alecthomas** [comment]
Yes, that's exactly correct.

**Comment by davidfeng88** [comment]
Thanks, @alecthomas!
I see you added `help wanted` label. If you could give me some references on how chroma works on the high level, maybe I can study and try to help!

**Comment by Jos512** [comment]
I can't really help with understanding Chroma on a high-level, since the few small things I contributed were all on the level of the lexers. For those you don't need to know much about Chroma, other than that Chroma takes the lexer file and applies to the different code elements. 

But that actually makes Chroma straightforward to work with, since everything that's needed is in the lexer code file.

**Comment by davidfeng88** [comment]
@Jos512 Sounds good. I'll try to play with the JS lexer once I have time!
