### ISSUE TITLE
Add "gitconfig", "tmuxconf" as aliases to "docker" lexer

### ISSUE THREAD

**Issue by kaushalmodi** [alecthomas/chroma#128]
Hello,

*First of all, sorry, looks like I did Ctrl+Enter or something, and that submitted that incomplete issue or rather tweak request.*

I don't use docker files, but through random experimentation, I believe that that lexer does the best syntax highlighting for `.gitconfig` files, `.gitattributes`, and `.tmux.conf` files.

Proof:

- https://scripter.co/git-diff-minified-js-and-css/#configure-git-to-use-that-tool
- https://scripter.co/command-to-every-pane-window-session-in-tmux/#tmux-send-cmd-to-all-panes-old

If you don't mind, can you please add `gitconfig` and `tmuxconf` as aliases for the docker lexer?

**Comment by alecthomas** [comment]
`.gitconfig` is an .ini file right?

**Comment by kaushalmodi** [comment]
### `.gitconfig`

> .gitconfig is an .ini file right?

I didn't know that.. So `ini` lexer also works great for `.gitconfig` (syntax highlighting looks the same as done by `docker` lexer)

So can `gitconfig` alias be added to `ini`?

### `.gitattributes`

I am not sure what's the right lexer for this.

`docker` gives:

![image](https://user-images.githubusercontent.com/3578197/37843545-9b662516-2e9b-11e8-92c5-4a8d8c6239fb.png)

`ini` gives:

![image](https://user-images.githubusercontent.com/3578197/37843565-a9c83716-2e9b-11e8-818b-d6af4c8007be.png)

Good thing is that both styles at least distinguish the `diff=..` part. If you alias `gitconfig` to `ini`, I can use the same `gitconfig` data-lang tag for .gitattributes too.. Not a problem

### `.tmux.conf`

Using `docker` lexer:

![image](https://user-images.githubusercontent.com/3578197/37843687-0a4e1c7c-2e9c-11e8-9da4-c9223f0c0345.png)

Here the key was that `# Send ..` should be comment, but `##{ses ..` should **not** as the `##` are part of the string. And based on trial and error, `docker` fits the bill. 

So can `tmuxconfig` be added as an alias to `docker`?

Thanks!
