### ISSUE TITLE
Wanted: YAML lexer

### ISSUE THREAD

**Issue by alecthomas** [alecthomas/chroma#13]
Unsurprisingly, the Pygments YAML lexer is very complex. This either needs to be ported with all its helpers, or a new lexer created from scratch.

**Comment by steambap** [comment]
Here is hightlight.js [yaml lexer](https://github.com/isagalaev/highlight.js/blob/master/src/languages/yaml.js) and prism [yaml lexer](https://github.com/PrismJS/prism/blob/master/components/prism-yaml.js) .

Both of them have a regex based lexer. No complexed helper.

**Comment by alecthomas** [comment]
They seem much more manageable, thanks!
