### ISSUE TITLE
Introduce Mermaid diagram support 

### ISSUE THREAD

**Issue by Honghe** [alecthomas/chroma#130]
example:

    ```mermaid
    graph TD;
        A-->B;
        A-->C;
        B-->D;
        C-->D;
    ```

This code block shall be rendered into diagram

![image](https://user-images.githubusercontent.com/1092722/38072781-8ce4cbd2-335a-11e8-9c8a-d8d6252031e1.png)

That is Chroma not hightlight `mermaid` block, only transform the block to mermaid syntax, then [mermaid.js](https://github.com/knsv/mermaid) can parse and render it.
```
  <div class="mermaid">
  graph LR
      A --- B
      B-->C[fa:fa-ban forbidden]
      B-->D(fa:fa-spinner);
  </div>
```

This is very useful feature for documenting code/high level design/architecture.

**Comment by alecthomas** [comment]
I've never heard of Mermaid, this would need more detail before implementing.

**Comment by Honghe** [comment]
https://github.com/knsv/mermaid

**Comment by alecthomas** [comment]
Mermaid looks really cool, but II'm not sure I understand what value Chroma is adding here. Both of the examples you give seem like Mermaid syntax? What's the transformation happening here?

Regardless, I think this is probably outside the scope of Chroma, but I'm curious what your idea is.

**Comment by Honghe** [comment]
Maybe I misled you. It is not that complicated :)
Something Chroma need to have is a mechanism or config, which can set no to converts the codeblock into syntax highlighted HTML when the codeblock starts with "```mermaid": 

    ```mermaid
    graph TD;
        A-->B;
        A-->C;
        B-->D;
        C-->D;
    ```
Instead, converts the codeblock to the following HTML (surrounded with \<div class="mermaid"\>), then mermaid.js can render it to SVG.
```
  <div class="mermaid">
  graph LR
      A --- B
      B-->C[fa:fa-ban forbidden]
      B-->D(fa:fa-spinner);
  </div>
```

**Comment by Depado** [comment]
I think this is outside the scope of chroma.
Maybe that would be cool to create a Blackfriday plugin or a completely separate package to handle that ?

**Comment by alecthomas** [comment]
Yes, agreed. Chroma doesn't do any kind of transformation, just highlighting.
