### ISSUE TITLE
Add targets in line numbers

### ISSUE THREAD

**Issue by ralsina** [alecthomas/chroma#132]
It would be great if you could add optional targets in the line numbers, so that you can link to a specific line in the file.

**Comment by alecthomas** [comment]
Not a bad idea, though it would need to support multiple code fragments in one file, so it would need some kind of namespacing.

**Comment by Simran-B** [comment]
Looks like linkable line numbers were implemented last year?

**Comment by alecthomas** [comment]
Yes!
