### ISSUE TITLE
Chroma Style Gallery

### ISSUE THREAD

**Issue by xyproto** [alecthomas/chroma#133]
Hi,

I could not find an overview of what all the available styles look like, so I created this page:

[Chroma Style Gallery](https://xyproto.github.io/splash/docs/)

It has the disadvantage that the style samples are not listed on one page, but it presents a full overview of all available styles.

Thanks for creating chroma!

Cheers,
Alexander F Røseth

**Comment by alecthomas** [comment]
Very cool!

I don't mind them being on separate pages, but perhaps a "next" button would be useful. Then people can just flick through them all to find one they like.

**Comment by Depado** [comment]
Amazing I was just looking for that today !

**Comment by xyproto** [comment]
Added `Prev`, `Next` and `Up` buttons to the style gallery.

**Comment by alecthomas** [comment]
Thanks @xyproto for adding a link to the README.
