### ISSUE TITLE
Feature request - "Inline" markdown highlighting option

### ISSUE THREAD

**Issue by jorgelbg** [alecthomas/chroma#135]
Currently we need to specify the line number(s) (or range) that we want to highlight. This works great but is not really easy to use. I would like to propose the use of some especial token in the code block itself to indicate the line to highlight. An example would be something similar to:

```
package main

import (
	"fmt"
)

*func main() {
*	fmt.Println("Hello, playground")
*}
```

This would indicate that the three lines that start with the `*` would the ones to highlight. This sounds like something that we would like to support?

**Comment by alecthomas** [comment]
I think that is out of scope for Chroma. It should be fairly simple to write a wrapper function to achieve the same goal though I would imagine?

**Comment by alecthomas** [comment]
Reopened it because it could be useful to add as a "util" function. Something like `ExtractLineRanges(source string) (stripped string, lines [][2]int)`

**Comment by jorgelbg** [comment]
@alecthomas I've implemented something similar as a feature for hugo, but was not sure if this could be of some use for the library itself, or should be contributed back only to hugo, hence why I asked.

**Comment by alecthomas** [comment]
Ah ok. IMO this would be more useful in Hugo, yep.

**Comment by kaushalmodi** [comment]
@jorgelbg How did you implement that in Hugo? Can you please share the details? What syntax would you use in Markdown for inline syntax highlighting? Thanks.
