### ISSUE TITLE
Incompatible CSS classes

### ISSUE THREAD

**Issue by bep** [alecthomas/chroma#14]
I see this and similar:

```
<span class="ss4"></span>
```
Which does not match any in

```
pygmentize -S perldoc -f html -a .highlight > syntax.css
```

**Comment by alecthomas** [comment]
CSS class IDs are not compatible with Pygments, no. The idea is to use:

```
chroma -s perldoc --html --html-styles
```

Is there some reason to want strict compatibility?

**Comment by bep** [comment]
>Is there some reason to want strict compatibility?

No, I just did not know about it...
