### ISSUE TITLE
HTML elements within YAML code fences are lost

### ISSUE THREAD

**Issue by ahmetb** [alecthomas/chroma#141]
(NOTE: I am using Hugo which uses Chroma. So I reported this issue initially at https://github.com/gohugoio/hugo/issues/4687)

It looks like this might actually be a Chroma issue caused by commit: https://github.com/alecthomas/chroma/commit/50a6b50a3b3c289126b04d14ba7e09caf5f476de (#118).

### Problem

When I use HTML tags in my code fences in Markdown, the <code>```yaml</code> code fence strips out the HTML and does not include the element in the output. For example, among these three examples (yaml, sh, _unspecified_):

    ```yaml
    kind: <strong>Service</strong>
    ``` 

    ```sh
    kind: <strong>Service</strong>
    ```

    ```
    kind: <strong>Service</strong>
    ```

The last 2 works fine, but the first example that uses <code>```yaml</code> fence **loses** the HTML tag `<strong>` (and the text in it altogether), so I get this:

> ![image](https://user-images.githubusercontent.com/159209/39445153-ee1c0d5c-4c6e-11e8-9afa-afefdd83fb78.png)

I have not tried reproducing this on Chroma directly. However, because it happens in only >v0.40.0 versions of Hugo (and not before, and the vendored code just got updated recently) the maintainer is suspecting it's coming from Chroma and particularly from 50a6b50a3b3c289126b04d14ba7e09caf5f476de.

**Comment by alecthomas** [comment]
I can't replicate this in Chroma:

```
[aat@cavern:~/Projects/chroma]echo 'kind: <strong>Service</strong>' | chroma -l yaml
kind: <strong>Service</strong>
```

**Comment by alecthomas** [comment]
Also in HTML mode it looks okay to me:

```
[aat@cavern:~/Projects/chroma]echo 'kind: <strong>Service</strong>' | chroma -l yaml -f html --html-only
<pre class="chroma">kind<span class="p">:</span><span class="w"> </span>&lt;strong&gt;Service&lt;/strong<span class="sd">&gt;
</span><span class="sd"></span></pre>
```

**Comment by ahmetb** [comment]
cc @bep as I'm not familiar with how Hugo invokes chroma.

**Comment by ahmetb** [comment]
No longer reproes.
