### ISSUE TITLE
Indexed Closest Color Wrong

### ISSUE THREAD

**Issue by danielgtaylor-isp** [alecthomas/chroma#145]
I understand you need to approximate the closest matching color from the palette, but it should not pick a completely different color.

[`#e06c75`](http://www.color-hex.com/color/e06c75) becomes [`#008080`](http://www.color-hex.com/color/008080) when passed into `findClosest` for `terminal256` output.

Sample code:

```go
styles.Register(chroma.MustNewStyle("test", chroma.StyleEntries{
		chroma.NameTag: "#e06c75",
})
quick.Highlight(os.Stdout, "{\"test\": true}", "json", "terminal256", "test")
```

**Comment by danielgtaylor-isp** [comment]
Note until this is fixed: as a workaround you can limit yourself to the [256-color palette](https://github.com/alecthomas/chroma/blob/master/formatters/tty_indexed.go#L33-L99) and things will work as expected. Install an editor plugin that highlights hex colors and it's easy to find similar colors to the ones you want.

**Comment by alecthomas** [comment]
Sorry, this one slipped my mind. I'll take a look.
