### ISSUE TITLE
Vue  SFC (Single File Component) lexer

### ISSUE THREAD

**Issue by robcresswell** [alecthomas/chroma#147]
This is kind of an interesting one. Vue has a concept of single file components, which put HTML, JS and CSS in a single `.vue` file.

I'm using this in Hugo, so there's a bit of a cross-project concern, but thought I'd start here. For example, if I have an SFC, something like:

```
<template> // the HTML block
...
</template>

<script> // The JS block
...
</script>
```

Is there a way of parsing the blocks as sub-blocks? Or does this require a new lexer that imports the others?

This gets slightly more complex as the template / script / style blocks can use different languages, such as pug for templating, but I'm just interested in the HTML / JS / CSS use case for now.

**Comment by alecthomas** [comment]
This would need a separate lexer, definitely, but it should be relatively straightforward. You'd need to use the `Using()` directive, which you can see an example of [here](https://github.com/alecthomas/chroma/blob/master/lexers/g/genshi.go#L27).

**Comment by Splode** [comment]
What's the status of the Vue SFC support? I ran into this issue when using Hugo, too.
