### ISSUE TITLE
Better support for word-wrapping by rendering code as ordered lists

### ISSUE THREAD

**Issue by iafan** [alecthomas/chroma#153]
Right now HTML produced by Chroma doesn't seem to play nice with word wrapping. If I e.g. set `word-break: break-all; white-space: pre-line` (the best option I can get to to automatically wrap long strings, line indents are gone, and line numbers are treated essentially as a part of the code, so wrapped lines bleed into the gutter area:

![screen shot 2018-06-25 at 00 21 42](https://user-images.githubusercontent.com/1728158/41835835-c536d9ec-780d-11e8-95b3-2d99bfb2cc72.png)

I think this could be improved by providing a rendering option that:

1. uses ordered lists for numbering instead of individual `<span>N</span>` tags. This will fix the gutter problem.
2. calculates the indent of each line in spaces and multiplies that to a provided width of char in pixels, setting the `padding-left: Npx` style for the `<li>` tag that wraps the line; the line itself is trimmed.
3. For blank lines, uses `<li>&nbsp;</li>`

This is how the code on the screenshot above might look like:

```html
<ol class="c-chroma">
    <li><span class="c-kn">package</span> <span class="c-nx">main</span></li>
    <li>&nbsp;</li>
    <li><span class="c-kn">import</span> <span class="c-p">(</span></li>
    <li style="padding-left:36px"><span class="c-s">"fmt"</span></li>
    <li><span class="c-p">)</span></li>
    <li>&nbsp;</li>
    <li><span class="c-kd">func</span> <span class="c-nx">main</span><span class="c-p">(</span><span class="c-p">)</span> <span class="c-p">{</span></li>
    <li style="padding-left:36px"><span class="c-nx">fmt</span><span class="c-p">.</span><span class="c-nx">Println</span><span class="c-p">(</span><span class="c-s">"Concurrency is not parallelism."</span><span class="c-p">)</span></li>
    <li><span class="c-p">}</span></pre></li>
</ol>
```

And this is how it can be rendered (I used the HTML code above and added some styling):

![screen shot 2018-06-25 at 00 43 11](https://user-images.githubusercontent.com/1728158/41836978-21646830-7811-11e8-8fb4-2c61e60e848d.png)

As one can see, long HTML lines are wrapped but at the same time they keep the indent, resulting in a nicer looking code. And no horizontal scrollbars!

**Comment by alecthomas** [comment]
Have you tried https://godoc.org/github.com/alecthomas/chroma/formatters/html#LineNumbersInTable?

**Comment by iafan** [comment]
I can try this, but after quickly looking at the code it seems like it doesn't solve the problem with indent-aware wrapping. Ordered lists are also less heavy than tables (and give you line numbers for free).

**Comment by alecthomas** [comment]
It won't fix the indentation, no, but it will prevent the line from wrapping into the numbers.

I'm not specifically opposed to supporting line wrapping, but I don't think it's a significant problem., mainly because a lot of languages lose some level of semantic meaning when they're wrapped arbitrarily.

If you'd like to submit a PR to implement this that isn't too intrusive, I'll take a look.

**Comment by alecthomas** [comment]
(note that it shouldn't modify the existing behaviours, and will have to support all of the options the HTML formatter allows)
