### ISSUE TITLE
Add some margin to the right of linenumbers

### ISSUE THREAD

**Issue by bep** [alecthomas/chroma#16]
![image](https://user-images.githubusercontent.com/394382/30699418-f79b1cac-9ee4-11e7-8371-fb67db5202b3.png)

The above is from the stylesheet generated with Chroma. Notice there is no gap between the grey and the code.

**Comment by alecthomas** [comment]
Interestingly, there is already a margin...

**Comment by bep** [comment]
Sorry, this was my mistake, with this I used "classic Pygments".
