### ISSUE TITLE
Refactor to package lexers, formatter and styles individually

### ISSUE THREAD

**Issue by flowchartsman** [alecthomas/chroma#163]
As part of an ongoing PR I'm working on to enhance the JSON output with actual style information, I initially found myself moving a couple useful methods from the HTML formatter into a utility library under `formatters`.  Eventually I realized each formatter could live in its own directory, they just had to call `formatters.Register()` instead of `register`.  This in turn made me realize that the registries really only exist to help out `cmd/chroma`, and that by moving them there the library could become much more piecemeal, allowing users to compile in just those lexers, formatters and styles they actually needed for their task.  Rather than go ahead with this, I am going to stop my PR with just enhancing JSON output, but I am willing to take on the task of migrating the framework to a more modular design as a step to a future stable release. I think this would greatly enhance the utility of Chroma.

**Comment by alecthomas** [comment]
> This in turn made me realize that the registries really only exist to help out cmd/chroma

That is not really correct. The registries exist to allow tools (including cmd/chroma) to retrieve lexers/formatters by string key. This is also used by eg. Hugo.

> I think this would greatly enhance the utility of Chroma.

In what way would it greatly enhance the utility?

**Comment by flowchartsman** [comment]
> The registries exist to allow tools (including cmd/chroma) to retrieve lexers/formatters by string key. This is also used by eg. Hugo.

Aha, I didn't know Hugo was compiling it in. Yeah if you're compiling it directly in as a dedicated generic syntax engine, it makes a lot more sense.

> In what way would it greatly enhance the utility?

When I wrote that I was thinking about an application I'd written that allows users to upload arbitrary code in a couple of different languages, and I was thinking it would be handy to have a dedicated syntax highlighting engine that only lexed what I cared about, output only in the format I cared about, and used only the color scheme I wanted.  But you know, this is 2018 so not only is disk space/memory that tiny of a concern, so is doing something like this in the backend, when you can more effectively do it in the front-end.

I still think the framework could benefit from a little re-org, but I can experiment with that in my own fork and issue a PR if there's enough of a perceived benefit.  I'm going to close this issue.
