### ISSUE TITLE
Get `err` class in Chroma output for new lexer

### ISSUE THREAD

**Issue by Jos512** [alecthomas/chroma#165]
I've been working on adding a [new lexer](https://github.com/Jos512/chroma/blob/tradingview/lexers/t/tradingview.go), but when testing I get `err` classes added by Chroma for each non-matched character:

```html
<span class="c1"></span><span class="nf">study</span><span class="err">(</span><span class="err">t</span><span class="err">i</span><span class="err">t</span><span class="err">l</span><span class="err">e</span><span class="err">=</span><span class="s">&#34;Bollinger bands alerts [indicator]&#34;</span><span class="p">,</span> <span class="err">o</span><span class="err">v</span><span class="err">e</span><span class="err">r</span><span class="err">l</span><span class="err">a</span><span class="err">y</span><span class="err">=</span><span class="ow">true</span><span class="err">)</span>
```

I understand from the [Pygments doc](http://pygments.org/docs/lexerdevelopment/) that when 'if no rule matches at the current position, the current char is emitted as an Error token that indicates a lexing error'. However, I do have whitespace matching rules for the `Text` token. From how I understand Chroma and the already implemented lexers, that should have Chroma skip those matches.

Can someone give me a pointer or suggestion? I'm going in circles with my own attempts and ideas.

**Comment by alecthomas** [comment]
It looks like "(" is the erroring token, and looking at the code I don't see a pattern for that?

**Comment by Jos512** [comment]
> It looks like "(" is the erroring token, and looking at the code I don't see a pattern for that?

Thanks for the quick reply and the good catch! That one was indeed still missing. Unfortunately there are a lot more error tokens still left.

If I input this:

~~~
study(title="Bollinger bands alerts [indicator]", overlay=true)
~~~

The lexer should turn that into:

Code element | Token
--------------- | ----------
`study` | NameFunction
`"Bollinger bands alerts [indicator]"` | CommentSingle
`,` | Punctuation
`true` | OperatorWord

But I get:

~~~
<span class="nf">study</span>
<span class="err">(</span>
<span class="err">t</span>
<span class="err">i</span>
<span class="err">t</span>
<span class="err">l</span>
<span class="err">e</span>
<span class="err">=</span>
<span class="s">&#34;Bollinger bands alerts [indicator]&#34;</span>
<span class="p">,</span>
<span class="err">o</span>
<span class="err">v</span>
<span class="err">e</span>
<span class="err">r</span>
<span class="err">l</span>
<span class="err">a</span>
<span class="err">y</span>
<span class="err">=</span>
<span class="ow">true</span>
<span class="err">)</span>
~~~

If I update my word lexer to include any word character (`\w`) to `{`[^\S\n\(\)\w]+`, Text, nil},` I still get the same errors.

**Comment by Jos512** [comment]
As a quick update, it seems I've found the problem: I had a missing `Name` token:

~~~
{`@?[_a-zA-Z]\w*`, Name, nil},
~~~

With this line the `err` message seem to go away. 

(It might be too soon to definitely close this PR since I need to do more testing and validating. But I wanted to make a quick comment in case someone else is going to spend time on it, which I wouldn't be comfortable with knowing I've 'wasted' someone's free time.)
