### ISSUE TITLE
Consider move terminal code to a terminal package

### ISSUE THREAD

**Issue by bep** [alecthomas/chroma#17]
Right now the /formatters package contains some dependencies that drags in some unwanted dependencies if you want to, say, just format HTML. I can do without this package at the moment, but it would probably be better to just move the tty stuff to a sub package.

**Comment by alecthomas** [comment]
Moving it to a separate package won't make a difference, as it will still be included by the Registry, unless you can somehow also exclude the `chroma/formatters` package. I assume you're talking about `github.com/lucasb-eyer/go-colorful`?

**Comment by bep** [comment]
>github.com/lucasb-eyer/go-colorful

Yes.

And I don't care about the registry, but it would be nice to use the `formatters.Fallback` without having to include some totally unrelated package.

**Comment by alecthomas** [comment]
I'm only using one function from go-colorful, but I did have a look at it briefly in the past and it looked non-trivial to port. I think I'll revisit that, and port the function directly.
