### ISSUE TITLE
Consider usage of []*Token vs []Token

### ISSUE THREAD

**Issue by eloff** [alecthomas/chroma#175]
Before the library interface has been finalized, it might be a good idea to consider passing Token around by pointer or by value. It should cause a LOT less allocations to use Token (which is a very small struct) by value instead of by pointer, which would speed up this library. It would also eliminate the risk of using nil Token pointers.

Think about it anyway, because if you're ever going to need to make that change it will be much less painful to do it now.

**Comment by alecthomas** [comment]
I originally had the tokens as values but changed it (for reasons I can no longer recall)...

**Comment by eloff** [comment]
Would you consider accepting a PR changing it to passing by value? Or do you think that's a bad idea?

**Comment by alecthomas** [comment]
In fact you can see it [here](https://github.com/alecthomas/chroma/commit/b2fb8edf77cc67ad2328e54c76e7c0dd9f6887cb#diff-0224885fe69be6593379df5a33ef351dR17) in the early commits.

**Comment by alecthomas** [comment]
And [here's](1f47bd705c6f7ee6eb5dc0dc5186b756422801e1) where I changed it to pointers, though unfortunately I didn't write a reason in the commit :\.

**Comment by eloff** [comment]
There may have been a good reason for it, but I think it should be possible to structure the code either way successfully. Do you mind if I give it a go? As long as it's something you'd consider merging I would be willing to take the time to do it.

**Comment by alecthomas** [comment]
Sure thing.

**Comment by alecthomas** [comment]
This has been done. Thanks @eloff !
