### ISSUE TITLE
Unreachable code in lexers/h/http.go

### ISSUE THREAD

**Issue by octomarat** [alecthomas/chroma#181]
Hi!

I am writing a tool to detect unreachable code in Go programs. I used your project to test it and found a couple of issues:
https://github.com/alecthomas/chroma/blob/095524152564f863a016c137d17efc785fc7c6a1/lexers/h/http.go#L80
https://github.com/alecthomas/chroma/blob/095524152564f863a016c137d17efc785fc7c6a1/lexers/h/http.go#L125
In both cases, post conditions of the loops will never be executed. 
As far as I can see, this doesn't actually affect the logic of the code. But the code could be simplified by removing loops.

**Comment by alecthomas** [comment]
I don't really understand what you mean. Why do you believe these loops will never execute?

**Comment by octomarat** [comment]
Loops are executed, but exactly once. For example, in the second case, we init ‘token’ with ‘subIterator()’, check it is not ‘nil’ and return from the enclosing function. As a result, we don’t go into second iteration and don’t execute post statement ‘token := subIterator()’ in the loop.

So, actually, they are not loops. They are equivalent to ‘if’ statements.

**Comment by alecthomas** [comment]
Ah, you didn't mention the inner return in your initial report so it wasn't clear. Fixed!
