### ISSUE TITLE
More frequent (minor) releases?

### ISSUE THREAD

**Issue by Jos512** [alecthomas/chroma#189]
Is it possible to release a new version of Chroma more frequent? 

I'm using Chroma through Hugo, and I'm waiting to use a new lexer and fixes to other lexers. But without a release the latest Chroma is not included in Hugo (and possibly other projects too).

I see the last release happened in the start of August. If it's not too much additional work, would it be an idea to release every 2-3 months? Even a small 0.5.0.1 release would be very helpful to get the latest Chroma additions and tweaks in projects that depend on Chroma.

Thanks for your consideration.

**Comment by alecthomas** [comment]
Sure!

**Comment by alecthomas** [comment]
Tagged 0.6.0!
