### ISSUE TITLE
Markdown lexer error with ** or __ (bold)

### ISSUE THREAD

**Issue by rcoreilly** [alecthomas/chroma#193]
If you look at the tokens generated for this text for markdown:

```markdown
Test **bold** this is the problem.
```

there is an erroneous, redundant "None" type there for the trailing ** :

```
type: Text  st: 0  ed: 5  txt: Test 
type: GenericStrong  st: 5  ed: 13  txt: **bold**
type: None  st: 13  ed: 15  txt: **
type: Text  st: 15  ed: 36  txt:  this is the problem.
```

also, likely relatedly, it does not handle repeated **bold** and **more bold** text on a single line -- makes everything in between bold.

Same thing also happens with the other way of doing bold:
 ```markdown
__bold__
```

**Comment by alecthomas** [comment]
Thanks for reporting this!

**Comment by dezza** [comment]
I have another possible problem. I cannot get the markdown lexer to react on the first line
`echo "**john**\n**john**" | chroma --lexer='markdown'`

Only second line is parsed to bold.
