### ISSUE TITLE
Support Rust raw string literals

### ISSUE THREAD

**Issue by rakenodiax** [alecthomas/chroma#202]
In Rust, raw string literals can be written as:

```rust
let some_string = r"\\\"foo\n";
let with_quotes = r#"this is allowed: ""#;
let raw_markdown = r###"## header with "quotes""###;
```

They are described in more detail [here](https://doc.rust-lang.org/reference/tokens.html#raw-string-literals). Currently chroma does the following highlighting:

![image](https://user-images.githubusercontent.com/33138989/49578799-d74f6180-f94a-11e8-87e8-18adcb2764d6.png)

**Comment by alecthomas** [comment]
PRs welcome.

**Comment by nu8** [comment]
https://github.com/alecthomas/chroma/issues/202
https://github.com/alecthomas/chroma/issues/412
https://github.com/alecthomas/chroma/pull/229
