### ISSUE TITLE
I cannot get HighlightLines working

### ISSUE THREAD

**Issue by bep** [alecthomas/chroma#21]
![image](https://user-images.githubusercontent.com/394382/30757053-80443e10-9fcd-11e7-940c-93dc59bbc59e.png)

Given the program below; I notice that the output changes when I add a line range, but I cannot see any visually different.

```go
package main

import (
	"log"
	"os"

	"io"

	"github.com/alecthomas/chroma"
	"github.com/alecthomas/chroma/formatters"
	"github.com/alecthomas/chroma/formatters/html"
	"github.com/alecthomas/chroma/lexers"
	"github.com/alecthomas/chroma/styles"
)

func main() {

	source := `package main

import (
	"fmt"
	"log"

	"github.com/alecthomas/chroma/formatters"
	"github.com/alecthomas/chroma/formatters/html"
)

func main() {
	
	var source = "foo2"

	err := quick.Highlight(os.Stdout, source, "go", "html", "monokai")

	if err != nil {
		log.Fatal(err)
	}
}`
	out, err := os.OpenFile("/Users/bep/hl.html", os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0755)
	if err != nil {
		log.Fatal(err)
	}

	options := []html.Option{
		html.Standalone(),
		html.WithLineNumbers(),
		html.HighlightLines([][2]int{[2]int{11, 16}}),
		html.TabWidth(4)}

	formatters.Register("html", html.New(options...))

	err = highlight(out, source, "go", "html", "trac")

	if err != nil {
		log.Fatal(err)
	}
}

func highlight(w io.Writer, source, lexer, formatter, style string) error {
	l := lexers.Get(lexer)
	if l == nil {
		l = lexers.Analyse(source)
	}
	if l == nil {
		l = lexers.Fallback
	}
	l = chroma.Coalesce(l)

	f := formatters.Get(formatter)
	if f == nil {
		f = formatters.Fallback
	}

	s := styles.Get(style)
	if s == nil {
		s = styles.Fallback
	}

	it, err := l.Tokenise(nil, source)
	if err != nil {
		return err
	}

	return f.Format(w, s, it)
}

```

**Comment by alecthomas** [comment]
There are no default LineHighlight colours. Our discussion about automatically determining what colour to use was related to tthis.

**Comment by alecthomas** [comment]
You can see that in the command line tool [here](https://github.com/alecthomas/chroma/blob/master/cmd/chroma/main.go#L101-L109).

**Comment by bep** [comment]
OK, I didn't really understand the previous discussion, I assumed that you picked "some kind of default style", but I guess that does not make much sense, either. But I tested this, and it works. For Hugo, I can just create some pretty default and let the user override it in the config.

**Comment by alecthomas** [comment]
I'm fixing it at the moment, as it's quite confusing I think.

It's going to use the background colour, either lightened or darkened by 10% (depending on if it's a dark or light theme, respectively).

**Comment by alecthomas** [comment]
Also the line numbers will use the `Text` colour, darkened or lightened in a similar but opposite manner.

**Comment by bep** [comment]
OK, I reopen this so you can commit against it if you want.

**Comment by alecthomas** [comment]
Okay, this should be fixed.

Example dark theme (monokai):
![image](https://user-images.githubusercontent.com/41767/30772987-9fe816b4-a0aa-11e7-9943-07ab86c0bfa4.png)

Example light theme (monokailight):
![image](https://user-images.githubusercontent.com/41767/30772994-b25468c0-a0aa-11e7-9dd5-7bbaff33338d.png)
