### ISSUE TITLE
Add support for linenostart

### ISSUE THREAD

**Issue by bep** [alecthomas/chroma#22]
I know I'm pushing it in the feature request department, but I assume this should be easy to add.

In Pygments, the flag is called `linenostart` -- which when set makes the line number start at a different value than the default 1. I assume you can add it as an argument to `WithLineNumbers`.

**Comment by alecthomas** [comment]
I did see that in Pygments, but couldn't really understand what it is for. What is the use case for it?

**Comment by bep** [comment]
> What is the use case for it?

If I want to document some existing big Java class (or whatever) and copy and paste, say, lines 46-200, into my documentation. In that case it would make sense to have it start at counting from 46 so it matches the original file.
