### ISSUE TITLE
Chroma by command-line?

### ISSUE THREAD

**Issue by omrllm** [alecthomas/chroma#234]
Is it possible to use Chroma to syntax highlight a file and convert that file in jsx?

I have tried to `go get -u github.com/alecthomas/chroma/cmd/chroma` & `git clone` the repo, but nothing significant happens.

Or Chroma is available just with Hugo?

**Comment by alecthomas** [comment]
The `go get` line is the bit you need. It will put the binary in `$GOBIN` (which defaults to `$GOPATH/bin`, often `~/go/bin`).

**Comment by alecthomas** [comment]
There are also binaries on the releases page...

**Comment by omrllm** [comment]
I have tried to install the linux & windows binaries, but nothing happens.
Same story if I try to start them from terminal & Allow executing file as program is enabled.

OS -> Fedora 29

**Comment by alecthomas** [comment]
Dude what does “nothing happens” mean?Provide useful information in your reports.
