### ISSUE TITLE
How to disable line wrap?

### ISSUE THREAD

**Issue by ezh** [alecthomas/chroma#241]
I'm using chroma as colorizer for preview window in my file manager like
```
chroma -f terminal file_for_preview
```
Line wraps are creating a lot of noise.

Is it possible to disable them?

**Comment by alecthomas** [comment]
When you say "line wrap" do you mean newlines? If so, Chroma shouldn't introduce any newlines that aren't in the source.

**Comment by ezh** [comment]
Indeed, sorry. I was confused with 'less -S' mode.
