### ISSUE TITLE
Issue with Erlang highlighting adding 'err' class

### ISSUE THREAD

**Issue by tsloughter** [alecthomas/chroma#242]
When highlighting Erlang code blocks chroma is mistakenly marking `>` and the whitespace after it with the css class `err`. As shown in this screenshot:

![image](https://user-images.githubusercontent.com/36227/55292895-5579bd00-53ad-11e9-88fb-4d4274cc7993.png)

The css for the `->` in the image is:

```css
<span class="p">-</span>
<span class="err">&gt;</span>
```

However when highlighted with pygments:

![image](https://user-images.githubusercontent.com/36227/55292900-5dd1f800-53ad-11e9-8a31-844703f079be.png)

```css
<span class="o">-&gt;</span>
```

The issue is also visible on the OpenCensus quickstart guide which also uses Hugo and Chroma https://opencensus.io/quickstart/erlang/tracing/

**Comment by alecthomas** [comment]
Can you paste some source so I can replicate this?

**Comment by alecthomas** [comment]
You also might want to try latest master; there was a bug related to newlines that I fixed.

**Comment by alecthomas** [comment]
Turns out this is a bit more of a fundamental issue than expected. Specifically, Chroma patterns that match on beginning of line will always succeed. In this case, Erlang directives (eg. `-import`) match on a `-` at the beginning of a line, but as this always succeeds in Chroma, `->` matches a directive but `>` is invalid, and errors.

**Comment by tsloughter** [comment]
Ah, hm, but the `->` isn't at the beginning of a line?

**Comment by alecthomas** [comment]
Exactly!

**Comment by alecthomas** [comment]
Okay, this should be fixed now.

**Comment by tsloughter** [comment]
Great, thanks! Will give it a try soon.
