### ISSUE TITLE
Default cases prefixed with newline

### ISSUE THREAD

**Issue by rips-hb** [alecthomas/chroma#244]
I encounter a problem where default cases in a switch statement are prefixed with a newline that is not there in the original code. I am using 0.6.3.

Here is an example file where it occurs: https://raw.githubusercontent.com/apache/incubator-dubbo/dubbo-2.7.1/dubbo-common/src/main/java/org/apache/dubbo/common/json/JSON.java

If you highlight it with "chroma -f html JSON.java" you will notice that in line 316 there is a newline that is not there in the original code. In line 364, 402, 441, and 446 it is the same.

**Comment by alecthomas** [comment]
I think this might be fixed in latest master. PTAL.

**Comment by rips-hb** [comment]
Great, thanks a lot, Alec! I will test it once I am back from vacation.

**Comment by rips-hb** [comment]
It is fixed, thanks Alec.
