### ISSUE TITLE
terraform snippet highlighted poorly

### ISSUE THREAD

**Issue by damienpontifex** [alecthomas/chroma#246]
I'm using hugo and have a terraform snippet which seems to be highlighted incorrectly. 
<img width="718" alt="image" src="https://user-images.githubusercontent.com/1321276/56486273-751e8400-651a-11e9-9891-c2a2ee1cb98d.png">

With the original text block being (formatting on GitHub here with ```terraform as in blog content)
```terraform
resource "azurerm_app_service_plan" "test" {
  name                = "${var.app_name}-appserviceplan"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  sku {
    tier = "Free"
    size = "F1"
  }
}

resource "azurerm_app_service" "test" {
  name                = "${var.app_name}-app-service"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  app_service_plan_id = "${azurerm_app_service_plan.test.id}"

  identity {
    type = "SystemAssigned"
  }
}
```

Other blocks do the same thing where the first line seems to be fine, but then get the blocked red backgrounds for any lines after that.

**Comment by alecthomas** [comment]
Thanks for reporting; this turned out to be a very surprising rule in Pygments that I hadn't replicated. Try latest master and it should work.

**Comment by damienpontifex** [comment]
Thanks for the prompt reply @alecthomas! :) 
I'm using this through https://github.com/gohugoio/hugo. Will there be a release soon with the fix that I could update the dependency in the hugo repo to utilise? Maybe a 0.6.4?

**Comment by alecthomas** [comment]
Can you not utilise it via master? I don't really want to do a point release for every single commit just because of Hugo.

**Comment by damienpontifex** [comment]
I'll look into it. I can always clone hugo and update the dependency to master. Then use a local build until it's integrated in the future. Thanks for the assistance
