### ISSUE TITLE
pygments2chroma doesn't handle special characters

### ISSUE THREAD

**Issue by hwayne** [alecthomas/chroma#251]
See 
https://github.com/alecthomas/chroma/blob/1327f9145ea6a0c6e7651d973270190a814bd92b/_tools/pygments2chroma.py#L23
and
https://github.com/alecthomas/chroma/blob/1327f9145ea6a0c6e7651d973270190a814bd92b/_tools/pygments2chroma.py#L188.

I found this out because I was trying to convert a [pygments lexer](https://github.com/hwayne/tla-pygments/blob/master/tlalexer/lexer.py#L8) with name "TLA+" to chroma. The conversion worked, but then `gofmt` failed because one variable was named `var Tla+`.

**Comment by alecthomas** [comment]
The tool is best effort and (almost deliberately) doesn't try to be too smart about naming. You'll almost always have to edit the file to fix some issues.
