### ISSUE TITLE
Clojure latex is wrong

### ISSUE THREAD

**Issue by kwladyka** [alecthomas/chroma#259]
I moved the issue from Hugo to Chroma.

https://github.com/gohugoio/hugo/issues/6068

**Comment by Jos512** [comment]
It's not my issue but since I read the discussion over at Hugo I do feel some responsibility to make this Chroma issue report a bit better. Else people have to spend just to find the snippets in that Hugo issue and linked resources.

-----

Problem is that this Clojure code:

~~~
(def counter (atom 0))
(def foo (atom 1))
(defn slow-inc [n]
  (swap! counter inc)
  (Thread/sleep 200)
  (inc n))

(pmap
  (fn [_]
    (swap! foo slow-inc))
  (range 100))

@counter
@foo
~~~

Renders as the following with Chroma:

~~~html
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-clojure" data-lang="clojure">(<span style="color:#66d9ef">def </span>counter (atom <span style="color:#ae81ff">0</span>))
(<span style="color:#66d9ef">def </span>foo (atom <span style="color:#ae81ff">1</span>))
(<span style="color:#66d9ef">defn </span>slow-inc [n]
  (swap! counter inc)
  (Thread/sleep <span style="color:#ae81ff">200</span>)
  (inc n))

(pmap
  (<span style="color:#66d9ef">fn </span>[_]
    (swap! foo slow-inc))
  (range <span style="color:#ae81ff">100</span>))

<span style="color:#f92672">@</span>counter
<span style="color:#f92672">@</span>foo
=&gt; <span style="color:#ae81ff">1602</span>
=&gt; <span style="color:#ae81ff">101</span></code></pre></div>
~~~

Several things are not highlighted here:

- `Thread/sleep`
- `inc`
- `swap!`
- `pmap`

Those keywords are indeed not in [the Clojure lexer](https://github.com/alecthomas/chroma/blob/master/lexers/c/clojure.go).

So a better, more positive, issue title would be: "Clojure lexers misses some tokens". Other than those missing compontents, the Clojure lexer is not wrong or faulty.

**Comment by kwladyka** [comment]
Actually is something more like for example each word as a first in `()` should be marked as different colour, because first word in `()` is always name of function. Value 0 should be in different colour because it is data. There is probably more, but I don't have any idea how to describe Clojure syntax in easy way. I guess the best is copy it from other solution like https://highlightjs.org/ or http://pygments.org/?

**Comment by Jos512** [comment]
> I guess the best is copy it from other solution like (...) http://pygments.org/?

Yes, Chroma has [a tool](https://github.com/alecthomas/chroma/blob/master/_tools/pygments2chroma.py) to convert Pygments lexers to Chroma's Go, so that should replicate the same Pygments behaviour here in Chroma. :slightly_smiling_face:

**Comment by kwladyka** [comment]
But it doesn't :)
http://pygments.org/ has a different output, than Hugo (Chroma as I understand).

**Comment by alecthomas** [comment]
Yes, as @Jos512 mentioned, please don't just create an issue here and link to random other issues. If you want something fixed, providing as much information as possible, as easily as possible, is the best approach.

That said, I can't replicate this. I get the following HTML:

```html
<pre class="chroma"><span class="p">(</span><span class="k">def </span><span class="nv">counter</span> <span class="p">(</span><span class="nf">atom</span> <span class="mi">0</span><span class="p">))</span>
<span class="p">(</span><span class="k">def </span><span class="nv">foo</span> <span class="p">(</span><span class="nf">atom</span> <span class="mi">1</span><span class="p">))</span>
<span class="p">(</span><span class="kd">defn </span><span class="nv">slow-inc</span> <span class="p">[</span><span class="nv">n</span><span class="p">]</span>
  <span class="p">(</span><span class="nf">swap!</span> <span class="nv">counter</span> <span class="nv">inc</span><span class="p">)</span>
  <span class="p">(</span><span class="nf">Thread/sleep</span> <span class="mi">200</span><span class="p">)</span>
  <span class="p">(</span><span class="nb">inc </span><span class="nv">n</span><span class="p">))</span>

<span class="p">(</span><span class="nf">pmap</span>
  <span class="p">(</span><span class="k">fn </span><span class="p">[</span><span class="nv">_</span><span class="p">]</span>
    <span class="p">(</span><span class="nf">swap!</span> <span class="nv">foo</span> <span class="nv">slow-inc</span><span class="p">))</span>
  <span class="p">(</span><span class="nb">range </span><span class="mi">100</span><span class="p">))</span>

<span class="o">@</span><span class="nv">counter</span>
<span class="o">@</span><span class="nv">foo</span>
</pre>
```

All tokens are highlighted, it just depends on the style as to whether a token will look different.

**Comment by alecthomas** [comment]
Superficially this HTML looks identical to Pygments, so I don't know why you're seeing something different in Hugo to what I get.

To replicate, with current master do:

```
chroma --html-only --html ./t.clj
```

**Comment by kwladyka** [comment]
@alecthomas 
For example:
`counter (atom <span style="color:#ae81ff">0</span>`
vs
`(</span><span class="nf">atom</span> <span class="mi">0</span><span class="p">))</span>`

it is totally different.

> link to random other issues

It is not random. It is one well described source of the issue with context of the tool. I can't describe it better. I am Hugo user, not Chroma. I use Choma by Hugo. Hugo community said it is Chroma issue, so I am here. What more exactly do you need from me to describe?

**Comment by kwladyka** [comment]
@alecthomas Hmm but from what you pasted in Hugo issue it looks like maybe it is Hugo issue, not Chroma. Personally I have no idea.

**Comment by moorereason** [comment]
@alecthomas,
Please consider reopening this issue.  I can reproduce from chroma cli.  Hugo defaults to **inline styles** which is gives visually different output from the class version.  It appears to be an incompatibility between the background color and the token styles (see [formatters/html/html.go:309](https://github.com/alecthomas/chroma/blob/2b84f4bd4d97fad818ec377cca9a4c6f73c94309/formatters/html/html.go#L308-L313)).

```html
<pre style="color:#e5e5e5;background-color:#000">(<span style="color:#fff;font-weight:bold">def </span>counter (atom <span style="color:#ff0;font-weight:bold">0</span>))
(<span style="color:#fff;font-weight:bold">def </span>foo (atom <span style="color:#ff0;font-weight:bold">1</span>))
(<span style="color:#fff;font-weight:bold">defn </span>slow-inc [n]
  (swap! counter inc)
  (Thread/sleep <span style="color:#ff0;font-weight:bold">200</span>)
  (<span style="color:#fff;font-weight:bold">inc </span>n))

(pmap
  (<span style="color:#fff;font-weight:bold">fn </span>[_]
    (swap! foo slow-inc))
  (<span style="color:#fff;font-weight:bold">range </span><span style="color:#ff0;font-weight:bold">100</span>))

@counter
@foo
</pre>
```

Replicate with:
```
chroma --html-only --html --html-inline-styles ./t.clj
```

**Comment by alecthomas** [comment]
The colours depend on the style. If you use Monokai you'll get this:

```html
$ chroma -s monokai --html-only --html --html-inline-styles ./t.clj
<pre style="color:#f8f8f2;background-color:#272822">(<span style="color:#66d9ef">def </span>counter (<span style="color:#a6e22e">atom</span> <span style="color:#ae81ff">0</span>))
(<span style="color:#66d9ef">def </span>foo (<span style="color:#a6e22e">atom</span> <span style="color:#ae81ff">1</span>))
(<span style="color:#66d9ef">defn </span>slow-inc [n]
  (<span style="color:#a6e22e">swap!</span> counter inc)
  (<span style="color:#a6e22e">Thread/sleep</span> <span style="color:#ae81ff">200</span>)
  (inc n))

(<span style="color:#a6e22e">pmap</span>
  (<span style="color:#66d9ef">fn </span>[_]
    (<span style="color:#a6e22e">swap!</span> foo slow-inc))
  (range <span style="color:#ae81ff">100</span>))

<span style="color:#f92672">@</span>counter
<span style="color:#f92672">@</span>foo
</pre>
```

**Comment by alecthomas** [comment]
(not that there may not also be a bug)

**Comment by kwladyka** [comment]
I will describe issue once again getting what we discovered already:

Hugo generat this, because use **inline styles**.
Recreate: `chroma --html-only --html --html-inline-styles ./t.clj`
```html
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-clojure" data-lang="clojure">(<span style="color:#66d9ef">def </span>counter (atom <span style="color:#ae81ff">0</span>))
(<span style="color:#66d9ef">def </span>foo (atom <span style="color:#ae81ff">1</span>))
(<span style="color:#66d9ef">defn </span>slow-inc [n]
  (swap! counter inc)
  (Thread/sleep <span style="color:#ae81ff">200</span>)
  (inc n))

(pmap
  (<span style="color:#66d9ef">fn </span>[_]
    (swap! foo slow-inc))
  (range <span style="color:#ae81ff">100</span>))

<span style="color:#f92672">@</span>counter
<span style="color:#f92672">@</span>foo
=&gt; <span style="color:#ae81ff">1602</span>
=&gt; <span style="color:#ae81ff">101</span></code></pre></div>
```

We expect this:
Recreate correct HTML`chroma --html-only --html ./t.clj`.
```html
<div class="hlcode">
<div class="syntax"><pre><span></span><span class="p">(</span><span class="k">def </span><span class="nv">counter</span> <span class="p">(</span><span class="nf">atom</span> <span class="mi">0</span><span class="p">))</span>
<span class="p">(</span><span class="k">def </span><span class="nv">foo</span> <span class="p">(</span><span class="nf">atom</span> <span class="mi">1</span><span class="p">))</span>
<span class="p">(</span><span class="kd">defn </span><span class="nv">slow-inc</span> <span class="p">[</span><span class="nv">n</span><span class="p">]</span>
  <span class="p">(</span><span class="nf">swap!</span> <span class="nv">counter</span> <span class="nv">inc</span><span class="p">)</span>
  <span class="p">(</span><span class="nf">Thread/sleep</span> <span class="mi">200</span><span class="p">)</span>
  <span class="p">(</span><span class="nb">inc </span><span class="nv">n</span><span class="p">))</span>

<span class="p">(</span><span class="nf">pmap</span>
  <span class="p">(</span><span class="k">fn </span><span class="p">[</span><span class="nv">_</span><span class="p">]</span>
    <span class="p">(</span><span class="nf">swap!</span> <span class="nv">foo</span> <span class="nv">slow-inc</span><span class="p">))</span>
  <span class="p">(</span><span class="nb">range </span><span class="mi">100</span><span class="p">))</span>

<span class="o">@</span><span class="nv">counter</span>
<span class="o">@</span><span class="nv">foo</span>
</pre></div>

</div>
```

In simple words: `--html-inline-styles` generate wrong syntax highlight for Clojure.

To understand deep details of "wrong" you will have to learn Clojure syntax. It is not easy to explain. But the point without `--html-inline-styles` is good enough. So why such difference?

**Comment by kwladyka** [comment]
Ok I tested if myself and while I have:
```html
<div class="highlight"><pre class="chroma"><code class="language-clojure" data-lang="clojure"><span class="p">(</span><span class="k">def </span><span class="nv">counter</span> <span class="p">(</span><span class="nv">atom</span> <span class="mi">0</span><span class="p">))</span>
<span class="p">(</span><span class="k">def </span><span class="nv">foo</span> <span class="p">(</span><span class="nv">atom</span> <span class="mi">1</span><span class="p">))</span>
<span class="p">(</span><span class="kd">defn </span><span class="nv">slow-inc</span> <span class="p">[</span><span class="nv">n</span><span class="p">]</span>
  <span class="p">(</span><span class="nv">swap!</span> <span class="nv">counter</span> <span class="nv">inc</span><span class="p">)</span>
  <span class="p">(</span><span class="nv">Thread/sleep</span> <span class="mi">200</span><span class="p">)</span>
  <span class="p">(</span><span class="nb">inc </span><span class="nv">n</span><span class="p">))</span>

<span class="p">(</span><span class="nv">pmap</span>
  <span class="p">(</span><span class="k">fn </span><span class="p">[</span><span class="nv">_</span><span class="p">]</span>
    <span class="p">(</span><span class="nv">swap!</span> <span class="nv">foo</span> <span class="nv">slow-inc</span><span class="p">))</span>
  <span class="p">(</span><span class="nb">range </span><span class="mi">100</span><span class="p">))</span>

<span class="o">@</span><span class="nv">counter</span>
<span class="o">@</span><span class="nv">foo</span>
<span class="nv">=&gt;</span> <span class="mi">1602</span>
<span class="nv">=&gt;</span> <span class="mi">101</span></code></pre></div>
```

Which looks like a good HTML it is still wrong highlighted. But in Hugo! and by `chroma --html-only --html --html-inline-styles ./t.clj`.
On http://pygments.org/ it works.

So... I have no idea why it is happening. I would say first though of @moorereason is right. https://github.com/alecthomas/chroma/blob/0c0b382eca61a71c1eb4cb4dea2bc78aa4939d96/lexers/c/clojure.go has to be wrong.

It works good here http://pygments.org/

I am sorry I can't describe it better but I don't know how you use pygments in Chroma etc. If you can make Chroma generate the same highlight like pygments, than it will be good.

**Comment by moorereason** [comment]
To clear this up, everything is working correctly.

I was wrong in pointing the finger at inline styles, which are correct above because the default `swapoff` theme is much simpler with less highlighting than `perldoc` (test it [here](https://swapoff.org/chroma/playground/)).  To test the `perldoc` style from the command line, use:

```
chroma --html-only --html --html-inline-styles --style=perldoc ./t.clj
```
