### ISSUE TITLE
Syntax highlighting ‘specificity’ lower compared to text editors

### ISSUE THREAD

**Issue by lifepeer** [alecthomas/chroma#260]
I'm using the built-in Chroma syntax highlighter with Hugo but it seems to lack specificity compared to let's say VSCode or Atom. Consider the following example in JavaScript:

![ggdf](https://user-images.githubusercontent.com/17163509/61190092-fc514300-a696-11e9-8671-ce99d4741253.jpg)

As you can see, the output from Chroma is limited in terms of how many different ‘elements’ it recognises.

This is confirmed by using the Hugo option `pygmentsUseClasses=true` and inspecting the classes it assigns to elements which are highlighted using different colours in text editors but the same once processed by Chroma, for example ‘target’ and ‘offset’ both share the `class="nx"` even though one is a parameter and the other is a method. Another example is ‘this’ and ‘return’ which are both `class="k"`.

This issue is even more striking if you use some other language like R, which looks like there's almost no syntax highlighting at all… :(

![hfgdh](https://user-images.githubusercontent.com/17163509/61190321-ce6dfd80-a69a-11e9-9b63-bbc6798d6d35.jpg)

Is it possible to set up Chroma to differentiate between such elements and assign them different classes, please?

**Comment by alecthomas** [comment]
Pygments lexers are translated into Chroma lexers automatically, but some constructs cannot be trivially mapped. Different Pygments lexers use this functionality more than others and so some Chroma lexers will be less at parity with Pygments.

I've synced the R lexer with the latest from Pygments and it seems to have improved:

![image](https://user-images.githubusercontent.com/41767/61210810-fd3eaf00-a740-11e9-9387-823abab7f87a.png)

**Comment by alecthomas** [comment]
To summarise, Chroma will typically be at parity with Pygments if its lexers are up to date, but for some it will not be and cannot be without manual translation effort. Contributions welcome.

**Comment by lifepeer** [comment]
I see, thank you for the explanation. Indeed, the latest R lexer appears to be improved because while function names were left without a class in my example above, they are now given the correct `nf` class according to the [demo at Pygments](http://pygments.org/demo/6850979/) which reflects your screenshot.

This falls outside my area of expertise but since it appears to be mostly an issue of selecting appropriate regex patterns to differentiate between various elements, I might be able to contribute—in this instance, should I aim to alter the Pygments R lexer or the Chroma one directly? I've looked at both sources and it appears the automatic translation works well in this instance, though that's just my noob impression.

**Comment by alecthomas** [comment]
Yep this one is entirely automatic. If you update the Pygments lexer I can just sync it into Chroma. That would be ideal for Pygments and Chroma.
