### ISSUE TITLE
including chroma brings a lot of dependencies

### ISSUE THREAD

**Issue by kjk** [alecthomas/chroma#261]
Consider the simplest program including chroma package:
```go
package main

import (
	"fmt"
	_ "github.com/alecthomas/chroma"
)

func main() {
	fmt.Printf("Hello\n")
}
```
with `go.mod`:
```
module tst

go 1.12

require github.com/alecthomas/chroma v0.6.5
```
When you `go build` it, `go.sum` ends up being:
```
github.com/GeertJohan/go.incremental v1.0.0/go.mod h1:6fAjUhbVuX1KcMD3c8TEgVUqmo4seqhv0i0kdATSkM0=
github.com/GeertJohan/go.rice v1.0.0/go.mod h1:eH6gbSOAUv07dQuZVnBmoDP8mgsM1rtixis4Tib9if0=
github.com/akavel/rsrc v0.8.0/go.mod h1:uLoCtb9J+EyAqh+26kdrTgmzRBFPGOolLWKpdxkKq+c=
github.com/alecthomas/assert v0.0.0-20170929043011-405dbfeb8e38/go.mod h1:r7bzyVFMNntcxPZXK3/+KdruV1H5KSlyVY0gc+NgInI=
github.com/alecthomas/chroma v0.6.5 h1:1gZ11dfxovHkbAM+xzyxjgxhG3Gr7U/cfOXI2eoEBkU=
github.com/alecthomas/chroma v0.6.5/go.mod h1:fmawHw4BldtHEYrwSxw+YmP0eiiT7JdI1JXEVxmW+nE=
github.com/alecthomas/colour v0.0.0-20160524082231-60882d9e2721/go.mod h1:QO9JBoKquHd+jz9nshCh40fOfO+JzsoXy8qTHF68zU0=
github.com/alecthomas/kong v0.1.13/go.mod h1:0m2VYms8rH0qbCqVB2gvGHk74bqLIq0HXjCs5bNbNQU=
github.com/alecthomas/kong v0.1.15/go.mod h1:0m2VYms8rH0qbCqVB2gvGHk74bqLIq0HXjCs5bNbNQU=
github.com/alecthomas/kong-hcl v0.1.7/go.mod h1:+diJg0tzfMUY/5uDo0dlb7uThhVpWr59PuYkdtRJbms=
github.com/alecthomas/repr v0.0.0-20180818092828-117648cd9897/go.mod h1:xTS7Pm1pD1mvyM075QCDSRqH6qRLXylzS24ZTpRiSzQ=
github.com/daaku/go.zipexe v1.0.0/go.mod h1:z8IiR6TsVLEYKwXAoE/I+8ys/sDkgTzSL0CLnGVd57E=
github.com/danwakefield/fnmatch v0.0.0-20160403171240-cbb64ac3d964/go.mod h1:Xd9hchkHSWYkEqJwUGisez3G1QY8Ryz0sdWrLPMGjLk=
github.com/davecgh/go-spew v1.1.0/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
github.com/davecgh/go-spew v1.1.1/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
github.com/dlclark/regexp2 v1.1.6 h1:CqB4MjHw0MFCDj+PHHjiESmHX+N7t0tJzKvC6M97BRg=
github.com/dlclark/regexp2 v1.1.6/go.mod h1:2pZnwuY/m+8K6iRw6wQdMtk+rH5tNGR1i55kozfMjCc=
github.com/gorilla/csrf v1.6.0/go.mod h1:7tSf8kmjNYr7IWDCYhd3U8Ck34iQ/Yw5CJu7bAkHEGI=
github.com/gorilla/handlers v1.4.1/go.mod h1:Qkdc/uu4tH4g6mTK6auzZ766c4CA0Ng8+o/OAirnOIQ=
github.com/gorilla/mux v1.7.3/go.mod h1:1lud6UwP+6orDFRuTfBEV8e9/aOM/c4fVVCaMa2zaAs=
github.com/gorilla/securecookie v1.1.1/go.mod h1:ra0sb63/xPlUeL+yeDciTfxMRAA+MP+HVt/4epWDjd4=
github.com/hashicorp/hcl v1.0.0/go.mod h1:E5yfLk+7swimpb2L/Alb/PJmXilQ/rhwaUYs4T20WEQ=
github.com/jessevdk/go-flags v1.4.0/go.mod h1:4FA24M0QyGHXBuZZK/XkWh8h0e1EYbRYJSGM75WSRxI=
github.com/mattn/go-colorable v0.0.9/go.mod h1:9vuHe8Xs5qXnSaW/c/ABM9alt+Vo+STaOChaDxuIBZU=
github.com/mattn/go-isatty v0.0.4/go.mod h1:M+lRXTBqGeGNdLjl/ufCoiOlB5xdOkqRJdNxMWT7Zi4=
github.com/nkovacs/streamquote v0.0.0-20170412213628-49af9bddb229/go.mod h1:0aYXnNPJ8l7uZxf45rWW1a/uME32OF0rhiYGNQ2oF2E=
github.com/pkg/errors v0.8.0/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=
github.com/pmezard/go-difflib v1.0.0/go.mod h1:iKH77koFhYxTK1pcRnkKkqfTogsbg7gZNVY4sRDYZ/4=
github.com/sergi/go-diff v1.0.0/go.mod h1:0CfEIISq7TuYL3j771MWULgwwjU+GofnZX9QAmXWZgo=
github.com/stretchr/objx v0.1.0/go.mod h1:HFkY916IF+rwdDfMAkV7OtwuqBVzrE8GR6GFx+wExME=
github.com/stretchr/testify v1.2.2/go.mod h1:a8OnRcib4nhh0OaRAV+Yts87kKdq0PP7pXfy6kDkUVs=
github.com/stretchr/testify v1.3.0/go.mod h1:M5WIy9Dh21IEIfnGCwXGc5bZfKNJtfHm1UVUgZn+9EI=
github.com/valyala/bytebufferpool v1.0.0/go.mod h1:6bBcMArwyJ5K/AmCkWv1jt77kVWyCJ6HpOuEn7z0Csc=
github.com/valyala/fasttemplate v1.0.1/go.mod h1:UQGH1tvbgY+Nz5t2n7tXsz52dQxojPUpymEIMZ47gx8=
golang.org/x/sys v0.0.0-20181128092732-4ed8d59d0b35/go.mod h1:STP8DvDyc/dI5b8T5hshtkjS+E42TnysNCUPdjciGhY=
```
Most of those are dependencies for code under `cmd`.
As a user of the library, I would rather not pull all those dependencies into my project.
It's a real cost (in time and bandwidth) when building things with empty module cache (e.g. on a CI server or after running `go clean -modcache`). 
Moving code under `cmd` to a separate repo (e.g. `chroma-tools`) would fix it.

I'm not sure if there is a solution that preserves co-location of `cmd` code in the same repo as chrome code.

**Comment by kjk** [comment]
After a quick test, it seems like adding `go.mod` file (with unique module names) to `cmd\chroma` and `cmd\chromad` (and running `go mod tidy` on top-level.
It looks like go tool will not scan sub-directories for dependencies if they have their own `go.mod` file.

**Comment by alecthomas** [comment]
None of those dependencies should be included in your project as they are not transitively imported from the chroma package. Are they in your go.mod?

**Comment by kjk** [comment]
You can reproduce this yourself with the simplest repro I described at the top. 

Or just look at https://github.com/alecthomas/chroma/blob/master/go.mod
Package github.com/alecthomas/chroma doesn't import those dependencies either.

`go build` treats sub-directories as part of the package and scans them for dependencies even if they are not explicitly imported from top-level. This is surprising (it was to me) but there probably is a reason for this.

The way to stop that is to put a `go.mod` in the sub-directory, at which point it seems `go build` will consider them separate modules (which does make sense).

**Comment by alecthomas** [comment]
Hmm, yeah.

Have you been able to actually compile `./cmd/chromad` though? It always fails for me with

**Comment by alecthomas** [comment]
No I mean once you add `cmd/chromad/go.mod` it no longer compiles.

**Comment by kjk** [comment]
Are you referring to:
```
can't load package: package github.com/alecthomas/chroma/cmd/chromad: 
unknown import path "github.com/alecthomas/chroma/cmd/chromad": 
ambiguous import: found github.com/alecthomas/chroma/cmd/chromad in multiple modules:
        github.com/alecthomas/chroma/cmd/chromad (C:\Users\kjk\src\chroma\cmd\chromad)
        github.com/alecthomas/chroma v0.6.5 (C:\Users\kjk\go\pkg\mod\github.com\alecthomas\chroma@v0.6.5\cmd\chromad)
```
So it's a pickle. I might be wrong but here's my explanation.

When you `go build github.com/alecthomas/chroma/cmd/chromad` with added `go.mod`, it tries to import latest version of github.com/alecthomas/chroma which happens to be v0.6.5

Version 0.6.5 of github.com/alecthomas/chroma imports version 0.6.5 of github.com/alecthomas/chroma/cmd/chromad

At which point go tool panics with this error message, paraphrased: you asked me to import 2 different versions of github.com/alecthomas/chroma/cmd/chromad.

So how to solve it? I think you have to have faith and do the following:
* add go.mod to cmd/chroma and cmd/chromad
* run mod tidy to remove references to them from github.com/alecthomas/chroma
* check that in
* `cd cmd/chromad` and run: `go get github.com/alecthomas/chroma@master`. Per https://stackoverflow.com/questions/53682247/how-to-point-go-module-dependency-in-go-mod-to-a-latest-commit-in-a-repo it'll switch github.com/alecthomas/chroma/cmd/chromad from v0.6.5 (which doesn't work) to master (which now should work)
* the same for `cmd/chroma`
* check that in
* make a v0.6.6 release
* and you can now undo forcing github.com/alecthomas/chroma@master in cmd/chromad (probably by manually editing go.mod)

**Comment by kjk** [comment]
A simpler option: remove cmd directory completely, mod tidy, check in, tag a new release, add cmd directory back and add go.mod files.
This would loose the history on cmd/ files but is easier to execute.

**Comment by alecthomas** [comment]
Well, I have managed to make it work via replace directives, but it has a few tooling downsides. Most tools do not grok multi-module repositories.

I'm not convinced that the extra complexity is worth it to avoid a few extra dependency downloads.

**Comment by alecthomas** [comment]
I don't think the extra dependencies are ideal, but the extra complexity of multiple module roots is really not great. Sorry.

**Comment by alecthomas** [comment]
Go 1.13 seems to have improved this situation quite a bit, so I've added it to `chromad`!
