### ISSUE TITLE
cpp lexer missing "enum class" type, introduced int cpp11

### ISSUE THREAD

**Issue by eran-** [alecthomas/chroma#272]
cpp lexer is not aware of `enum class` type, and is treating `class` as the name of the `enum` and the actual `enum class` name as a syntax error.

**To Reproduce**
```
enum class EnumClass {
    foo,        
    bar,
    baz
};
```

**Comment by XhmikosR** [comment]
@alecthomas: I think this was wrongfully closed?

**Comment by alecthomas** [comment]
Whoops!
