### ISSUE TITLE
Use long token for code highlighting [HUGO]

### ISSUE THREAD

**Issue by hugoiscrazyxo** [alecthomas/chroma#277]
Hello i'm using HUGO, and i activated, `pygmentsUseClasses` but i want to use the long token for code highlighting how can i do that?

What i want;

`<span class="keyword">const</span>`

What i have ;

`<span class="k">const</span>`

**Comment by alecthomas** [comment]
That is not supported by Chroma. It may be supported by Pygments. 

But why wouldn't you ask this on the Hugo Discourse?

**Comment by hugoiscrazyxo** [comment]
I did both in discourse and on github they told me to ask you.
