### ISSUE TITLE
ABAP Syntax Support

### ISSUE THREAD

**Issue by Stegosawr** [alecthomas/chroma#278]
**What problem does this feature solve?**

Makes .abap files readable. 

**What feature do you propose?**

Add support for the programming language ABAP.

![image](https://user-images.githubusercontent.com/38107067/64865028-b41fb400-d638-11e9-81a8-194168ccf322.png)

(Sorry that the comments are in german, but I think you'll get the point)

**Comment by Jos512** [comment]
Do you have the source code for the code in your screenshot? 

That way we can see if Chroma can be made to recognise the same as your image shows. Is the formatting that your image shows the 'golden standard'?

---
(To prevent duplicate work, a heads up that I started working on this issue.)

**Comment by alecthomas** [comment]
It looks like Pygments has [ABAP](http://pygments.org/docs/lexers/?highlight=console#lexers-for-business-oriented-languages) support, so it should be fairly straightforward.

**Comment by Stegosawr** [comment]
The best ABAP language support comes from SAP themselfs. They have developed a ADK for eclipse maybe you can grab the syntax highlighting from there :)

The formatting in ABAP is a little bit weird. If you want to see some more source code check out [this project](https://github.com/Stegosawr/archiving_engine) on github. 


Source code for the screenshot mentioned above:
(not the golden standard)
`*&---------------------------------------------------------------------*
*& Report  /WUE/AUFGABE_PRIMZAHL
*&
*&---------------------------------------------------------------------*
*& Anmerkung: um bei einer Zahl entscheiden zu können, ob diese eine Primzahl ist,
*&            genügt es die Primzahlen zu prüfen die kleiner gleich der Würzel der Zahl sind
*&
*&---------------------------------------------------------------------*
REPORT /wue/aufgabe_primzahl.


PARAMETERS p_range TYPE i.

"Tabelle in der alle gefundenen Primzahlen gespeichert werden, die kleiner gleich
"der Würzel der eingegebenen Zahl sind
DATA gt_prim_num TYPE TABLE OF i.

"Diese Variable dient dazu, alle Zahlen <= der eingegebenen Zahl und >= 2 aufzustellen
DATA g_number    TYPE i VALUE 1.

"Diese Variable dient dazu, zu sagen, ob die aktuelle g_number eine Primzahl ist oder nicht
DATA g_is_prime  TYPE abap_bool.

"mit sqrt( zahl1 ) kann die Quadratwurzel der Zahl1 berechnet werden
DATA(g_sqrt_range) = sqrt( p_range ).



"da die zu prüfenden Zahlen bei der 2 beginnend durch Addition von 1 aufgestellt werden
"muss die Schleife lediglich p_range - 1 male durchlaufen werden
DO p_range - 1 TIMES.

  "zählt die zu prüfende Zahlen hoch
  ADD 1 TO g_number.

  "grundsätzlich wird solange, bis es nicht widerlegt ist angenommen, dass g_number eine Primzahl ist
  g_is_prime = abap_true.

  "Jede Zahl die in der Tabelle gt_prim_num enthalten ist wird geprüft, ob g_number durch diese ohne Rest teilbar ist
  LOOP AT gt_prim_num ASSIGNING FIELD-SYMBOL(<g_prim>).

    "Durch Zahl1 MOD Zahl2 kann der Rest, der bei Zahl1 / Zahl2 herauskommt ermittelt werden
    "Sobald dieser bei g_number / <g_prim> 0 ist, handelt es sich bei g_number um keine Primzahl und somit muss diese nicht
    "weiter überprüft werden, folglich kann die Loop-Schleife mit EXIT verlassen werden
    IF g_number MOD <g_prim> = 0.
      g_is_prime = abap_false.
      EXIT.
    ENDIF.

  ENDLOOP.

  "Wenn nicht widerlegt werden konnte, dass g_number eine Primzahl ist, wird diese ausgegeben
  IF g_is_prime = abap_true.

    "Wenn die neu gefundene Primzahl <= g_sqrt_range, wird diese in die Tabelle gt_prim_num eingefügt (Erklärung siehe Anmerkung)
    IF g_number <= g_sqrt_range.
      INSERT g_number INTO TABLE gt_prim_num.
    ENDIF.
    WRITE g_number.
  ENDIF.

ENDDO.`

**Comment by Jos512** [comment]
> It looks like Pygments has ABAP support, so it should be fairly straightforward.

That's the one I'm using and what I'm hoping for. Without your helpful Chroma conversion tool it would be undoable since I know nothing of ABAP.

> Source code for the screenshot mentioned above as file primzahlrechner.txt

Thanks!

**Comment by Stegosawr** [comment]
If you need some abap example you can also checkout this [https://dotabap.org/](https://dotabap.org/)
and you can also check out a abap linter [here](https://github.com/abaplint/abaplint).
