### ISSUE TITLE
Build release binaries for Chroma

### ISSUE THREAD

**Issue by alecthomas** [alecthomas/chroma#28]
This would be nice to have, for those who just want to have a convenient tool they can download.

**Comment by bep** [comment]
Tip: https://github.com/goreleaser/goreleaser

**Comment by alecthomas** [comment]
Aha, nice!

**Comment by alecthomas** [comment]
Aha! Very nice.

**Comment by alecthomas** [comment]
Done. Thanks for the tip @bep!
