### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Jos512** [alecthomas/chroma#280]
I was wondering if we could get a new release sometime in the near future (~ the coming weeks), if it's not too much work.

There have been [some changes](https://github.com/alecthomas/chroma/compare/v0.6.6...master) compared with the last release to both the lexers and Chroma. It would be helpful for projects that depend on Chroma releases (e.g., Hugo).

There's a +1 and 'thumbs up' for this in the Hugo repository [here](https://github.com/gohugoio/hugo/issues/6279).

---

If you want to keep the 4 month cycle from between the main version of 0.6.5 and 0.6.3 and aim for an October release, then that's fine by me too. :slightly_smiling_face:

**Comment by alecthomas** [comment]
Done, tagged 0.6.7.

**Comment by Jos512** [comment]
Thank you! Much appreciated. :slightly_smiling_face:
