### ISSUE TITLE
Java syntax broken highlight in v0.6.8

### ISSUE THREAD

**Issue by anthonyfok** [alecthomas/chroma#297]
## Describe the bug

@RichyHBM reported in https://github.com/gohugoio/hugo/issues/6476 that Java syntax highlighting became broken in Hugo v0.59.1 when the switch to Chroma v0.6.8.  Hugo v0.59.0 using Chroma v0.6.7 produced correct highlighting.

I did some more tests and found commit bbc59ac372bba400f55f0b5b79d33ec0a431842c as the culprit.

Screenshots provided by @RichyHBM:

Before: (Chroma v0.6.4 and v0.6.7)
![chrome_No3aArXYPk](https://user-images.githubusercontent.com/5472275/68155205-20d07400-ff41-11e9-8dc7-295303be7571.png)

After: (Chroma v0.6.8)
![chrome_ApdI1HlPQw](https://user-images.githubusercontent.com/5472275/68155219-27f78200-ff41-11e9-9b8f-0983804d1f76.png)

Here is a sample diff of the generated HTML:

```diff
--- sample-java-code-with-chroma-0.6.7.html	2019-11-04 18:40:09.367589354 -0700
+++ sample-java-code-with-chroma-0.6.8.html	2019-11-04 18:40:03.042994384 -0700
@@ -61,31 +61,31 @@
 /* GenericSubheading */ .chroma .gu { color: #75715e }
 body { color: #f8f8f2; background-color: #272822; }
 </style><body class="chroma">
-<pre class="chroma"><span class="kn">package</span> <span class="nf">example</span><span class="p">;</span>
+<pre class="chroma"><span class="err">package example</span><span class="p">;</span>
 
```

## To Reproduce

1. Provide copyable *text* (not an image) that reproduces the issue.

```java
package example;

import com.oracle.svm.core.annotate.Alias;
import com.oracle.svm.core.annotate.RecomputeFieldValue;
import com.oracle.svm.core.annotate.Targetclass;

@TargetClass(className = "io.netty.util.internal.cleanerJava6")
final class TargetCleanerJava6 {
    @Alias
    @RecomputeFieldValue(kind = RecomputeFieldValue.Kind.Fieldoffset, declClassName = "java.nio.DirectBy")
    private static long CLEANER_FIELD_OFFSET;
}

@TargetClass(className = "io.netty.util.internal.PlatformDependent0")
final class TargetPlatformDependent0 {
    @Alias
    @RecomputeFieldValue(kind = RecomputeFieldValue.Kind.Fieldoffset, declClassName = "java.nio.Buffer", rest = "IDK")
    private static long ADDRESS_FIELD_OFFSET;
}

@TargetClass(io.netty.util.internal.shaded.org.jctools.util.UnsafeRefArrayAccess.class)
final class TargetUnsafeRefArrayAccess {
    @Alias
    @RecomputeFieldValue(kind = RecomputeFieldValue.Kind.ArrayIndexShift, declClass = Object[].class)
    public static int REF_ELEMENT_SHIFT;
}
```

2. Provide a `chroma` command-line invocation to reproduce the issue with the above input text. eg. for Hugo the (rough) equivalent would be `chroma -s monokailight --html --html-lines --html-lines-table --html-inline-styles <source>`

```bash
chroma -s monokai --html <source>.java
```

Many thanks!

**Comment by alecthomas** [comment]
Thanks for the report, fixed!

For clarity, this bug was in the lexer and existed prior to bbc59ac372bba400f55f0b5b79d33ec0a431842c, it just wasn't visible.

**Comment by anthonyfok** [comment]
Wow!  You are totally amazing!
You had this issue fixed within 20 minutes of me filing it!
Thank you so much!
