### ISSUE TITLE
--html-only still prepends <style> tag to output

### ISSUE THREAD

**Issue by rykov** [alecthomas/chroma#3]
When I run the following command:

    ./chroma -l Ruby --html --html-only code.rb

The output looks something like this:

```html
<style type="text/css">
... snip CSS...
</style>
<pre class="chroma">
... snip HTML...
```

Is there an option to just output the `<pre>` tag and its content, and I would generate the CSS separately with `--html-styles`?

**Comment by alecthomas** [comment]
Whoops! That is what it should be doing, let me whip up a fix.

**Comment by alecthomas** [comment]
Okay, that should be working now:

```
[aat@cavern:~/Projects/chroma]chroma --html --html-only colour.go | head -20
```

```html
<pre class="chroma">
<span class="s3e8">package</span> chroma

<span class="s3e8">import</span> (
        <span class="sc1c">&#34;fmt&#34;</span>
        <span class="sc1c">&#34;strconv&#34;</span>
        <span class="sc1c">&#34;strings&#34;</span>
)
```

**Comment by rykov** [comment]
Great!  Thank you.
