### ISSUE TITLE
HighlightLines range should be 1 based

### ISSUE THREAD

**Issue by bep** [alecthomas/chroma#30]
And not, as now, relative to the `BaseLineNumber`

Had it not been for the fact that Pygments behaves like this, this would maybe make sense, but as it is now, when we release this in Hugo, users will have to also do some conversion on their side. 

I could of course do the calculations on my side, but I think you would be better off being "Pygments compatible" where it makes sense.

**Comment by alecthomas** [comment]
Man, that sounds super confusing...

**Comment by alecthomas** [comment]
I think I'll leave the default as-is, but offer an option for using the Pygments compatible approach.

**Comment by bep** [comment]
>Man, that sounds super confusing...

To me it actually makes more sense: Highlight line 3 and 5 in **this code block**. That was my first intuitive attempt even before checking with Pygments. So I wouldn't assume the "super confusing" thing on other users before asking a set of people other than yourself.

**Comment by alecthomas** [comment]
Yes, I understand. But as long as there's a way to do both, and it is documented, I think it's fine.
