### ISSUE TITLE
html: Add bool argument to WithClasses, WithLineNumbers etc.

### ISSUE THREAD

**Issue by bep** [alecthomas/chroma#301]
This feature request springs out of my work adding some features to https://github.com/yuin/goldmark-highlighting/

That library takes:

* Chroma's `[]html.Option` as a configuration option.
* But it's also possible to configure the code blocks via attributes, e.g. `bash {linenos=true}`

There is currently no way to reconfigure a `[]html.Option` slice for the options that take no argument (`WithClasses`, `WithLineNumbers` etc). Given the below:

```go
func main() {
	var cfg config
	opts := getOptions(cfg)

	// There is no way to turn off line numbers in the option set above.
}

func getOptions(cfg config) []html.Option {
	var options []html.Option

	if cfg.lineNos {
		options = append(options, html.WithLineNumbers())
	}

	return options
}
```

What I suggest would turn the above into:

```go
func main() {
	var cfg config
	opts := getOptions(cfg)

	// Turn off line numbers
	opts = append(options, html.WithLineNumbers(false))
}

func getOptions(cfg config) []html.Option {
	var options []html.Option
	options = append(options, html.WithLineNumbers(cfg.lineNos))
	return options
}
```

Which gives 2 benefits:

1. It allows to toggle on/off features in a ` []html.Option` slice.
2. It makes for simpler mapping from config structs

There are workarounds for the above, so this isn't the most important issue in the world, but I think it would make for a much simpler to use and better API design -- and I would suggest you boldly just add these bools even if it breaks some code in the wild ...

/cc @yuin

**Comment by alecthomas** [comment]
Seems reasonable to me.

**Comment by rcoreilly** [comment]
please do push a new release soon -- definitely does break some code in the wild -- need module version updated before I can fix it so it is consistent between module & non-module users..
