### ISSUE TITLE
Add support for Raku programming language

### ISSUE THREAD

**Issue by CIAvash** [alecthomas/chroma#306]
Raku(formerly known as Perl 6) - https://raku.org/

**Comment by moorereason** [comment]
@alecthomas,
Looking at the Pygments Perl6 lexer, their custom callbacks are [accepting a context](https://github.com/pygments/pygments/blob/b45777fd2713bc3c6b80680168563afa5c96b46d/pygments/lexers/perl.py#L451), which chroma's [`EmitterFunc` doesn't contain](https://github.com/alecthomas/chroma/blob/9fb54c5f75769e5f9850376fab0fd67ad4677f33/regexp.go#L31).  It looks like their YAML and Perl6 lexers are using the context pattern.

What are your thoughts on changing the chroma API to accommodate a context?

**Comment by alecthomas** [comment]
I think it should be sufficient to just change the signature for an emitter from `Emit(groups []string, lexer Lexer) Iterator` to `Emit(groups []string, state *LexerState) Iterator`.

**Comment by moorereason** [comment]
Would you use `LexerState.MutatorState` to replicate what Pygments is doing with the context? For example:

```go
state.Set("perl6_token_nesting_level") = 1
```

**Comment by alecthomas** [comment]
Yes I think so. Possibly it could be renamed to just `Context` to reflects its new role.
