### ISSUE TITLE
Needs more indentation when `--html-lines` option is enabled

### ISSUE THREAD

**Issue by griffin-stewie** [alecthomas/chroma#31]
I think chroma needs more indentation when `--html-lines` option is enabled.

![chroma_indentation_linenumbers](https://user-images.githubusercontent.com/22316/30808398-e7809f0c-a238-11e7-8ad7-fe00f6bfb156.png)

for example, see picture above, indentation at Line:18 looks like 2 spaces but original code is 4 spaces(actually it's a tab though).

**Comment by alecthomas** [comment]
That's pretty weird. What browser is that?

**Comment by alecthomas** [comment]
Aha! Okay, interesting...this is because of how tabs work in HTML. Yes, agreed, that will need to be fixed...hmm.

**Comment by alecthomas** [comment]
Interestingly, Pygments has the exact same issue:

![image](https://user-images.githubusercontent.com/41767/30810417-6cdf20a6-a248-11e7-8f4d-aba00a80c0f6.png)

vs.

![image](https://user-images.githubusercontent.com/41767/30810435-7dee128a-a248-11e7-8054-dbab32c13f50.png)

**Comment by griffin-stewie** [comment]
@alecthomas 
Thank you for your quick reply.

I see what's going on, but I'm afraid that I'm not good at HTML & CSS. I hope it'll be fixed.

**Comment by alecthomas** [comment]
I think there are two solutions to this:

1. Explicitly expand tabs to spaces inside Chroma. This will be non-trivial, as it would have to buffer tokens and reconstruct lines.
2. Use tables for the generated HTML.

**Comment by griffin-stewie** [comment]
@alecthomas 
I think 1st idea is the best solution, because low cost to implement I guess.

**Comment by bep** [comment]
See https://github.com/alecthomas/chroma/pull/54#issuecomment-335755340

**Comment by griffin-stewie** [comment]
Thank you @bep 
Your PR would solves my issue.

**Comment by alecthomas** [comment]
I think that this can be closed given that Pygments also doesn't solve this for the non-table case.
