### ISSUE TITLE
PowerShell highlighting looks a bit broken or incomplete

### ISSUE THREAD

**Issue by exploide** [alecthomas/chroma#312]
**Describe the bug**

PowerShell highlighting looks a bit broken (perhaps in terms of incomplete).

The following screenshot shows a rendering on the playground with no colors applied, but an error indication at `C:\`.

![powershell-highlighting](https://user-images.githubusercontent.com/5670236/70344178-5971af00-1859-11ea-9327-d7dd6eb665ee.png)

**To Reproduce**

The following PowerShell line serves as an example.

```powershell
Get-ChildItem -Recurse -Force -ErrorAction SilentlyContinue -Name -Path C:\ *.txt
```

GitHub's rendering here can be seen for comparison.

**Comment by alecthomas** [comment]
![image](https://user-images.githubusercontent.com/41767/70383522-10d2f800-1924-11ea-972f-4815a5d0c91f.png)
