### ISSUE TITLE
Preprocessor directives in C/C++

### ISSUE THREAD

**Issue by srlpub** [alecthomas/chroma#313]
I use chroma from Hugo.

When I write #define or #include in C/C++, I get an extra blank line after the directives.
I use it with css style. 
 
How can I fix it?

**Comment by alecthomas** [comment]
Please follow the issue guidelines and provide a reproducible example using Chroma.

**Comment by srlpub** [comment]
Sorry.
I tried it again using chroma directly on Windows with Windows Subsystem for Linux installed. 

I found it is the matter of EOL characters.

**Describe the bug**
When I write #include or #define in C/C++, I get an extra blank line after the preprocessor directives for a file with CRLF line terminators.

**To Reproduce**
I have lf.c and crlf.c. They are same except for the EOL characters.

$ cat lf.c
#include <stdio.h>

int main() {
}
$ file lf.c crlf.c
lf.c:   C source, ASCII text
crlf.c: C source, ASCII text, with CRLF line terminators

$ chroma.exe --version
0.7.0-28dcb8565c0eca2136ca9256a240a9fe2701b553-2019-11-24T02:59:19Z
$ chroma.exe --html --html-only ./lf.c > lf.html
$ less lf.html
`<pre class="chroma"><span class="cp">#include</span> <span class="cpf">&lt;stdio.h&gt;</span><span class="cp">
</span><span class="cp"></span>
<span class="kt">int</span> <span class="nf">main</span><span class="p">()</span> <span class="p">{</span>
<span class="p">}</span>
</pre>`

$ chroma.exe --html --html-only ./crlf.c > crlf.html
$ less crlf.html
`<pre class="chroma"><span class="cp">#include</span> <span class="cpf">&lt;stdio.h&gt;^M</span><span class="cp">
</span><span class="cp"></span>
<span class="kt">int</span> <span class="nf">main</span><span class="p">()</span> <span class="p">{</span>
<span class="p">}</span></pre>`

There is an extra ^M after &gt for the crlf.c. Indeed it is one CR character not '^' and 'M'.

**Comment by alecthomas** [comment]
This seems to be only at the end of the file, is that correct?

**Comment by srlpub** [comment]
> This seems to be only at the end of the file, is that correct?

No.

This happens when I feed a file with CR(0x0d) + LF(0x0a) at the end of each LINE, which is Windows standard, for example, notepad.exe produces.

The file 
+++
#include <stdio.h> <- no extra newline here
#define A b <- no extra newline here

int main() {
}
+++

would become

+++
#include <stdio.h>
                        <- extra newline here
#define A b
                        <- extra newline here

int main() {       <- no extra newline here
}                       <- no extra newline here
+++

I am not sure I understand your question correctly.
If my answer dose not make sense, please let me know.

**Comment by sovietspaceship** [comment]
Having the same issue.

```c
#define A b
```

in C gives

```html
<span class="p">#</p>
<span class="p">define A b
</span>
<span class="p">
</p>
```

empty lines are added, and also empty span at the end (of the block, not the entire file), which adds an empty line and messes up line numbers. This happens anywhere in the file.

**Comment by alecthomas** [comment]
I think this is fixed:

```
~/Projects/chroma $ hexdump -c t.c
0000000   #   d   e   f   i   n   e       A       b  \r  \n            
000000d
~/Projects/chroma $ chroma --html --html-only t.c
<pre class="chroma"><span class="cp">#define A b
</span></pre>%                                                                                                                                                     

```
