### ISSUE TITLE
Updating ebnf syntax to match linguists?

### ISSUE THREAD

**Issue by jpienaar** [alecthomas/chroma#314]
**What problem does this feature solve?**

Currently the syntax for EBNF in chroma differs from what GitHub linguist supports, this is to find out feasibility of getting these to match closer. This would allow using the same file, highlighted similarly when served from GitHub or Hugo.

**What feature do you propose?**

Update the EBNF grammer to match what GitHub does (https://github.com/Alhadis/language-grammars).

I'm not sure how many folks depends on the current EBNF grammar here.

**Comment by alecthomas** [comment]
There are many many EBNF grammars, what makes this one better?

**Comment by alecthomas** [comment]
In fact, can you illustrate what exactly the differences are?

**Comment by alecthomas** [comment]
@jpienaar ping

**Comment by jpienaar** [comment]
Oops, and I was logged into the wrong account. Which would explain why I didn't get the notification either.

**Comment by alecthomas** [comment]
No worries!
