### ISSUE TITLE
Include C# highlight

### ISSUE THREAD

**Issue by Jos512** [alecthomas/chroma#32]
I plan to use Chroma with Hugo, which added Chrome in [v0.28](https://github.com/gohugoio/hugo/releases/tag/v0.28). But I'd need C# highlight for that. I don't see that language currently in the `lexers` folder of the repository. Could that language be added? Thanks.

---

By the way, given how busy you've been with this project I'm fine with making this a low-priority request if you decide to add it. (I'm not in a hurry.)

Thanks for your work!

**Comment by alecthomas** [comment]
Thanks @steambap !
