### ISSUE TITLE
Backslashes are wrapped in <span>

### ISSUE THREAD

**Issue by eine** [alecthomas/chroma#322]
With hugo and docuapi, using backslashes in a code block with a `sh` command, produces coloured symbols that are wrapped in `<span>`. As a result, additional space is shown. For example:
 
```shell
docker run --rm \
  -v //var/run/docker.sock://var/run/docker.sock \
  -v issues://volume \
  eine/issue-runner <ref>
```

![docuapi_backslash](https://user-images.githubusercontent.com/6628437/71944289-a1bb1e80-31c3-11ea-84de-2a1b5723f78c.png)

I could not reproduce it with the CLI tool (note that `test.md` contains the code block above):

```
root@0b219af479d8:~# go get -u github.com/alecthomas/chroma/cmd/chroma
root@0b219af479d8:~# chroma -s monokailight --html --html-lines --html-lines-table --html-inline-styles test.md 
<html>
<body style="color:#272822;background-color:#fafafa">
<div style="color:#272822;background-color:#fafafa">
<table style="border-spacing:0;padding:0;margin:0;border:0;width:auto;overflow:auto;display:block;"><tr><td style="vertical-align:top;padding:0;margin:0;border:0;">
<pre style="color:#272822;background-color:#fafafa"><span style="margin-right:0.4em;padding:0 0.4em 0 0.4em;color:#7f7f7f">1
</span><span style="margin-right:0.4em;padding:0 0.4em 0 0.4em;color:#7f7f7f">2
</span><span style="margin-right:0.4em;padding:0 0.4em 0 0.4em;color:#7f7f7f">3
</span><span style="margin-right:0.4em;padding:0 0.4em 0 0.4em;color:#7f7f7f">4
</span></pre></td>
<td style="vertical-align:top;padding:0;margin:0;border:0;;width:100%">
<pre style="color:#272822;background-color:#fafafa">docker run --rm \
  -v //var/run/docker.sock://var/run/docker.sock \
  -v issues://volume \
  eine/issue-runner &lt;ref&gt;</pre></td></tr></table>
</div>

</body>
</html>
```

However, the issue is found at https://swapoff.org/chroma/playground/. Just copy&paste the snippet and show the HTML output:

```html
<body class="chroma">
<pre class="chroma">docker run --rm <span class="se">\
</span><span class="se"></span> -v //var/run/docker.sock://var/run/docker.sock <span class="se">\
</span><span class="se"></span> -v issues://volume <span class="se">\
</span><span class="se"></span> eine/issue-runner &lt;ref&gt;</pre>
</body>
```

Ref bep/docuapi#47

**Comment by alecthomas** [comment]
I can't reproduce this on the playground. In fact, your HTML looks okay too, there are no extra linebreaks. It could be that it was a bug in a previous version of Chroma that has subsequently been fixed.

![image](https://user-images.githubusercontent.com/41767/72025828-76bcf180-32cd-11ea-8017-07aa4708eb55.png)


What language are you using?

**Comment by alecthomas** [comment]
FYI the bug there isn't that the backslashes are wrapped in `span` (that's intentional), it's that an extra linebreak is being added after them.

**Comment by eine** [comment]
> I can't reproduce this on the playground. In fact, your HTML looks okay too; there are no extra linebreaks. It could be that it was a bug in a previous version of Chroma that has subsequently been fixed.

My HTML output (last code block in the message above) shows the following pattern three times:

```html
>\
</span><span
```

Instead, it should be as follows:

```html
>\</span>
<span
```

or

```html
>\<!--
--></span><span
```

Overall, there should be a single symbol/character between `>` and `</`.

I tested it by using the 'inspect' feature of the browser and editing the HTML. I left the one in the middle unmodified, to better show the difference:

![chroma_span](https://user-images.githubusercontent.com/6628437/72033753-7f90d180-3293-11ea-88ae-f90d3a030a55.png)

> What language are you using?

I'm using `sh` or `bash` in hugo/docuapi, and `Bash` in the playground.

> FYI the bug there isn't that the backslashes are wrapped in `span` (that's intentional), it's that an extra linebreak is being added after them.

You are correct. Thanks for clarifying.

**Comment by alecthomas** [comment]
The fact that there's an empty span, or a span with `\\\n` shouldn't cause an extra newline though, correct? What problem is it causing?

**Comment by eine** [comment]
That's what I am trying to understand. As you say, the visualization in the playground ignores those additional characters and no extra newline is shown. I don't understand why the visualization in the hugo site is different... Does the code in the playground do any "sanitization"?

**Comment by eine** [comment]
Oh. I think I got it now. This is the playground:

```html
<pre style="color:#272822;background-color:#fafafa">docker run --rm <span style="color:#8045ff">\
</span><span style="color:#8045ff"></span>  -v //var/run/docker.sock://var/run/docker.sock <span style="color:#8045ff">\
</span><span style="color:#8045ff"></span>  -v issues://volume <span style="color:#8045ff">\
</span><span style="color:#8045ff"></span>  eine/issue-runner &lt;ref&gt;</pre>
```

This is hugo:

```html
<code class="language-bash" data-lang="bash">docker run --rm <span style="color:#ae81ff">\
</span>
  -v //var/run/docker.sock://var/run/docker.sock <span style="color:#ae81ff">\
</span>
  -v issues://volume <span style="color:#ae81ff">\
</span>
  eine/issue-runner &lt;ref&gt;
</code>
```

Hence, the problem is inmediately after the span that wraps the backslash. In the playground, each line starting with white characters is "safe" because it is prepended with an empty span. Those empty spans do not exist in hugo.

**Comment by alecthomas** [comment]
Yeah as I said, I think it might be a bug with the version of Chroma that Hugo is currently on. I've tagged 0.7.1, which you could try with Hugo if you are confident enough with Go.

**Comment by eine** [comment]
I tried cloning hugo, editing go.mod to bump chroma, `go get ./...` and go build. I'd say the the resulting binary is using the newer version of chroma, because I see a colour difference:

```
<code class="language-sh" data-lang="sh">docker run --rm -it <span style="color:#ae81ff">\
</span>
  -v /<span style="color:#66d9ef">$(</span>pwd<span style="color:#66d9ef">)</span>://src <span style="color:#ae81ff">\
</span>
  -w //src <span style="color:#ae81ff">\
</span>
  -v //var/run/docker.sock://var/run/docker.sock <span style="color:#ae81ff">\
</span>
  -v issues://volume <span style="color:#ae81ff">\
</span>
  golang bash
</code>
```

As you see, `$( )` are now coloured. Unfortunately, the issue with extra linebreaks persists...
