### ISSUE TITLE
Status of go.rice fork, is it still needed?

### ISSUE THREAD

**Issue by eclipseo** [alecthomas/chroma#328]
Is:

```
replace github.com/GeertJohan/go.rice => github.com/alecthomas/go.rice v1.0.1-0.20190719113735-961b99d742e7
```

still needed? It seems the changes in the fork were upstreamed a while ago and that GeertJohan continued development. I'd like to keep forking to a minimum in my packaging in order to keep getting security updates if any.

Best regards,

**Comment by alecthomas** [comment]
I think he merged my change, so nope!

**Comment by anthonyfok** [comment]
Thank you to you both, Robert-André and Alec!  I was wondering about the same question (re: Debian packaging), and I'm glad that you reached the same conclusion.

I went ahead and remove the `replace` directive from go.mod in PR #333 
Cheers!

**Comment by alecthomas** [comment]
Thanks!
