### ISSUE TITLE
Windows-style line endings break rendering

### ISSUE THREAD

**Issue by muesli** [alecthomas/chroma#329]
Windows-style line endings `\r\n` break chroma's syntax highlighting. I've seen it break in different ways, but most commonly it will then render everything as spaces instead of text.

Providing a copyable text is difficult, as the GitHub interface would cleanup the line endings. GitHub also doesn't let me attach such a file to this issue.

Replacing `\r\n` and `\r` with `\n` before passing the source to chroma works around the problem.

**Comment by chmike** [comment]
I confirm the problem. 

Text obtain from a textarea html form has its lines terminated by \r\n. A filtering is required to replace \r\n with \n.

**Comment by alecthomas** [comment]
Can someone try https://github.com/alecthomas/chroma/pull/336? Given there's no data to verify that this fixes the issue, I'd prefer someone to verify it before merging.

**Comment by muesli** [comment]
@alecthomas This is pretty much the workaround I use locally, at the moment. I'm actually wondering if it needs to be a separate option or if this isn't a sanitizer we always want to run?

**Comment by satotake** [comment]
I am wondering, too. @muesli 

Theoretically, there can be lexers which do not handle `\n` as EOL and accept only `\r` or `\r\n`. 
I had suspected some windows-driven files might be so.
Fortunately, it was not the case of the lexers which chorma are using.
At least, they are so rare.

**Comment by alecthomas** [comment]
Fix merged please verify.

**Comment by muesli** [comment]
@alecthomas Verified as fixed. Thanks everyone!
