### ISSUE TITLE
Caddyfile syntax highlighting

### ISSUE THREAD

**Issue by francislavoie** [alecthomas/chroma#338]
[Caddy](https://caddyserver.com/) supports [markdown rendering](https://caddyserver.com/docs/json/apps/http/servers/errors/routes/handle/templates/#markdown) via [Blackfriday](https://github.com/russross/blackfriday), which uses Chroma for syntax highlighting.

I think it would be awesome if Chroma would support a `caddyfile` lexer so that we can syntax highlight all the examples in the Caddy documentation! It would also mean that the Caddy could syntax highlight its own configuration!

[See here](https://caddyserver.com/docs/caddyfile/concepts#structure) for information on the syntax. It's quite simple.

Caddy v1 and Caddy v2 have slightly different syntax, but @Mohammed90 found this [VS Code syntax for v1](https://github.com/Zamerick/vscode-caddyfile-syntax/blob/master/syntaxes/caddyfile.tmLanguage.json) which could be useful as a base reference?

Thanks!

**Comment by alecthomas** [comment]
The linked syntax is a Textmate grammar, so I think a more flexible solution is to add an importer for those.

**Comment by alecthomas** [comment]
I actually played around with this a bit today and had some success, but unfortunately that Textmate syntax is really quite bad. I think Textmate support in general is a good idea, but for this particular syntax it's probably better just to write one from scratch.

**Comment by francislavoie** [comment]
Thanks for looking into it! Let me know if you have any questions regarding the syntax.

**Comment by mholt** [comment]
It shouldn't be _too_ hard to write a new one from scratch; the Caddyfile is relatively simple, but there might be a few edge cases that take some time to work out (and that's OK for later too).
