### ISSUE TITLE
Chroma can't determine correct lexer for a simple YAML/JSON output

### ISSUE THREAD

**Issue by mic4ael** [alecthomas/chroma#341]
**Describe the bug**

While trying to colorize output from `kubectl` I noticed that `chroma` can't properly autodetect the correct lexer for a simple `JSON` or `YAML` output (provided that the output is redirected to a file without extension).

**To Reproduce**

```console
$ echo "api: 3\napiVersion: 4" > test_file
$ chroma --trace --json test_file
root: pos=0, text="api: 3\napiVersion: 4\n"
root: pos=6, text="\napiVersion: 4\n"
root: pos=7, text="apiVersion: 4\n"
root: pos=20, text="\n"
[
  {"type":"Text","value":"api: 3\napiVersion: 4\n"}
]

$ cp test_file{,.yml}
$ chroma --trace --json test_file.yml
root: pos=0, text="api: 3\napiVersion: 4\n"
root: pos=5, text="3\napiVersion: 4\n"
root: pos=6, text="\napiVersion: 4\n"
root: pos=7, text="apiVersion: 4\n"
root: pos=19, text="4\n"
root: pos=20, text="\n"
[
  {"type":"Keyword","value":"api"},
  {"type":"Punctuation","value":":"},
  {"type":"TextWhitespace","value":" "},
  {"type":"LiteralNumber","value":"3"},
  {"type":"TextWhitespace","value":"\n"},
  {"type":"Keyword","value":"apiVersion"},
  {"type":"Punctuation","value":":"},
  {"type":"TextWhitespace","value":" "},
  {"type":"LiteralNumber","value":"4"},
  {"type":"TextWhitespace","value":"\n"}
]
```

It doesn't seem to work for those filetypes, however correct autodection works for `Go` files.

**Comment by alecthomas** [comment]
Yes, this is [documented](https://github.com/alecthomas/chroma#whats-missing-compared-to-pygments) in the README. I had plans to implement a statistical language detector, but haven't had the time to implement it.

**Comment by mic4ael** [comment]
Ahh, ok, I see - I missed that part of the README

**Comment by mic4ael** [comment]
Hey @alecthomas, just a small suggestion. Maybe this part of the README should be a bit more visible (some info section on top)? To prevent issues like this one in the future :)
