### ISSUE TITLE
FR: prompt highlighting

### ISSUE THREAD

**Issue by prosoitos** [alecthomas/chroma#343]
**What problem does this feature solve?**

Not a problem, but a great improvement in code readability, in aesthetics, and mostly in making code blocks of different languages obviously different at a glance.

**What feature do you propose?**

I build a lot of workshops using Hugo and I always thought that it would be neat if the prompts in various languages were highlighted.

Now, I am getting into Julia and this old wish got greatly reinforced.

For instance:

I am building workshops which involve code blocks in Julia and code blocks in the terminal.

People get confused as to what runs where. I would love to be able to customize the background of my chroma theme based on the language used as this would be the cleanest solution to make blocks of different languages visually very distinct. This may be possible, but I don't know how to do it (I would greatly appreciate any hint on this actually!! and if it is not possible, that is another feature request I would love to suggest).

As an alternative to making the code blocks obviously distinct, I decided to add the prompts. It is not ideal as users cannot simply copy and paste the code to run it: they have to first edit the prompts out. But it does the job.

Adding `julia>` at the start of every line of code however makes it heavy, hard to read, looking cluttered, and not all that great.

So I thought that it would be great if the shell prompt (`$`), when used in shell blocks, would be highlighted in one color and appear bold, while `julia>` in julia blocks would appear in light green (as it does in a Julia REPL) or in light blue as the Julia [Documenter package](https://github.com/JuliaDocs/Documenter.jl) allows to do.

See for instance: https://fluxml.ai/Flux.jl/stable/models/basics/

![2020-03-10_13:27:10](https://user-images.githubusercontent.com/4634851/76356447-34b32a80-62d3-11ea-80c0-b7201df570b9.png)

This looks really cool and makes the code block really easy to read.

It certainly looks a lot nicer than what I managed to do with Hugo using a chroma theme, for instance here https://westgrid-julia.netlify.com/workshops/intro.html.

To avoid the cluttering/hard to read effect of having all these `julia>` in black, I used `>` instead. But the distinction between the terminal blocks which start with an equally black `$` is not striking at a glance.

**Comment by alecthomas** [comment]
While this would be nice, every language has its own prompt format, so there would basically need to be lexers for each distinct language. It's not a problem that can be solved wholesale.

That said if someone wants to implement a Julia "console" lexer, I'd happily accept it.
