### ISSUE TITLE
Custom styles

### ISSUE THREAD

**Issue by AbeEstrada** [alecthomas/chroma#35]
What is the proper way to add a custom style?

I want to use [Dracula](https://draculatheme.com/), I generated the [`dracula.go`](https://gist.github.com/AbeEstrada/e16e4d22d9adec4e720fd62a16a0113d) file.

**Comment by alecthomas** [comment]
I need to document this, but there are basically two ways:

1. Generate the new scheme and send me a PR.
2. Use the Pygments .css file from that style (this will only work after bdc1124369132ffa0e5edf345612995893ee4f9a).

Please send a PR!

**Comment by AbeEstrada** [comment]
I sent #36 to add the style

**Comment by alecthomas** [comment]
Thanks!
