### ISSUE TITLE
yaml parsing improvements

### ISSUE THREAD

**Issue by yaythomas** [alecthomas/chroma#360]
Thanks @alecthomas for a great project! To follow a list of some issues for the more obvious/common yaml bumps. Rather than just complain about yaml parsing (nightmare that yaml via regex is!) I forked and fixed all of these, so if TLDR; skip to the end where there's a link to my fork and the changes might be more obvious in code than in more wordy description.

Consider the following yaml, `simple.yaml`:
```yaml
k1: value1
k2: 'value2'
k3: value 4
k4: str w can't cope with single quote
k5: value 4
k6: another ' sq
k7: True
k8: false
k9: 'single quotes'
"k10": "double quotes"
k11: Punctuation at end.
k12: more punc at !
k13: punc ? in middle
k14: end
```

pygments parses as follows:
`pygmentize -f html -l yaml simple.yaml`
```html
<div class="highlight"><pre><span></span><span class="nt">k1</span><span class="p">:</span> <span class="l l-Scalar l-Scalar-Plain">value1</span>
<span class="nt">k2</span><span class="p">:</span> <span class="s">&#39;value2&#39;</span>
<span class="nt">k3</span><span class="p">:</span> <span class="l l-Scalar l-Scalar-Plain">value 4</span>
<span class="nt">k4</span><span class="p">:</span> <span class="l l-Scalar l-Scalar-Plain">str w can&#39;t cope with single quote</span>
<span class="nt">k5</span><span class="p">:</span> <span class="l l-Scalar l-Scalar-Plain">value 4</span>
<span class="nt">k6</span><span class="p">:</span> <span class="l l-Scalar l-Scalar-Plain">another &#39; sq</span>
<span class="nt">k7</span><span class="p">:</span> <span class="l l-Scalar l-Scalar-Plain">True</span>
<span class="nt">k8</span><span class="p">:</span> <span class="l l-Scalar l-Scalar-Plain">false</span>
<span class="nt">k9</span><span class="p">:</span> <span class="s">&#39;single</span><span class="nv"> </span><span class="s">quotes&#39;</span>
<span class="s">&quot;k10&quot;</span><span class="p p-Indicator">:</span> <span class="s">&quot;double</span><span class="nv"> </span><span class="s">quotes&quot;</span>
<span class="nt">k11</span><span class="p">:</span> <span class="l l-Scalar l-Scalar-Plain">Punctuation at end.</span>
<span class="nt">k12</span><span class="p">:</span> <span class="l l-Scalar l-Scalar-Plain">more punc at !</span>
<span class="nt">k13</span><span class="p">:</span> <span class="l l-Scalar l-Scalar-Plain">punc ? in middle</span>
<span class="nt">k14</span><span class="p">:</span> <span class="l l-Scalar l-Scalar-Plain">end</span>
```

chroma parses as follows:
`go run cmd/chroma/main.go --lexer=yaml --formatter=tokens simple.yaml`

```
&Token{Keyword, "k1"}
&Token{Punctuation, ":"}
&Token{TextWhitespace, " "}
&Token{Text, "value1"}
&Token{TextWhitespace, "\n"}
&Token{Keyword, "k2"}
&Token{Punctuation, ":"}
&Token{TextWhitespace, " "}
&Token{LiteralStringSingle, "'value2'"}
&Token{TextWhitespace, "\n"}
&Token{Keyword, "k3"}
&Token{Punctuation, ":"}
&Token{TextWhitespace, " "}
&Token{Text, "value"}
&Token{TextWhitespace, " "}
&Token{LiteralNumber, "4"}
&Token{TextWhitespace, "\n"}
&Token{Keyword, "k4"}
&Token{Punctuation, ":"}
&Token{TextWhitespace, " "}
&Token{Text, "str"}
&Token{TextWhitespace, " "}
&Token{Text, "w"}
&Token{TextWhitespace, " "}
&Token{Text, "can"}
&Token{LiteralStringSingle, "'t cope with single quote\nk5: value 4\nk6: another '"}
&Token{TextWhitespace, " "}
&Token{Text, "sq"}
&Token{TextWhitespace, "\n"}
&Token{Keyword, "k7"}
&Token{Punctuation, ":"}
&Token{TextWhitespace, " "}
&Token{Text, "True"}
&Token{TextWhitespace, "\n"}
&Token{Keyword, "k8"}
&Token{Punctuation, ":"}
&Token{TextWhitespace, " "}
&Token{KeywordConstant, "false"}
&Token{TextWhitespace, "\n"}
&Token{Keyword, "k9"}
&Token{Punctuation, ":"}
&Token{TextWhitespace, " "}
&Token{LiteralStringSingle, "'single quotes'"}
&Token{TextWhitespace, "\n"}
&Token{Keyword, "\"k10\": "}
&Token{LiteralStringDouble, "\"double quotes\""}
&Token{TextWhitespace, "\n"}
&Token{Keyword, "k11"}
&Token{Punctuation, ":"}
&Token{TextWhitespace, " "}
&Token{Text, "Punctuation"}
&Token{TextWhitespace, " "}
&Token{Text, "at"}
&Token{TextWhitespace, " "}
&Token{Text, "end."}
&Token{TextWhitespace, "\n"}
&Token{Keyword, "k12"}
&Token{Punctuation, ":"}
&Token{TextWhitespace, " "}
&Token{Text, "more"}
&Token{TextWhitespace, " "}
&Token{Text, "punc"}
&Token{TextWhitespace, " "}
&Token{Text, "at"}
&Token{TextWhitespace, " "}
&Token{Text, "!"}
&Token{TextWhitespace, "\n"}
&Token{Keyword, "k13"}
&Token{Punctuation, ":"}
&Token{TextWhitespace, " "}
&Token{Text, "punc"}
&Token{TextWhitespace, " "}
&Token{Punctuation, "?"}
&Token{TextWhitespace, " "}
&Token{Text, "in"}
&Token{TextWhitespace, " "}
&Token{Text, "middle"}
&Token{TextWhitespace, "\n"}
&Token{Keyword, "k14"}
&Token{Punctuation, ":"}
&Token{TextWhitespace, " "}
&Token{Text, "end"}
&Token{TextWhitespace, "\n"}
```

Issues:

1. yaml key parsed as `Keyword` rather than `NameTag`.
2. `---` and `...` parsed as `Text`, rather than `NameNamespace` (e.g in _lexers/testdata/yaml.actual_)
3. Doesn't recognise all possible yaml bool values as `KeywordConstant` (https://yaml.org/type/bool.html)

```
y|Y|yes|Yes|YES|n|N|no|No|NO
|true|True|TRUE|false|False|FALSE
|on|On|ON|off|Off|OFF
```
4. yaml plain flow scalars parsed as `Text` rather than `Literal`. When explicitly wrapped in single/double quotes correctly parses to LiteralString.
5. yaml value literal parses per word, rather than the full line. Other than bloating output unnecessarily, this also has additional/unintentional side effects:
  5.1. accidental highlighting of known types like date/number/bool in a literal (check `k3` above)
  5.2. A single quote in a plain flow scalar that is not explicitly string will incorrectly highlight a string across multiple keys (check `k4`- `k6`)
  5.3. Sequences like this (from _lexers/testdata/yaml.actual_)
```
a_sequence:
  - Item 1
  - Item 2
```
parses like this (literal value breaks over word, sequence separator becomes part of text):
```
{"type":"NameTag","value":"a_sequence"},
  {"type":"Punctuation","value":":"},
  {"type":"TextWhitespace","value":"\n  "},
  {"type":"Text","value":"- Item"},
  {"type":"TextWhitespace","value":" "},
  {"type":"LiteralNumber","value":"1"},
  {"type":"TextWhitespace","value":"\n  "},
```

6. multi-line value (with > or | chomping indicators) parses 1st line as `StringDoc`, then subsequent lines per word as `Text`

Although 1-3 are minor, they do mean that pygments stylesheets have some surprising formatting when used with chroma - so if the idea is that chroma should be a seamless drop-in for pygments derived stylesheets. . . These are also pretty trivial fixes and potential side-effects limited.

4-6 has more potential for unintended side-effects. I propose changing the current
``{`\b[\w]+\b`, Text, nil}`` to parse plain flow scalar literals more exactly, but this
probably deserves some extra thought by someone better acquainted with all the subtleties
of parsing rules in chroma than I because it can have some unintended side-effects.

I've forked and made the changes to address all of the above, see here https://github.com/alecthomas/chroma/compare/master...yaythomas:yamlfix?expand=1

I also added some test cases to the `yaml.actual` sample. For review the areas most deserving of a close eye are probably ln 26 and ln 40, parsing for multiline scalar and literal, respectively:
- ``{`[>|](?:[+-])?\s(?:^(?:[ \n]{1})+.*\n?)*$`, StringDoc, nil}``
- ``{`[^\{\}\[\]\?,\:\!\-\*&\@].*`, Literal, nil}``

If you're happy with the approach and nothing horrifying leaps out at you by way of sanity check, I can happily PR this in? I made each change in its own commit if anything does not meet with your approval.

**Comment by alecthomas** [comment]
I don't think anyone using Chroma's YAML highlighting will be complaining about backwards compatibility, so PR away :)
