### ISSUE TITLE
Missing elements in Go Template lexer

### ISSUE THREAD

**Issue by malcom** [alecthomas/chroma#387]
Seems that the `Go Template` lexer do not support all "features" like assigned operator and multi-line comments. These elements in the rendered output are ignored and/or marked as a syntax error.

Code:
```
{{/* a comment */}}

{{/* a multi-line
comment
*/}}

{{ $variable := 1 }}
{{ $variable = 2 }}
```
Output:
![image](https://user-images.githubusercontent.com/124141/89227350-ce120e80-d5dd-11ea-819b-57cf018a6fde.png)

**Comment by cmaster11** [comment]
Addressed in <https://github.com/alecthomas/chroma/pull/401> :)

**Comment by alecthomas** [comment]
Champion, thanks!
