### ISSUE TITLE
YAML multiline strings issues

### ISSUE THREAD

**Issue by silverwind** [alecthomas/chroma#391]
**Describe the bug**

YAML multiline strings have some highlighting issues.

**To Reproduce**

Put this in the playground and set syntax to YAML.

```` yaml
parent:
  a: |
    multiline literal
    line 2
  b: >
    multiline folded
    line 2
  c: |-
    multiline literal strip
    line 2
  d: >-
    multiline folded strip
    line 2
  e: |+
    multiline literal keep
    line 2
  f: >+
    multiline folded keep
    line 2
````

Renders like this:

<img width="347" alt="image" src="https://user-images.githubusercontent.com/115237/90618486-5e706600-e210-11ea-9ca8-01979e5713df.png">

Issues:

- "line 2" should be highlighted as string
- double-character specifiers like `|+` should use the same tokens (not string)

See https://yaml-multiline.info/ for more info on this.

**Comment by alecthomas** [comment]
Yep, YAML is terrible. There have been several issues [in the past](https://github.com/alecthomas/chroma/issues?q=is%3Aissue+yaml+). Contributions are welcome.

**Comment by silverwind** [comment]
Is it possible that the playground has not been updated to 0.8.0 yet? We do observe different rendering than the playground shows in https://github.com/go-gitea/gitea/issues/12532 and are wondering where it's coming from.

**Comment by alecthomas** [comment]
Yes the playground is a bit behind. I've updated it, and not it is incorrect in an entirely different way! Progress!

**Comment by silverwind** [comment]
Yay, now it it matches GitHub's rendering which is also broken 😉

**Comment by yaythomas** [comment]
Linked PR resolves this specific issue, and added some specific tests for the breaking example as given above so it doesn't regress on future updates, and rest assured future fixes will happen, because I can't imagine this is the last word on the wondrous world of yaml regexing! 🤯 

(This is a polite way of saying the yaml-ing is bit better as a result but deffo not perfect. Progress!)
