### ISSUE TITLE
Suggestion: a better lexer result visualiser, made for humans

### ISSUE THREAD

**Issue by pedroql** [alecthomas/chroma#393]
Hi,

I recently worked on some improvements in one of the lexers and noticed how difficult it was to mentally parse the  `*.expected` file to see if the lexer is producing the correct output. It is also difficult to look at a diff and make sure we changed everything we wanted to change and nothing else.

So I built a tool to help me visualise it. It basically parses the same `*.expected` file and produces a more visual representation of the different tokens applied to each part of the text. In my opinion, it is better both at visualising the results of the lexer and running a diff to compare differences to the previous version.

It turns this (excerpt) 

```json
[
  {"type":"Keyword","value":"package"},
  {"type":"Text","value":" "},
  {"type":"NameNamespace","value":"X"},
  {"type":"Text","value":"\n\n"},
  {"type":"Keyword","value":"import"},
  {"type":"Text","value":" "},
  {"type":"NameNamespace","value":"A"},
  {"type":"Text","value":"\n"},
  {"type":"Keyword","value":"import"},
  {"type":"Text","value":" "},
  {"type":"NameNamespace","value":"B.*"},
```

Into this (option 1)

```
Keyword          > package
Text             >         
NameNamespace    >         X
Text             >          
                 | 
                 | 
Keyword          > import
Text             >        
NameNamespace    >        A
Text             >         
                 | 
Keyword          > import
Text             >        
NameNamespace    >        B.*
```

Or this (option 2)

```
package		 <- Keyword
package 		 <- Text
package X		 <- NameNamespace
package X

		 <- (2 lines until here) Text
import		 <- Keyword
import 		 <- Text
import A		 <- NameNamespace
import A
		 <- (1 lines until here) Text
import		 <- Keyword
import 		 <- Text
import B.*		 <- NameNamespace
```

Right now I'm split between the two output styles, but I use more the second one.

You can compare the three files in [this gist](https://gist.github.com/pedroql/63838d675f64cc6cb5c63b9d4bcf1d80)

And you can check the source here: https://github.com/pedroql/chroma/commit/1314fd09f9242257dce3c85f4a1533242fd97875 PS: I'm not a Go developer so I probably wrote overly complicated code and broke some conventions. I'm not even sure if `visualiser.go` is in a reasonable folder!

I suggest you include this tool or something similar in this project. (I can create a PR with that commit). 

The way I imagined this being employed, you could run this visualiser against all `*.expected` files in the project and put the result in git. Then integrate it with the tests (when you run the tests, you also update the visualised file). Next time someone makes a changes to a lexer, it will be much easier to inspect what changes were done as the normal diff tools applied to this visualised file are a lot more readable that the way we do it now. 

I can also do this step of running the visualiser against all current lexer results and integrating with the tests.

**Comment by pedroql** [comment]
With `chroma --html` you can use the browser to check if it *looks* correct, but it's hard to make sure what class each token has. I see some advantages and disadvantages to this:

* You can open up your browser and just look at the final result
  *  arguably more important than having each token classified correctly (if it looks the same, it doesn't matter it's not what you thought it should be).
  * on the other hand, what looks correct under a theme might look wrong using a different theme. 
  * some themes might render some classes exactly the same, so you can never tell between them
* By looking at the rendered html, you need to trust your eyes to spot differences (is this italic? bold? etc). So you might miss things or you might believe one element has a different styling than another but it might just be an illusion.

But this is the main reason I suggest this:

* calling `chroma --html` is not integrated into the code review process. If I tweak a lexer and submit a PR, there is no easy way to see how my changes affect the outputs created by the lexers. Even for me who made changes, I would like to know these things before I create the PR. Yes, we can checkout the PR branch and run that command but I *think* it would be nicer to have a diff that you can look from github/ `git diff` and have a reasonable way to see what changed.

**Comment by alecthomas** [comment]
I appreciate failing an issue, and the PR, but I think the JSON format is fine for my purposes.
