### ISSUE TITLE
<pre> tag is not being closed for HTML generation

### ISSUE THREAD

**Issue by rykov** [alecthomas/chroma#4]
When I run either of the following commands:

    ./chroma -l Ruby --html code.rb
    ./chroma -l Ruby --html --html-only code.rb

The output opens the `<pre>` tag, but there is no corresponding `</pre>`.

**Comment by alecthomas** [comment]
This should be fixed now!

**Comment by alecthomas** [comment]
```
[aat@cavern:~/Projects/chroma]chroma --html --html-only colour.go | grep '\<pre\>'
<pre class="chroma">
</pre>
```

**Comment by alecthomas** [comment]
Thanks for reporting.

**Comment by rykov** [comment]
Quick response.  Thank you.
