### ISSUE TITLE
Add support for Org-mode syntax

### ISSUE THREAD

**Issue by kaushalmodi** [alecthomas/chroma#40]
Thank you for adding the systemverilog lexer and I also noticed the Nimrod -> Nim conversion. So now Chroma works at least to the level Pygments worked for me.

Chroma can level up more if Org-mode syntax can be added too!

AFAIK, Pygments still doesn't support that: https://bitbucket.org/birkenfeld/pygments-main/issues/719/wishlist-support-org

I don't know Go, but I might give a try creating a lexer for Org by copying the template from other lexers.

**Comment by alecthomas** [comment]
That would be excellent. I recently implemented the [YAML lexer](https://github.com/alecthomas/chroma/blob/master/lexers/yaml.go), which is quite simple and could be used as an example.
