### ISSUE TITLE
Add Timeout to Highlight 

### ISSUE THREAD

**Issue by boyter** [alecthomas/chroma#410]
**What problem does this feature solve?**

On occasion choma can be passed input that spends hours processing. This is due to backtracking in the regular expression engine that is being used. It's hard to know ahead of time which inputs will cause this, and can result in long lived processes chewing up CPU. Having the ability to set a hard timeout on how long it should spend highlighting would be very useful in controlling this for long lived processes.

See the attached profile (named .txt to allow its upload) as an example where this occurs

```
go tool pprof -http=localhost:8090 profile.txt
```

![Screen Shot 2020-10-20 at 11 26 38 am](https://user-images.githubusercontent.com/612151/96525614-21375b80-12c7-11eb-864f-1761a564e5c1.png)

[profile.txt](https://github.com/alecthomas/chroma/files/5405536/profile.txt)

Examples of input that can cause this include the following, but they are not the only ones I have observed.

https://searchcode.com/codesearch/raw/91342914/
https://searchcode.com/codesearch/raw/146574592/

**What feature do you propose?**

Having the ability to specify a hard timeout via a time.Duration would resolve the above. It's one of the tricky things about backtracking. I suspect its needed to use the Pygments highlight matchers.

It seems doable as https://github.com/dlclark/regexp2 does support a timeout thankfully using `re.MatchTimeout`.

**Comment by alecthomas** [comment]
This was [added in July](https://github.com/alecthomas/chroma/commit/e62d93f4aabfa3f0140c0863d2f33c9b94719b7e). What version are you on?

**Comment by boyter** [comment]
Ah, a much older one apparently. v0.7.1 Ill update now.

I tend to not update them that often. Any plans to expose that as something controllable? I don't mind waiting a few seconds most of the time.

**Comment by alecthomas** [comment]
Not at the moment, but remember this timeout is _per token_ not for the document as a whole, so if your timeout is seconds and each token hits pathological backtracking it could still take hours.

All the best!
