### ISSUE TITLE
JavaScript String.raw

### ISSUE THREAD

**Issue by nu8** [alecthomas/chroma#414]
This valid JavaScript code:

~~~js
const filePath = String.raw`C:\Development\profile\aboutme.html`;
~~~

produces an error on each of the backslashes.

https://developer.mozilla.org/Web/JavaScript/Reference/Global_Objects/String/raw

**Comment by nu8** [comment]
This shows error too:

~~~js
let s = `May\nJune`;
~~~

https://developer.mozilla.org/Web/JavaScript/Reference/Template_literals

**Comment by nu8** [comment]
https://github.com/alecthomas/chroma/pull/415

**Comment by nu8** [comment]
@alecthomas I am pretty sure my fix is correct, but if you have a test suite, I would recommend running it or even adding this to it.

**Comment by alecthomas** [comment]
Add your construct to https://github.com/alecthomas/chroma/blob/master/lexers/testdata/javascript.actual and follow the instructions in the lexers/README

**Comment by nu8** [comment]
Done
