### ISSUE TITLE
Unexpected err class added to Makefile code snippet

### ISSUE THREAD

**Issue by kaushalmodi** [alecthomas/chroma#42]
Please notice the second Makefile code block here:

![image](https://user-images.githubusercontent.com/3578197/30874215-ad55723c-a2bd-11e7-96b8-38bc8cc840b8.png)

I don't know why the second block has `err` class added to all the identifiers.

Here is the Markdown for the same:

```md
-   **`infodir`:** Org Info installation directory. I like to keep the
    Info file for development version of Org in a separate
    directory.

    ```makefile
    infodir = $(prefix)/org/info # Default: $(prefix)/info
    ```
-   **`ORG_MAKE_DOC`:** Types of Org documentation you'd like to build by
    default.  Below enables generation of the Info and
    PDF Org manuals and the Org reference cards (in
    PDF too).

    ```makefile
    # Define below you only need info documentation, the default includes html and pdf
    ORG_MAKE_DOC = info pdf card # html
    ```
```
Here is the HTML:

```html
<li><p><strong><code>infodir</code>:</strong> Org Info installation directory. I like to keep the
Info file for development version of Org in a separate
directory.</p>
<div class="highlight"><pre class="chroma"><code class="language-makefile" data-lang="makefile"><span class="nf">infodir = $(prefix)/org/info # Default</span><span class="o">:</span><span class=""> </span><span class="k">$(</span><span class="n">prefix</span><span class="k">)</span><span class="">/</span><span class="n">info</span></code></pre>
</div></li>

<li><p><strong><code>ORG_MAKE_DOC</code>:</strong> Types of Org documentation you&rsquo;d like to build by
default.  Below enables generation of the Info and
PDF Org manuals and the Org reference cards (in
PDF too).</p>
<div class="highlight"><pre class="chroma"><code class="language-makefile" data-lang="makefile"><span class="c"># Define below you only need info documentation, the default includes html and pdf
</span><span class="c"></span><span class="err">ORG_MAKE_DOC</span><span class=""> </span><span class="err">=</span><span class=""> </span><span class="err">info</span><span class=""> </span><span class="err">pdf</span><span class=""> </span><span class="err">card</span><span class=""> </span><span class="err">#</span><span class=""> </span><span class="err">html</span></code></pre>
</div></li>
```

This is using this commit of chroma: https://github.com/alecthomas/chroma/commit/c99eebc024740b198c28e1013a22a8292d48dc1a

**Comment by kaushalmodi** [comment]
Also, just noticed at the comment portion of `infodir = $(prefix)/org/info # Default: $(prefix)/info` i.e. `# Default: $(prefix)/info` in that first Makefile block is also not syntax highlighted in comment face.

**Comment by kaushalmodi** [comment]
Here's the live example: https://scripter.co/building-org-development-version/

I have disabled the `err` class highlighting, but you can still see the incorrect highlighting of comments in the Makefile code blocks.

**Comment by alecthomas** [comment]
I can't replicate this locally:

![image](https://user-images.githubusercontent.com/41767/30887211-bc506a76-a35d-11e7-9b8b-07877dcd6e9a.png)

This is probably a bug with how it is integrated with Hugo (though may well still be a bug in Chroma!) Thoughts @bep?

**Comment by kaushalmodi** [comment]
As @moorereason figured out in that other issue thread, this issue can be recreated in standalone `chroma` too if the final newline is removed.

My editor was auto-adding final newline to the test `Makefile`, so the issue was never seen with CLI `chroma`. Probably you also have it set that way. Once I allowed the file to not end in a newline, I can see the problem:

![image](https://user-images.githubusercontent.com/3578197/30931666-61623550-a393-11e7-98cb-149e09616a73.png)

**Comment by alecthomas** [comment]
Interesting. These rules are directly from Pygments, so one would expect it to have the same behaviour, but it doesn't. It *looks* like Pygments automatically adds a newline if one is missing:

```shell
$ pygmentize -f raw Makefile
Token.Name.Variable	'ORG_MAKE_DOC'
Token.Text	' '
Token.Operator	'='
Token.Text	' '
Token.Text	'foo'
Token.Text	'\n'

$ chroma -f tokens Makefile
Token{Error, "ORG_MAKE_DOC"}
Token{Text, " "}
Token{Error, "="}
Token{Text, " "}
Token{Error, "foo"}
```

So it seems like that's the easy fix here.

**Comment by alecthomas** [comment]
Yes, that is exactly what Pygments does, but specifically for makefiles...

**Comment by kaushalmodi** [comment]
Thanks for investigating. Would it be possible to get rid of that hack in Chroma? If not, then I guess, you just port the hack too from Pygments. 

I briefly looked at the make lexer, but I couldn't yet understand the logic completely:

- So everything should be put in "root"?
- Each curly grace set inside root deals with a different class of highlighting?
- Each curly brace looks like a 3 element array. First element looks like a regex, which when matched sets the highlight class mentioned in the second element. But what is the third element?
- Why is the third element nil for most cases? What do Push and Pop do?
- Using seems to be like macro replacement of predefined rules. But it is not clear what `Using(Bash, nil)` means over there when used in place of the "highlight" element of the first curly brace element in "root". The regex seems to match every line beginning with space or tabs, and empty lines. **Is the `\n` in there culprit for this bug?**
- About the order of curly brace sets in each section like "root", are those order sensitive?
- About the rest of the sections: "expansion", "export", "block-header" -- they seem to be user-defined, and are basically there to break down the logic? Still not clear what Push(), Pop(1) do in these mini sections. 
- Only the "root" section looks like the main section, and it is responsible to interact with the mini sections. So if root doesn't have Push (or some other fn?) to interact with a mini section, the mini section will be useless. Is that right?

Sorry for these many questions, most of which could be stupid. But I have never coded in Go or have even tried to tweak the Pygments lexer.

**Comment by alecthomas** [comment]
Chroma lexers use a very similar approach and terminology to Pygments. If you reed the Pygments guide on [writing your own lexer](http://pygments.org/docs/lexerdevelopment/) it should tell you most of what you need to know.

There are some differences due to language, such as the third element in that struct being nil. `{`\n`, Text, nil}` is a struct initialiser, and all fields must be present. The third field is an action, such as `Push(state)`, `Pop(n)`, etc. The actions are the same as in Pygments.

**Comment by kaushalmodi** [comment]
Thanks. I'll read the docs, working towards developing an Org mode lexer. I think it will be similar to the markdown.go. 

Please fix this Makefile bug when you can. This red boxes are killing me :)

**Comment by alecthomas** [comment]
Okay, give that a whirl.

**Comment by kaushalmodi** [comment]
Awesome! Thanks!

![image](https://user-images.githubusercontent.com/3578197/31015566-c4296b66-a4ee-11e7-8276-87bdacd41c07.png)
