### ISSUE TITLE
Implement highlighting of Emacs Lisp keywords 

### ISSUE THREAD

**Issue by kaushalmodi** [alecthomas/chroma#43]
Hello,

Can the emacs-lisp keywords also be ported from [Pygments lexers/lisp.py][1]?

Live example: https://scripter.co/building-org-development-version/#set-the-correct-paths-in-your-emacs-config

![image](https://user-images.githubusercontent.com/3578197/30880000-2f3a6c74-a2cf-11e7-8b62-d3e26e3affbc.png)

Here we see that keywords like `defvar`, `with-eval-after-load`, `unless`, .. do not get highlighted at all.

[1]: https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/lisp.py?at=default&fileviewer=file-view-default#lisp.py-1532

**Comment by kaushalmodi** [comment]
Here's a screenshot of how the syntax highlighting looks from within Emacs:

![image](https://user-images.githubusercontent.com/3578197/30880172-b56b5344-a2cf-11e7-955b-9d209155e0bd.png)

Also note the special highlighting of symbol in "`..'" within the docstrings.. like `` `lispdir'``, `` `infodir'``.

**Comment by alecthomas** [comment]
You'll need to use the same theme to compare.

**Comment by kaushalmodi** [comment]
Sorry, the two screenshots were not for theme comparison.. just showing that:

- The keywords like `defvar`, `with-eval-after-load`, etc. should be highlighted.
- special highlighting of symbol in `` `..'`` within the docstrings and comments .. like `` `lispdir'``, `` `infodir'``

Comparing [emacs.go][1] with [lisp.py][2], I see that the whole section of keywords/identifiers is not ported over.

[1]: https://github.com/alecthomas/chroma/blob/caf2542b1beedc41d7b3d85f5b7e9439d7ce1a5b/lexers/emacs.go
[2]: https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/lisp.py?at=default&fileviewer=file-view-default#lisp.py-1532

**Comment by kaushalmodi** [comment]
From the site HTML, I see that the keywords, variable names, etc get classified as `<span class="n"> .. </span>`.

![image](https://user-images.githubusercontent.com/3578197/30886353-b51b4ce0-a2e4-11e7-9c6c-0072d62ff6e1.png)

**Comment by alecthomas** [comment]
Okay. The converter script can only convert RegexLexers. It's likely that the lispish ones are slightly different and will need some manual intervention. I will get to this, but probably not for a few days. If you'd like to send a PR I'll happily merge it.

**Comment by alecthomas** [comment]
Yes, this is happening because of [this function](https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/lisp.py?at=default&fileviewer=file-view-default#lisp.py-205) in Pygments. It will need to be ported.

**Comment by alecthomas** [comment]
Okay, this seems to have worked. Here's your [example code](//swapoff.org/files/t-C2tZ8dcJ6d.html) highlighted. Note that whether a particular element is highlighted also depends on the style used.

**Comment by alecthomas** [comment]
Note that I only converted EmacsLisp. The other lisps will need similar treatment.

**Comment by kaushalmodi** [comment]
Wow! Thank you for implementing this so quick, especially when you apparently don't use emacs-lisp. I'll rebuild Hugo with latest Chroma as soon as I get to my computer. 

Apologies for not providing the raw emacs-lisp code for testing. So thank you for going the extra mile to parse the raw code out of that HTML, or finding out the markdown source. I'll make sure to link the source too, next time. 

For now, emacs-lisp is the only Lisp I use. So I am content :)

Final nitpick: Can the emacs.go be renamed to emacs-lisp.go? If not that, then emacs_lisp.go or emacslisp.go?

Many thanks again! I'll try it out as soon as I can today, and report back.

**Comment by kaushalmodi** [comment]
I confirm the fix. Thank you!

From: https://scripter.co/building-org-development-version/#set-the-correct-paths-in-your-emacs-config

![image](https://user-images.githubusercontent.com/3578197/30919479-83fe13fa-a36f-11e7-9671-625543ff2031.png)
