### ISSUE TITLE
Provide source tarball preprocessed by goreleaser

### ISSUE THREAD

**Issue by sternenseemann** [alecthomas/chroma#435]
For the chroma package, since the switch to goreleaser, we have to populate the version, commit and date variables ourselves in the package when building, since we can't use goreleaser ourselves as it requires network access which is disallowed in our build sandbox.

Using `git rev-parse` etc. at build time is not desireable for us however, since git creates some reproducibility issues.

Using the prebuilt binaries is also not an option for us unfortunately.

Therefore it'd be great if you could provide an additional source tarball with releases which has the values already exchanged by goreleaser if that is possible!

**Comment by alecthomas** [comment]
I don't know if goreleaser supports that, but feel free to send a PR if it does.
