### ISSUE TITLE
Mixed PHP + HTML code not correctly parsed / highlighted (Hugo)

### ISSUE THREAD

**Issue by DanielRuf** [alecthomas/chroma#440]
**Describe the bug**

I have a case where in the middle of the file the PHP block is closed and HTML / JS / CSS output and then reopened by another `<?php`. But it seems Chroma in Hugo does not correctly catch this.

<img width="701" alt="Bildschirmfoto 2021-01-09 um 19 18 29" src="https://user-images.githubusercontent.com/827205/104105619-ae2ef700-52af-11eb-89cc-a4a41952bb0b.png">

**To Reproduce**

1. Create a fenced code block and add the `php` language to it.
2. In the PHP code close it with `?>`, add some HTML and then reopen it with `<?php`.
3. See the generated output. Starting from the first `?>`everything is red.
2. `chroma -s monokailight --html --html-lines --html-lines-table --html-inline-styles file`
As file content use https://gist.githubusercontent.com/DanielRuf/3f9bf73e239eb82800470e839b5e4b08/raw/057dc8bf6955781b23885d80387216cca9d3c099/test.php

I get the following as result:

```html
<html>
<body style="color:#272822;background-color:#fafafa">
<div style="color:#272822;background-color:#fafafa">
<table style="border-spacing:0;padding:0;margin:0;border:0;width:auto;overflow:auto;display:block;"><tr><td style="vertical-align:top;padding:0;margin:0;border:0;">
<pre style="color:#272822;background-color:#fafafa"><span style="margin-right:0.4em;padding:0 0.4em 0 0.4em;color:#7f7f7f">1
</span><span style="margin-right:0.4em;padding:0 0.4em 0 0.4em;color:#7f7f7f">2
</span><span style="margin-right:0.4em;padding:0 0.4em 0 0.4em;color:#7f7f7f">3
</span><span style="margin-right:0.4em;padding:0 0.4em 0 0.4em;color:#7f7f7f">4
</span><span style="margin-right:0.4em;padding:0 0.4em 0 0.4em;color:#7f7f7f">5
</span><span style="margin-right:0.4em;padding:0 0.4em 0 0.4em;color:#7f7f7f">6
</span></pre></td>
<td style="vertical-align:top;padding:0;margin:0;border:0;;width:100%">
<pre style="color:#272822;background-color:#fafafa">&lt;?php
function code {
?&gt;
some code
&lt;?php
}</pre></td></tr></table>
</div>

</body>
</html>
```

This can be also reproduced at https://swapoff.org/chroma/playground/

**Comment by alecthomas** [comment]
You want "phtml" as the syntax, not "php".
![image](https://user-images.githubusercontent.com/41767/107095593-34ae0880-685d-11eb-95b1-768c252f067f.png)

**Comment by DanielRuf** [comment]
Ah, thanks for the clarification.
