### ISSUE TITLE
Add Support for Plantuml

### ISSUE THREAD

**Issue by 6543** [alecthomas/chroma#443]
**What problem does this feature solve?**

Currently there is no support for [Plantuml](http://plantuml.com/guide).

**What feature do you propose?**

support it

---
~~issue source: https://github.com/go-gitea/gitea/issues/14219~~

**Comment by alecthomas** [comment]
I don't think this will do what you want it to do. IIUC PlantUML _renders_ a language into UML inline in Gitea. Chroma does not do that, it will just syntax highlight the language itself.

**Comment by 6543** [comment]
@alecthomas thanks for clarification/looking into ... did overlook some stuff ther :sweat: - anyway if you like to keep it open since chroma do not support it anyway we can leave it open  - else just close it
