### ISSUE TITLE
Format func for code indentation

### ISSUE THREAD

**Issue by mozey** [alecthomas/chroma#445]
Chroma does a great job of syntax highlighting code.

**What feature do you propose?**

Are there any plans to also do code formatting, e.g.
```
var indentedSourceCode bytes.Buffer
err := quick.Format(&indentedSourceCode, singleLineOfSourceCode, "sql")
err = quick.Highlight(os.Stdout, indentedSourceCode.String(), "sql", "html", "monokai")
```

Or should I look at a different library for this feature?

**Comment by alecthomas** [comment]
Oh interesting idea, though I'm not sure how that would work exactly. There's definitely no support for it yet.

**Comment by mozey** [comment]
Thanks for the reply. Had a look at the code, couldn't find anything, and I wasn't sure if chroma had support for this.

For golang the [gofmt](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=8m43s) command is built into the toolchain, which is nice. Other languages like python have style guides ([PEP8](https://www.python.org/dev/peps/pep-0008/)). And some I'm sure have no official guide, they either compile and run or they don't.

Sadly there is no [omnifmt](https://hackage.haskell.org/package/omnifmt) commands that supports everything.

My current use case is only for one language, SQL, but even then the different dialects should probably have their own indentation rules. For now I'm going to use a library that is specific to SQL.

**Comment by alecthomas** [comment]
Yes I think this is out of scope for Chroma, though it is an interesting idea.
