### ISSUE TITLE
Separately styling line numbers

### ISSUE THREAD

**Issue by moorereason** [alecthomas/chroma#45]
Enhancement request from https://github.com/gohugoio/hugo/issues/3915:

> I've been using the highlighting shortcode (eg `{{< highlight ini "linenos=table" >}}`) to output line numbers into one column and code into another, so I can style numbers separately.

There's currently no way to style the line number separate from the line itself.  The simplest solution seems to be to mimic Pygments' `linenos=table` behavior.

**Comment by alecthomas** [comment]
Line numbers have the CSS class `ln`, which can be styled separately, unless I'm not understanding something.
