### ISSUE TITLE
vscode styles

### ISSUE THREAD

**Issue by pcj** [alecthomas/chroma#453]
I'd like to contribute some styles based on vscode...  Is this something you'd accept?

<img width="979" alt="Screen Shot 2021-02-25 at 9 16 50 AM" src="https://user-images.githubusercontent.com/50580/109182557-4db62500-774a-11eb-9e4f-70c7a25b30ac.png">

**Comment by alecthomas** [comment]
For sure!

**Comment by alecthomas** [comment]
No response.
