### ISSUE TITLE
Svelte syntax

### ISSUE THREAD

**Issue by acim** [alecthomas/chroma#455]
**What problem does this feature solve?**

Please check the Chroma [README](https://github.com/alecthomas/chroma) and command-line tool to ensure this isn't an already solved problem.

**What feature do you propose?**

Adding syntax highlighting for [Svelte](https://svelte.dev/).

**Comment by iamvukasin** [comment]
I have a basic lexer for Svelte already written, so I can take this one. I will fill a PR in a few days.

**Comment by CIAvash** [comment]
I think this can be closed now that Svelte lexer has been added.
