### ISSUE TITLE
[bug] Empty line appended to all output

### ISSUE THREAD

**Issue by FooSoft** [alecthomas/chroma#47]
Simple test application:

```go
package main

import (
	"bytes"
	"fmt"

	"github.com/alecthomas/chroma/formatters/html"
	"github.com/alecthomas/chroma/lexers"
	"github.com/alecthomas/chroma/styles"
)

func main() {
	input := "hello world"

	lexer := lexers.Get("javascript")
	iterator, _ := lexer.Tokenise(nil, input)
	style := styles.Get("github")
	formatter := html.New(html.WithLineNumbers())

	var buff bytes.Buffer
	formatter.Format(&buff, style, iterator)

	fmt.Printf("[%s]", buff.Bytes())
}
```

Produces the following output (notice the line break; there is none in the input):
```html
[<pre style="background-color:#fff"><span style="color:#7f7f7f;margin-right:0.4em;padding:00.4em00.4em;">1</span>hello world
<span style="color:#7f7f7f;margin-right:0.4em;padding:00.4em00.4em;">2</span></pre>
]
```

Expected output:
```html
[<pre style="background-color:#fff"><span style="color:#7f7f7f;margin-right:0.4em;padding:00.4em00.4em;">1</span>hello world</pre>]
```

Happens with and without `WithLineNumbers`, but the problem is easier to see this way. Output shows that there are two lines, but there is obviously only one.

**Comment by FooSoft** [comment]
I managed to get expected behavior with:
```go
	lexer.Config().DontEnsureNL = true
```

Is this the correct solution to this? My website ends up having really nasty looking whitespace from the blank lines otherwise.

**Comment by FooSoft** [comment]
Actually to be completely accurate, I still have to trim newline character from the result:

```go
fmt.Printf("[%s]", strings.Trim(string(buff.Bytes()), "\n")))
```

**Comment by alecthomas** [comment]
This is the same behaviour as Pygments, AFAICT:

```
$ echo -n 'hello world' | pygmentize -l js -f html -O style=colorful,linenos=inline
<div class="highlight"><pre><span></span><span class="lineno">1 </span><span class="nx">hello</span> <span class="nx">world</span>
</pre></div>
```

Some (many? Hard to tell) lexers rely on this behaviour, which is why it was introduced. See #42.

**Comment by alecthomas** [comment]
> Actually to be completely accurate, I still have to trim newline character from the result

This is expected and shouldn't impact the resulting HTML, right?

**Comment by FooSoft** [comment]
Thanks for the quick reply. 

So given that there are lexers which are not robust enough to handle files code spans without a terminating newline, what about just fixing up the results after the lexer has finished processing (e.g. strip newlines)? Maybe at least have an opt-in setting to do this? Once chroma outputs the HTML it becomes a lot more difficult to strip out this data.

Imagine a blog post where there are a lot of single or double code snippets mixed in with article text. Having newlines inserted into these short code blocks is noticeable and looks distracting and even broken. I don't know the reasons behind why this happens in Pygments (possibly a bug?), but I haven't seen this behavior in any other syntax highlighter or can I think of any situation where it is useful as anything other than a workaround for questionable lexers. 

Regarding your second reply, the resulting HTML should technically not be impacted but it can be in some cases. I'm rendering my page with blackfriday and it wraps all code snippets in `<pre><code>`. Since the `<code>` tag contains the source code, I was just dropping the output of chroma into it. This lead to the surrounding tags becoming `<pre><code><pre>` (which I will be the first to admit was not a great way to go about it), but having the linebreak after the chroma-generated `<pre>` tag ended up being meaningful since it was still wrapped by the outer `<pre>`. This is something that can definitely be easy to work around, but I still think that chroma should not output a single character more than it is required to.

**Comment by alecthomas** [comment]
> Imagine a blog post where there are a lot of single or double code snippets mixed in with article text. Having newlines inserted into these short code blocks is noticeable and looks distracting and even broken. I don't know the reasons behind why this happens in Pygments (possibly a bug?), but I haven't seen this behavior in any other syntax highlighter or can I think of any situation where it is useful as anything other than a workaround for questionable lexers.

Yes, I agree it is quite odd. I think what I might do is to invert the default for that configuration option, so that a lexer has to opt IN to get extra newlines. The only one that I'm aware of is the make one at the moment.

> Regarding your second reply, the resulting HTML should technically not be impacted but it can be in some cases. I'm rendering my page with blackfriday and it wraps all code snippets in `<pre><code>`. Since the `<code>` tag contains the source code, I was just dropping the output of chroma into it. This lead to the surrounding tags becoming `<pre><code><pre>` (which I will be the first to admit was not a great way to go about it), but having the linebreak after the chroma-generated `<pre>` tag ended up being meaningful since it was still wrapped by the outer `<pre>`. This is something that can definitely be easy to work around, but I still think that chroma should not output a single character more than it is required to.

Mmm, yeah. TBH that feels like a bit of an edge case, but there's no compelling reason other than neatness to keep the newline.

**Comment by alecthomas** [comment]
Okay, give latest master a whirl. Both of these should be fixed (as well as the empty span segments...).

**Comment by alecthomas** [comment]
Thanks for the thorough bug report BTW, appreciated.

**Comment by FooSoft** [comment]
Looking good, thank you for the fix! :+1: 
Really happy to have syntax highlighting in a Go lib, keep up the good work!
