### ISSUE TITLE
Add support for hl_lines, linenos

### ISSUE THREAD

**Issue by bep** [alecthomas/chroma#5]
First, this is great and really appreciated.

I maintain Hugo and wanted to use your library. I searched the code and I assume these Pygments options are not implemented:

* hl_lines - highlight a range of lines
* linenos - show line numbers to the left

I understand that you cannot implement the full Pygments, but I added those two flags to Hugo as it was requested by many.

**Comment by alecthomas** [comment]
I assume this is for the HTML formatter?

If so, it should be fairly simple to add! I'll see if I can do it tonight.

**Comment by bep** [comment]
>I assume this is for the HTML formatter?

Yes. And thanks again.

**Comment by alecthomas** [comment]
Okay, this should be implemented. Line numbers in 3f230ec71710e57e182c046a9d84cd7a5b65d083 and highlighting in a5637e60b2a16a6fdb4390fc2c331f80f20608ac.

```
$ chroma -s pygments \
  --html \
   --html-line-numbers \
  --html-highlight=5:8,1,15:20 \
  --html-highlight-style='bg:#eee' \
   lexer.go
```

Results in this:

![image](https://user-images.githubusercontent.com/41767/30626790-935c9b60-9e0f-11e7-9882-0f65e0ab2441.png)

Note that there is no automatic selection of line number and highlight styles based on dark/light themes. There's no concept of light/dark themes at all, but I think it will be necessary to add, so as to avoid having to manually select styles for each theme.

If this is not quite correct, or needs some tweaks, let me know.

**Comment by alecthomas** [comment]
Unfortunately performance has regressed somewhat.

Before:
```
BenchmarkHTMLFormatter-8   	   10000	    110769 ns/op
```

After:
```
BenchmarkHTMLFormatter-8   	    3000	  11548172 ns/op
```

**Comment by alecthomas** [comment]
Ah, that is due to a bug!

**Comment by alecthomas** [comment]
Actual new timings are:
```
BenchmarkHTMLFormatter-8   	   10000	    131209 ns/op
```

**Comment by bep** [comment]
Those benchmarks comes in handy sometimes ... Thanks a lot for this and for the super fast response. I agree about the "dark theme" remark, but that isn't super-important for me.

**Comment by alecthomas** [comment]
Fixing the underlying bug will require breaking changes to the API, but the changes shouldn't be too significant.
