### ISSUE TITLE
Leading underscores in JavaScript identifiers incorrectly parsed as LiteralNumberInteger

### ISSUE THREAD

**Issue by chalin** [alecthomas/chroma#507]
Consider the following snippet of JavaScript:

```js
var PROTO_PATH = __dirname + '/../../../protos/route_guide.proto';
```

Using the [v0.9.1 playground](https://swapoff.org/chroma/playground/), you'll get this output:

> <img src='https://user-images.githubusercontent.com/4140793/118272014-02312e80-b490-11eb-93c6-d6dd72b7bbc4.png' width=550>

```html
<pre class="chroma">
<span class="kd">var</span> <span class="nx">PROTO_PATH</span> <span class="o">=</span> 
<span class="mi">__</span><span class="nx">dirname</span> <span class="o">+</span> <span class="s1">&#39;/../../../protos/route_guide.proto&#39;</span><span class="p">;</span>
</pre>
```

Notice how the leading underscore characters (`__`) are formatted as "mi" (LiteralNumberInteger) rather than "nx" (NameOther ) like the rest of the identifier `__dirname`.

As @jmooring pointed out in https://github.com/gohugoio/hugo/issues/8532#issuecomment-840932485, 

> I think this is the change that is causing the problem:
> https://github.com/alecthomas/chroma/commit/881d54f096b115a34bbaa6585915e3840ec46fcd#diff-12f3e5a2dbe731b9b91b6e604b0f7e1b8928ae8ceaee52b7f014752b25d82005L33-R33

**Comment by chalin** [comment]
> So I have a genuine question here. Given that two people know where the issue is already, why not just click the edit button in GitHub, fix it, and send a PR? Surely that would have been quicker than writing this comprehensive ticket?

As someone with expert knowledge of the inner workings of chroma, the fixes you did in 6a6cf1764db914057a47d8fb782924f27dd3a7b9 might seem obvious, but it can feel daunting to those unfamiliar with the inner workings of chroma (the code, how to update & run tests, etc).

Having spent some time crafting #551, I'd now feel more comfortable doing what you suggested, but that seemed out of reach back in May :).

**Comment by alecthomas** [comment]
@chalin that's a good point that I hadn't considered, thanks - a side-effect of Chroma being used so heavily by Hugo is that a _lot_ of Chroma users are not Go users. Maybe it would be good to have a "contributing" section in the README, would you be interested in contributing that?

**Comment by chalin** [comment]
Sure, though I'm not sure what you like written in such a section (relative to your comment about most users not knowing Go).
