### ISSUE TITLE
Add a11y support for tabindex="0" to make scrollable pre focusable

### ISSUE THREAD

**Issue by rhymes** [alecthomas/chroma#514]
**What problem does this feature solve?**

Currently the generated `<pre>` element isn't fully accessible as it can't be focused by keyboard users.

An example of syntax highlighting (using Hugo) and how the [aXe devTools extension](https://www.deque.com/axe/browser-extensions/) detects this issue:

<img width="1789" alt="Screenshot 2021-05-23 at 10 35 27 PM" src="https://user-images.githubusercontent.com/146201/119275887-ec520500-bc17-11eb-8ad4-545c35138fb9.png">

Additional info:

- [Deque University: Ensure that scrollable region has keyboard access](https://dequeuniversity.com/rules/axe/4.2/scrollable-region-focusable):

> The key to getting a scrollable region to be accessible with the keyboard is to ensure that a keyboard-only user can focus the scrollable region itself or a static text item within the scrollable region.

- [Accessibility insights: scrollable-region-focusable](https://accessibilityinsights.io/info-examples/web/scrollable-region-focusable/)

> Thus, scrollable content is keyboard accessible only if the scrollable element is focusable or contains a focusable element.

**What feature do you propose?**

To make this fully accessible, the attribute `tabindex="0"` should be added to the `<pre>` tag.

According to [MDN's page on tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) the attribute can have 3 values:

- `-1`, which means "skip it using sequential tabbing"
- `0`, focusable with sequential keyboard navigation (what we want in this case)
- something over 0, which changes the priority of tabbing inside the page

**Comment by alecthomas** [comment]
Sounds reasonable, PR welcome.

**Comment by rhymes** [comment]
@alecthomas thanks! Done: https://github.com/alecthomas/chroma/pull/515
