### ISSUE TITLE
Merge text analyses from forked repository

### ISSUE THREAD

**Issue by gandarez** [alecthomas/chroma#524]
**What problem does this feature solve?**

We at WakaTime have been during the last months implementing various text analyses for available lexers. Them were merged into our master branch and used for [wakatime-cli](https://github.com/wakatime/wakatime-cli). Would you consider merging our changes into the main repository?

**Comment by alecthomas** [comment]
For sure!

**Comment by alecthomas** [comment]
No response on #527
