### ISSUE TITLE
Error when I try to install command line interface

### ISSUE THREAD

**Issue by gmr458** [alecthomas/chroma#526]
**Describe the bug**

A clear and concise description of what the bug is. Screenshots are often helpful here.
![image](https://user-images.githubusercontent.com/53343401/122684752-fb06ea00-d1cc-11eb-8627-95ef225a2516.png)

Do *NOT* just paste a link to other issues on GitHub.

**To Reproduce**

1. Provide copyable *text* (not an image) that reproduces the issue.
`go get -u github.com/alecthomas/chroma/cmd/chroma`
2. Provide a `chroma` command-line invocation to reproduce the issue with the above input text. eg. for Hugo the (rough) equivalent would be `chroma -s monokailight --html --html-lines --html-lines-table --html-inline-styles <source>`

Do *NOT* provide configuration for another tool (eg. Hugo). My time is limited and if you want me to fix your issue, help me help you.

**Comment by alecthomas** [comment]
cmd/chroma is now a seperate module in order to keep the imports minimal. I'm not sure what the go invocation is, but you can use the binary releases on GitHub.
