### ISSUE TITLE
Can no longer install chroma binary with go get

### ISSUE THREAD

**Issue by artis3n** [alecthomas/chroma#533]
**Describe the bug**

Attempting to install the package via `go get` now fails, was previously working.

The alternative approach with go 1.16 is to use `go install`, which also fails. I haven't seen a line like https://github.com/alecthomas/chroma/blob/master/cmd/chroma/go.mod#L8 before so not sure what it is supposed to do. But Go does not seem to like it.

**To Reproduce**

Run `go get -u github.com/alecthomas/chroma/cmd/chroma`

```bash
go get -u github.com/alecthomas/chroma/cmd/chroma

go get: github.com/alecthomas/chroma/cmd/chroma@none updating to
        github.com/alecthomas/chroma/cmd/chroma@v0.0.0-20210717222423-a0e9618fbcc4 requires
        github.com/alecthomas/chroma@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

Run `go install github.com/alecthomas/chroma/cmd/chroma@latest`

```bash
go install github.com/alecthomas/chroma/cmd/chroma@latest  
                         
go install github.com/alecthomas/chroma/cmd/chroma@latest: github.com/alecthomas/chroma/cmd/chroma@v0.0.0-20210717222423-a0e9618fbcc4
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by alecthomas** [comment]
Please use the binary releases on Github.
