### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by chalin** [alecthomas/chroma#561]
> @alecthomas: might you be making a release soon? I'd love to start using this basic [console] lexer in Hugo, and get the fix to #507 so that we can close https://github.com/gohugoio/hugo/issues/8532.

_Originally posted by @chalin in https://github.com/alecthomas/chroma/issues/551#issuecomment-922467132_

**Comment by alecthomas** [comment]
Released https://github.com/alecthomas/chroma/releases/tag/v0.9.4!
