### ISSUE TITLE
Add Bicep language syntax highlighting

### ISSUE THREAD

**Issue by Jandev** [alecthomas/chroma#562]
**What problem does this feature solve?**
Bicep is the a 'new' DSL created by Microsoft. It enables us developers to create better ARM templates.
More information can be found over here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/overview

Where ARM Templates are just a different flavor of JSON, Bicep has a different syntax.

At the moment, specifying the `bicep` language will result in having a non-highlighted code block.

**What feature do you propose?**
Implement the Bicep language for syntax highlighting.

I haven't looked at the code of this project yet, but it sounds like a good first issue for someone to pick up.

**Comment by samtrion** [comment]
Since I myself currently have Biceps, as an urgent need, I have created a PR.

PR #564 should cover the current Bicep version completely.
