### ISSUE TITLE
Add One Dark theme

### ISSUE THREAD

**Issue by AntoniosBarotsis** [alecthomas/chroma#568]
I found at least some of the colors [here](https://github.com/joonro/Spyder-Color-Themes/blob/master/atom-one-dark.ini).

**Comment by serhack** [comment]
It seems great, tomorrow I'll commit that.

![image](https://user-images.githubusercontent.com/27734319/201210871-34fa1256-66c0-4222-8180-1cedfe3b90bb.png)
