### ISSUE TITLE
PHTML lexer takes priority over PHP?

### ISSUE THREAD

**Issue by gandarez** [alecthomas/chroma#577]
**Describe the bug**

An empty `file.php` is being parsed as **PHTML** instead of a **PHP** file because PHTML lexer has higher priority (actual 2) over PHP which is 0. To maybe fix it we might set **PHP** with priority 1 and **PHTML** with priority 0.1?

**To Reproduce**

N/A

relates https://github.com/alecthomas/chroma/pull/477

**Comment by gandarez** [comment]
anybody?

**Comment by gandarez** [comment]
hello

**Comment by alecthomas** [comment]
I have no real opinion on this, but if you think this is the right thing to do please send a PR.
