### ISSUE TITLE
Export the `classes` field

### ISSUE THREAD

**Issue by Depado** [alecthomas/chroma#58]
Hi ! Thanks for the awesome project !

I'm currently integrating [chroma into a blackfriday markdown renderer](https://github.com/Depado/bfchroma), and there just one tiny issue with the `WithClasses()` functional option. I have yet no way of knowing if that option was used since the field in the  `html.Formatter` struct isn't exposed which means I can't determine if I need or not to write the CSS. 

Is there a way that field could be made public ?
Or maybe add a `HasClasses()` method in the `Formatter` interface ?

Thanks ! 🎉

**Comment by alecthomas** [comment]
I have no problem with making that field public. Please send a PR!

**Comment by Depado** [comment]
Will do ! Thanks :D

**Comment by Depado** [comment]
Done, see #61 
Does that suit you ? Or would you prefer to directly export the field ?

**Comment by alecthomas** [comment]
I think just exporting the field should be fine (with a comment). Be nice if Go had immutable fields, but there you go.

**Comment by Depado** [comment]
There you go 😄

**Comment by Depado** [comment]
Thanks a lot 👍
