### ISSUE TITLE
[Feature request] Please add gruvbox color scheme

### ISSUE THREAD

**Issue by kirillbobyrev** [alecthomas/chroma#581]
[gruvbox](https://github.com/morhetz/gruvbox) is a really cool color scheme that would be great to support in chroma!

There were some [attempts to port](https://github.com/daveyarwood/gruvbox-pygments) it to pygments, but I don't have familiarity with chroma's internals.

**Comment by zpyg** [comment]
I am trying to add gruvbox color scheme, but I don't know how to test it.

**Comment by zpyg** [comment]
I created a PR #592 just now.

**Comment by mhmdanas** [comment]
That PR was merged, so shouldn't this be closed?

**Comment by kirillbobyrev** [comment]
> That PR was merged, so shouldn't this be closed?

You're right, thanks!
