### ISSUE TITLE
Feature request - add support for Arduino

### ISSUE THREAD

**Issue by oveddan** [alecthomas/chroma#59]
Linguist currently supports Arduino and provides syntax highlighting for platform specific operations and definitions.

See the Linguist Spec for Arduino [here](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml), and this [example](https://github.com/github/linguist/tree/master/samples/Arduino):

```Arduino
const int buttons[4] = {2,3,4,5};
const int octaves[2] = {6,7};

void setup() {                
  // initialize the digital pin as an output.
  // Pin 13 has an LED connected on most Arduino boards:

  pinMode(13,OUTPUT);

 for(int i =0;i<sizeof(buttons)/sizeof(int);i++){
   pinMode(buttons[i],INPUT );
 }
 
 for(int i =0;i<sizeof(octaves)/sizeof(int);i++){
   pinMode(octaves[i],INPUT );
 }
 
  Serial.begin(9600);
}


void loop() {
  delay(1);              // wait
  int output = -1;
  
 // Serial.print(digitalRead(buttons[0]));
  
 for(int i =0;i<sizeof(buttons)/sizeof(int);i++){
   if(digitalRead(buttons[i])==LOW
   ){
     if(output<=0){
       output=1;
     }
     output+=i+1;
   }
 }
 
 for(int i =0;i<sizeof(octaves)/sizeof(int);i++){
    if(output<=0){
       break;
     }
   if(digitalRead(octaves[i])==LOW
   ){
     output*=7*(i==1 ? -1 : 1);
   }
 }
  if(output>=0){
  Serial.print(output);
  Serial.println(";");
  digitalWrite(13,HIGH);
  }else{
  digitalWrite(13,LOW);
  }
}
```

It would be great if chroma provided syntax highlighting like this as well.

**Comment by alecthomas** [comment]
I assume this is C++?

You should be able to use the [TypeRemappingLexer](https://godoc.org/github.com/alecthomas/chroma#TypeRemappingLexer) and just extend the C++ lexer.

eg.

```go
var Arduino = TypeRemappingLexer(CPP, TypeMapping{
  {Name, Keyword, []string{"pinMode", "digitalRead", "digitalWrite" /* etc. */}},
  // etc.
})
```

PRs welcome!

**Comment by oveddan** [comment]
Cool, I'd be glad to work on this!

**Comment by per1234** [comment]
This contains the Arduino core API keywords:
https://github.com/arduino/Arduino/blob/master/build/shared/lib/keywords.txt
Bundled libraries specify their own keywords and hardware cores can add additional keywords but the ones on that list are probably all anyone would expect/want.

And yes, Arduino's .ino files are C++. the IDE just does a little preprocessing (mainly generating any missing function prototypes) before renaming it with .cpp extension and compiling.
