### ISSUE TITLE
mariadb language as alias to mysql

### ISSUE THREAD

**Issue by hrvoj3e** [alecthomas/chroma#590]
**What problem does this feature solve?**

I am using Gitea that uses `chroma` for highlighting.
Before it supported `mariadb` language because it used `highlightjs`

**What feature do you propose?**

Could you add language `mariadb` as alias to `mysql`? Is this possible?
It has the same syntax.

**Comment by silverwind** [comment]
Should be a simple addition here: https://github.com/alecthomas/chroma/blob/master/lexers/m/mysql.go#L19

**Comment by hrvoj3e** [comment]
Not comfortable with Go.
Could you or someone make a PR with this change?

**Comment by silverwind** [comment]
https://github.com/alecthomas/chroma/pull/595
