### ISSUE TITLE
Add support for Vala

### ISSUE THREAD

**Issue by lw64** [alecthomas/chroma#599]
Currently the Vala programming language is not supported.

That would be good to have.

https://gitlab.gnome.org/GNOME/vala/

**Comment by rafaelmardojai** [comment]
Pygments seems to have a [Vala lexer](https://github.com/pygments/pygments/blob/f2264a0014eb1b8b764c30bea668133bcc88bec1/pygments/lexers/c_like.py#L179), it is possible to use the translators here?
