### ISSUE TITLE
Placeholder support

### ISSUE THREAD

**Issue by xxxbobrxxx** [alecthomas/chroma#602]
In google documentation there is a great feature called [Placeholders](https://developers.google.com/style/placeholders#explain-placeholders)

Can that feature be implemented in chrome to be used in hugo? It would be great to use that feature in 2 scenarios:

- You change a variable in one place - variables in other code blocks with same name change also
- Without previously described effect 

Thanks!

**Comment by alecthomas** [comment]
I think that would be better suited as a Hugo plugin, it's pretty out of scope for Chroma.
