### ISSUE TITLE
Playground v2.0.0-alpha2 is broken

### ISSUE THREAD

**Issue by braoult** [alecthomas/chroma#610]
Playground (https://swapoff.org/chroma/playground/) looks broken. It was OK yesterday.

Environment: Firefox 96.0 on Xubuntu 21.10.

Current output (I tried different languages) :

![Screenshot_2022-02-22_14-23-48](https://user-images.githubusercontent.com/8958429/155141111-8aff0966-aab6-424c-b070-86d691dba13f.png)

**Comment by alecthomas** [comment]
This works fine for me in Chrome, and I haven't updated it recently.

**Comment by braoult** [comment]
Chomium works too... Firefox console shows a lot of errors (it did work yesterday).

![Screenshot_2022-02-22_22-26-37](https://user-images.githubusercontent.com/8958429/155222268-3559840f-a606-4141-83f4-e66b97ee80de.png)

There is a 403 somewhere :
![Screenshot_2022-02-22_22-29-36](https://user-images.githubusercontent.com/8958429/155222716-fae812eb-e8e7-4b47-99d8-20954f02c88a.png)

**Comment by braoult** [comment]
@alecthomas,  I fixed the issue, I don't understand why I needed to do it :
1) I removed 2 cookies from https://swapoff.org
     At this stage, source code was displayed (before that, preview was just empty as in screenshots above), but no highlighting at all in source code.
2) I removed all cached data in Firefox, then forced reload of https://swapoff.org
    After that, the site did work again.

There is something wrong somewhere, but I will close this issue if it is fine for you.

**Comment by braoult** [comment]
There is nothing I can add here, si I close this issue for now, and try to investigate (if I can) if it happens again.

**Comment by braoult** [comment]
Same happened again on Firefox.

So I tried also with Chromium again, and I have the same kind of problems :

![Screenshot_2022-02-27_09-21-25](https://user-images.githubusercontent.com/8958429/155874597-ccf8011d-e01c-4d0d-a283-54be5be9d312.png)

**Comment by CIAvash** [comment]
@braoult Can you open the Network tab of developer tools and reload the page and look at the request and response headers, see if anything is unusual?

**Comment by braoult** [comment]
@CIAvash, I will need to wait for it to break again...

But, in my two screenshots, you can see the console errors :
- While not working (many errors: 403s, then JSON errors)
- While working again (just a favicon.ico 404)

I had similar errors on Firefox (my previous posts).

If you look at [this previous post](https://github.com/alecthomas/chroma/issues/610#issuecomment-1048230792), you can see some Firefox 403 details.

**Comment by braoult** [comment]
I know for favicon, this is why I ignored it. I updated my answer, about the possible error (I cannot test anything now, as it is working).

**Comment by CIAvash** [comment]
I'm not sure about that, when I make a POST request to "https://swapoff.org/chroma/playground/api/render" without cookie and token, I get the "Forbidden - CSRF token invalid" response. Which seems to be the same content-length as yours(not that it means it's the same problem, we won't know until you see the response). And there is deleting cookies and cache which makes it work again, that's why I'm guessing the problem is with an invalid cookie/token.

You can also emulate this by blocking all cookies (from browser settings), but of course this just a wild guess.

**Comment by braoult** [comment]
I use playground nearly on a daily basis : I will check exact 403 answer when it fails again, likely in a few days...

**Comment by alecthomas** [comment]
I had never seen this before, but I encountered it today and am able to replicate it. I'll see if I can fix it.

**Comment by alecthomas** [comment]
I noticed that I had two separate CSRF cookies, one for / and one for /api, then found [this section](https://github.com/gorilla/csrf#cookie-path) in the gorilla/csrf docs. I've set this and hopefully it will fix it.

**Comment by alecthomas** [comment]
This just occurred again for me again and it looks like gorilla/csrf is somehow setting two cookies:

```
_gorilla_csrf=MTY3NDE5Mzg3NnxJbXhaZUZsd1JFNXZOblJ2VkdweVZIbG1UQzkxVTNabWNYZFFWVzE0UkRaM01rZHFUSEYxY1U1UFNEQTlJZ289fKchguudE6ipzr7JVOZJ9RrEuHkSIaptJsm6JjKrF8P-; _gorilla_csrf=MTY3NDE5Mzg4NHxJbGxUYjBoSlRtTTFTV3ROVkdJdmJEVXdWSFU0U1VORVIxZEZVbHB2Tm1wbE1URTVOVWxzUzFoMWFVMDlJZ289fER8ge4YJ4N1Hn0DRtB2SEyosLapB35GyssgVWANppHV
```

I would guess this is a bug in gorilla/csrf, but as it is now unmaintained I'm going to try switching to a different CSRF library.
