### ISSUE TITLE
Highlight lines in code blocks

### ISSUE THREAD

**Issue by laoshaw** [alecthomas/chroma#616]
**What problem does this feature solve?**

make key lines of code standout

**What feature do you propose?**

something like Prism does, as shown below:

![image](https://user-images.githubusercontent.com/18351761/157166481-6b73c325-d99a-4506-9a66-8a4751a1378a.png)

**Comment by alecthomas** [comment]
This is [already implemented](https://github.com/alecthomas/chroma/blob/master/formatters/html/html.go#L83-L88).
