### ISSUE TITLE
Duplicate Line in _tools/pygments2chroma.py

### ISSUE THREAD

**Issue by DavePearce** [alecthomas/chroma#625]
**Describe the bug**

The script `_tools/pygments2chroma.py` does not appear to be working for me at the moment.  Specifcally, `python3` (`3.8.10`) complains about `keyword argument repeated` (details below).

**To Reproduce**

```
python3 _tools/pygments2chroma.py pygments.lexers.whiley.WhileyLexer
```

This produces the following output:

```
  File "_tools/pygments2chroma.py", line 194
    upper_name=to_camel_case(re.sub(r'\W', '_', lexer_cls.name)),
    ^ 
SyntaxError: keyword argument repeated
```

Looking at the `_tools/pygments2chroma.py` script I see this on line 193:

```python
        upper_name=to_camel_case(re.sub(r'\W', '_', lexer_cls.name)),
        upper_name=to_camel_case(re.sub(r'\W', '_', lexer_cls.name)),
```

If I remove the duplicate line, then the script appears to do something useful.

**Comment by alecthomas** [comment]
Unfortunately that script is no longer functional, as Chroma now uses XML definitions for lexers. I want to migrate it at some point, but I don't have time.

**Comment by DavePearce** [comment]
Hey Alec,

Yeah, I noticed the `XML` definitions for other languages like Dart, etc.  Is there some documentation on the format for these?  I can probably figure it out from looking at others, but if there's some docs that would be great.

Also, I was having trouble building chroma yesterday for testing.  Basically, so I could test my new lexer.  I'm not a big `go` person.  What is the suggested mechanism for testing a new language lexer?

**Comment by alecthomas** [comment]
Hey Dave, you should be able to build with `./bin/go build ./cmd/chroma` (using [Hermit](https://cashapp.github.io/hermit/)) or install Go system wide and run `go build ./cmd/chroma`.

**Comment by alecthomas** [comment]
You can run tests with `./bin/go test ./...`

**Comment by DavePearce** [comment]
Great, thanks Alec --- I'll give that a try!
