### ISSUE TITLE
Custom style loader

### ISSUE THREAD

**Issue by jolheiser** [alecthomas/chroma#635]
**What problem does this feature solve?**

Currently, new styles need to be PRed into chroma (or use a pygments CSS file). This is okay, but it means that custom styles are somewhat confusing to load into chroma.

**What feature do you propose?**

Theoretically, chroma themes aren't very complicated and should be configurable outside of the Go language (or pygments css).
I propose a [JSON schema](https://json-schema.org/) and subsequent way to load a `<style>.chroma.json` into chroma, which would allow anyone to load a custom style.
The schema allows IDEs to lint the style as the user writes it, which makes it easier to create custom styles. 
The real core functionality is just translating that JSON into a slice of chroma style entries.

I would be more than happy to contribute it in some form to this repo, or leave it third-party.

**Comment by dezza** [comment]
I love this idea. This was my main reason for forking chroma last time I used it.
https://github.com/alecthomas/chroma/commit/5d5eaa17f385cfc5d437c57417d92d821d9e9a9f

**Comment by alecthomas** [comment]
I think this would be a great idea, though I'd prefer XML for consistency with the lexers.
