### ISSUE TITLE
Yes

### ISSUE THREAD

**Issue by villanueva44** [alecthomas/chroma#672]
**Describe the bug**

A clear and concise description of what the bug is. Screenshots are often helpful here.

Do *NOT* just paste a link to other issues on GitHub.

**To Reproduce**

1. Provide copyable *text* (not an image) that reproduces the issue.
2. Provide a `chroma` command-line invocation to reproduce the issue with the above input text. eg. for Hugo the (rough) equivalent would be `chroma -s monokailight --html --html-lines --html-lines-table --html-inline-styles <source>`

Do *NOT* provide configuration for another tool (eg. Hugo). My time is limited and if you want me to fix your issue, help me help you.

**Comment by alecthomas** [comment]
What?
