### ISSUE TITLE
Can C# highlight also include classes, interfaces, enums?

### ISSUE THREAD

**Issue by Jos512** [alecthomas/chroma#68]
Chroma is great and I'm happy with it. But I think the [C# lexer](https://github.com/alecthomas/chroma/blob/master/lexers/csharp.go) can improved. Currently, it doesn't recognise standard .NET framework classes, interfaces, and enumerations. I think the Chroma highlight will be for the better if we include those.

As an example, here's how a small code snippet looks like in Visual Studio:

![code-highlight-visua-studio](https://user-images.githubusercontent.com/13403160/31838768-94d4cc10-b5de-11e7-85bf-62dac3ad8056.png)

With Chroma's C# lexer highlighting, I see this:

![code-highlight-chroma](https://user-images.githubusercontent.com/13403160/31838779-9fa0a07e-b5de-11e7-93c3-54be8b5149ca.png)

It's pretty colourless in Chroma, honestly, and I think the lightblue highlighting of `DriveInfo`, `IEnumerable`, `Directory`, and `Console` here would really add value in making the code easier to read and interpret.

Is there a way to expand the C# lexer for this? Perhaps Alec has an idea, or perhaps otherwise you @steambap? (I ping you because you made the original lexer, and have a better understanding of how it works than I do.)

**Comment by steambap** [comment]
Visual Studio knows everything because it has the real C# parser buildin. It knows you are importing `Console` with `using System;` statement. On contrary, chroma is a regexp based lexer, not a real parser. In other words, it do not knows you are `using System;`. 

As you can see in [Microsoft's own website](https://msdn.microsoft.com/en-us/library/system.console(v=vs.110).aspx#code-snippet-2), it's also using some kind of regexp based lexer and it does not understand `Console`.

There is a work around though. You could add `Console` and `IEnumerable` as NameBuiltin since everybody will be `using System;` and `using System.Collections;`. 
The code probably will be:
```
{`(?<!\.)(Console|IEnumerable)\b`, NameBuiltin, nil}
```
But then I guess someone would argue that C# does not have globals. They should not be NameBuiltin.

**Comment by Jos512** [comment]
Thanks for your comments Steambap.

> As you can see in Microsoft's own website, it's also using some kind of regexp based lexer and it does not understand Console.

That's true, but I'd like it to look a bit nicer than how it looks like on MSDN and other sites. It might also give Chroma an advantage if it looks better than any other syntax highlighter out there.

I see by the way that StackOverflow goes the other way: where MSDN doesn't colour classes, SO colours both classes and methods in the same way (which is not nice other I thing). See [here](https://stackoverflow.com/questions/11949951/working-with-console-writeline-c-sharp) for an example. Their lexer gives everything (keywords, class names, method names, namespace names) the `typ` CSS class.

> But then I guess someone would argue that C# does not have globals. They should not be NameBuiltin.

Perhaps `NameBuiltin` doesn't suit it, no. But there's also a `NameClass` for class names and a `NameOther` that we could stamp on interfaces.

--------

I think there are roughly two ways to expand the C# lexer:

1. Hard-code all 'common' classes and interfaces. (And use regex to weed out the false positives. For instance, a method named `Console()` shouldn't be coloured as the `Console` class.)
2. Or use regex to colour all static classes. That wouldn't colour all classes, but is probably easier to implement and still catches a large portion of them.

Examples of point 2 are:

- `DriveInfo.GetDrives()` -> colour `DriveInfo` as static class.
- `Directory.EnumerateDirectories(drive.RootDirectory.ToString())` -> `Directory`
- `Console.WriteLine()` -> `Console`
- `Convert.ToInt32()` -> `Convert`
- `GlobalDictionary.NamedDoubles.TryGetValue("LastValue", out received)` -> `GlobalDictionary` (custom static class).
- `DateTime.Now.ToString("HH:mm:ss.fff")` -> `DateTime` as 'class' (actually struct, but it's coloured wherever you look as classes are).

**Comment by steambap** [comment]
Point 2 looks good to me.

**Comment by alecthomas** [comment]
Quite a number of lexers have a static list of names that are treated specially, so there is precedent. I'd accept a PR.

**Comment by Jos512** [comment]
Thanks for the feedback Steambap and Alecthomas.

I like point 2 because it also allows syntax highlighting for static classes we created in our own code. But a static list of names will for all (?) standard .NET framework classes would of course be the option with the least amount of missing syntax highlights.

Alec, can you say how long such a static list of names can be without affecting performance?

Weilin, could you help implement this? I'm don't know much Go nor Go's regex, so I'm a bit lost for now. 😄

**Comment by Jos512** [comment]
I didn't got a GitHub notification but see that you (steambap) already made a commit. Cool and thanks!

**Comment by Jos512** [comment]
I noticed that with this update the syntax highlighting is a bit 'greedy', highlighting more than needed. 

Being new to Go it took me a while to get a sample application, but this is the code I came up with:

```go
package main

import (
	"bytes"
	"fmt"

	"github.com/alecthomas/chroma/formatters/html"
	"github.com/alecthomas/chroma/lexers"
	"github.com/alecthomas/chroma/styles"
)

func main() {
	input := `
DriveInfo[] drives = DriveInfo.GetDrives();
foreach (DriveInfo drive in drives)
{
	IEnumerable<string> driveFolders =
		Directory.EnumerateDirectories(drive.RootDirectory.ToString());
	
	foreach (string dir in driveFolders)
	{
		Console.WriteLine(dir);
	}	
}`

	lexer := lexers.Get("csharp")

	iterator, _ := lexer.Tokenise(nil, input)

	style := styles.Get("github")

	formatter := html.New(html.WithClasses())

	var buff bytes.Buffer
	formatter.Format(&buff, style, iterator)

	fmt.Printf("[%s]", buff.Bytes())
}
```

The output that this generates is:

```html
<pre class="chroma">
<span class="n">DriveInfo</span><span class="na">[]</span> <span class="n">drives</span> <span class="p">=</span> <span class="n">DriveInfo</span><span class="
p">.</span><span class="n">GetDrives</span><span class="p">(</span><span class="p">)</span><span class="p">;</span>
<span class="k">foreach</span> <span class="p">(</span><span class="n">DriveInfo</span> <span class="n">drive</span> <span class="k">in</span> <span class="n">
drives</span><span class="p">)</span>
<span class="p">{</span>
        <span class="n">IEnumerable</span><span class="p">&lt;</span><span class="kt">string</span><span class="p">&gt;</span> <span class="n">driveFolders</sp
an> <span class="p">=</span>
                <span class="n">Directory</span><span class="p">.</span><span class="n">EnumerateDirectories</span><span class="p">(</span><span class="n">driv
e</span><span class="p">.</span><span class="n">RootDirectory</span><span class="p">.</span><span class="n">ToString</span><span class="p">(</span><span class=
"p">)</span><span class="p">)</span><span class="p">;</span>

        <span class="k">foreach</span> <span class="p">(</span><span class="kt">string</span> <span class="n">dir</span> <span class="k">in</span> <span class=
"n">driveFolders</span><span class="p">)</span>
        <span class="p">{</span>
                <span class="n">Console</span><span class="p">.</span><span class="n">WriteLine</span><span class="p">(</span><span class="n">dir</span><span c
lass="p">)</span><span class="p">;</span>
        <span class="p">}</span>
<span class="p">}</span></pre>
```

The good news is that the following static classes and interface are identified with the `n` HTML class:

```
<span class="n">DriveInfo</span>
<span class="n">IEnumerable</span>
<span class="n">Directory</span>
<span class="n">Console</span>
```

The bad news is that these local variables and methods get the same HTML class as a C# class/interface would get:

```
<span class="n">drives</span>
<span class="n">drive</span> 
<span class="n">driveFolders</span>
<span class="n">EnumerateDirectories</span>
<span class="n">RootDirectory</span>
<span class="n">ToString</span>
<span class="n">dir</span>
<span class="n">driveFolders</span>
<span class="n">WriteLine</span>
```

Can we improve this behaviour?

**Comment by steambap** [comment]
Although I don't have any idea on improve the c# highlight, I think we really need unit test on lexers. This way anyone could contribute to the lexer without break anything.

**Comment by alecthomas** [comment]
I don't disagree, but I don't have time to write unit tests for every language. Contributions welcome.

**Comment by alecthomas** [comment]
I've added a data-driven framework for testing lexers. See the [https://github.com/alecthomas/chroma/tree/master/lexers/testdata](README) for more information.

**Comment by Jos512** [comment]
Thanks for replying Steambap. I also don't know how. I looked at some other libraries to see how/if they highlight those C# code elements, but they don't (see [SyntaxHighlighter](http://alexgorbatchev.com/SyntaxHighlighter/manual/brushes/csharp.html), [highlight.js](https://github.com/isagalaev/highlight.js/blob/master/src/languages/cs.js), [prism.js](https://github.com/PrismJS/prism/blob/gh-pages/components/prism-csharp.js)). Perhaps someone else has an idea. 

And thanks to Alec for making a framework for testing lexers.

**Comment by Jos512** [comment]
I don't think this issue should be closed. Like I [mentioned above](https://github.com/alecthomas/chroma/issues/68#issuecomment-354459563) in December, the pull request #78 from October doesn't work -- it also colours variables and methods as classes/interfaces.

Unless I missed something, there hasn't been another commit that addressed that. The two points I mentioned in the [January comment](https://github.com/alecthomas/chroma/issues/68#issuecomment-354790062) above still need to be implemented as far as I understand.

If the issue has been fixed, then good and I'm looking forward to test it. If not, I ask to re-open this issue so that people can see it and help me with the two points I mentioned above (or help with another way to implement this issue).

**Comment by alecthomas** [comment]
I've reverted #78 for now.

**Comment by alecthomas** [comment]
Without a significantly more intelligent lexer, the highlighting described above can not be realistically achieved. If somebody wants to send a PR to do that, that is great, but the current lexer is the same as Pygments which is fine for now.
