### ISSUE TITLE
LinkableLineNumbers doesn't respect WithClasses configuration

### ISSUE THREAD

**Issue by plumbis** [alecthomas/chroma#683]
**Describe the bug**
When using both `LinkableLineNumbers(true)` and `WithClasses(true)` the html generated by `LinkableLineNumbers` always includes a `style` instead of a `class` for the style of the line number link.

https://github.com/alecthomas/chroma/blob/master/formatters/html/html.go#L353

**To Reproduce**
I _think_ this can be reproduced with any code input:
```shell
wget http://www.google.com
```

But the Chroma CLI doesn't have a build with [Linkable line numbers](https://github.com/alecthomas/chroma/pull/679) yet. 

I think a full command would be:
```shell
chroma --lexer shell --formatter html --style monokai --html-lines --html-only --html-linkable-lines <source>
```

Here is the HTML output generated by Hugo demonstrating the problem
```html
<table class="lntable"><tr><td class="lntd">
  <pre tabindex="0" class="chroma"><code><span class="lnt" id="1">
<a style="outline: none; text-decoration:none; color:inherit" href="#1"> 1</a>
```
Although the `table` and `td` elements have classes the `a` element has an inline style.

I apologize I don't know Golang so I can't test or submit a patch, but it looks like the style needs to be applied similar to highlighted lines here:
https://github.com/alecthomas/chroma/blob/master/formatters/html/html.go#L293

**Comment by alecthomas** [comment]
Thanks for the excellent bug report, this should be fixed in #692.
