### ISSUE TITLE
add the Catppuccin color theme

### ISSUE THREAD

**Issue by walshg3** [alecthomas/chroma#684]
**What problem does this feature solve?**
 making the world a better place one theme at a time

**What feature do you propose?**
please add the Catppuccin color theme it looks like most the work is already done here:
https://github.com/jolheiser/chroma-catppuccin 
Big thank you to jolheiser for his work on it.

**Comment by alecthomas** [comment]
I mean, I'd happily accept a PR from @jolheiser for it.
