### ISSUE TITLE
Other Catppuccin variants

### ISSUE THREAD

**Issue by jolheiser** [alecthomas/chroma#686]
**What problem does this feature solve?**

It spreads the rest of the beauty of catppuccin.

**What feature do you propose?**

Would you be open to a follow-up PR that adds the other three variants? 
#685 is `mocha`, the other three would be `frappe`, `macchiato`, and `latte`.

**Comment by alecthomas** [comment]
> It spreads the rest of the beauty of catppuccin.

😂

> Would you be open to a follow-up PR that adds the other three variants?

Absolutely!

**Comment by walshg3** [comment]
I think this would be a great addition as I use the Frappe theme personally.

I also think once the other variants are made it would be a great opportunity to add chroma to the official catppuccin repo.

**Comment by jolheiser** [comment]
> I also think once the other variants are made it would be a great opportunity to add chroma to the official catppuccin repo.

I'm not sure what this means, but I'll have a PR ready for the other variants tonight or tomorrow most likely. 🙂

**Comment by walshg3** [comment]
> I'm not sure what this means, but I'll have a PR ready for the other variants tonight or tomorrow most likely. 🙂

Sorry I realize how my reply can be confusing haha. I was meaning the  **chroma**  project can submit to be added to [this section](https://github.com/catppuccin/catppuccin#-ports-and-more) of the Catppuccin repo once the variations are completed.

Thank you @jolheiser for your hard work on the themes you made my eyes happy 😆

**Comment by nekowinston** [comment]
Hey there :wave:

Always lovely to see that people are enjoying Catppuccin as much as I do!
Just wanted to chime in here to thank you – @alecthomas for accepting the other flavours and @jolheiser making both PRs.
