### ISSUE TITLE
General improvements for C

### ISSUE THREAD

**Issue by serhack** [alecthomas/chroma#698]
**Description**

This issue wants to report general improvements that can be made on RegEx to highlight more information of C language. In this issue I'd like to add the following features:
* highlight any first string that ends with _t as types. It's [common](https://stackoverflow.com/questions/231760/what-does-a-type-followed-by-t-underscore-t-represent) to use `_t` to mark a type.
* highlight any function `hi()` `wow()` `longstringthatidonotknowof()` (any string that ends with "(...text..)").
* ~~highlight NULL as a parameter inside of any function call.~~ (missing color in the theme I'm using)

It's up to the maintainer adding these features or not. I would be happy to discuss about this.

**To Reproduce**
Text:
```C
time_t begin = time(NULL);
// Call to a function that takes up time
time_t end = time(NULL);
printf("It has been %d seconds from point begin to end", (end-begin));
```

Screenshot:
![image](https://user-images.githubusercontent.com/27734319/200114295-b5f61ddd-d948-44f1-9cc8-3ad5db08e9d9.png)

After:
![image](https://user-images.githubusercontent.com/27734319/200114757-3852a59c-0933-4547-91a0-50495d5a951d.png)

Command:
`chroma -s monokai --html --html-lines --html-lines-table --html-inline-styles <source>`

**Comment by alecthomas** [comment]
The lexers are now defined in XML, so PRs to improve the [C lexer](https://github.com/alecthomas/chroma/blob/master/lexers/embedded/c.xml) are very welcome.

**Comment by serhack** [comment]
I'm not at home, right now. For myself (WIP):

1) for types:

```
(bool|int|long|float|short|double|char((8|16|32)_t)?|unsigned|signed|void|u?int(_fast|_least|)(8|16|32|64)_t)\b|\b[a-z]\w*_t\b
```

2) for functions:

```
((?:[\w*\s])+?(?:\s|[*]))([a-zA-Z_]\w*)(\s*\([^;]*?\))([^;{]*)(\{)|\b[a-z_]\w*(?=\s*\()
```

**Comment by serhack** [comment]
It's clear the second RegEx does not work.

![image](https://user-images.githubusercontent.com/27734319/201047993-6563fe6b-8656-4c50-bc7e-3650f7865bfe.png)

@alecthomas regarding NULL, would you mind if I add some colors to monokai theme? [This file](https://github.com/richleland/pygments-css/blob/master/monokai.css) seems to have all the colors.

**Comment by serhack** [comment]
Win :)

![image](https://user-images.githubusercontent.com/27734319/201171236-0ed34a13-0605-450a-86df-e82e032843c7.png)

**Comment by serhack** [comment]
I think we can close the issue :)
