### ISSUE TITLE
Add some padding or margin to the right of line numbers when styles are inlined

### ISSUE THREAD

**Issue by bep** [alecthomas/chroma#7]
![image](https://user-images.githubusercontent.com/394382/30631156-96f383aa-9de3-11e7-9417-6dc4e5005580.png)

When using CSS classes you can control this, but when the code itself is not indented, the line numbers come a little close when using the inlines styles. Other than that it works great!

**Comment by alecthomas** [comment]
Ah, yeah this is just an omission for inline styles.
