### ISSUE TITLE
lexers.Get is very slow when the lexer is not found

### ISSUE THREAD

**Issue by bep** [alecthomas/chroma#714]
See benchmark in https://github.com/alecthomas/chroma/pull/713

I'm not sure if this is cacheable, but you should at least consider a note in the GoDoc, as this came as a pretty big surprise to me when I found this lighting up like a Christmas tree in a pprof profile.

**Comment by alecthomas** [comment]
I added a note for now, but we could also add another function to not fallback on file matching.
