### ISSUE TITLE
Highlight specific lines

### ISSUE THREAD

**Issue by PaperPrototype** [alecthomas/chroma#715]
**What problem does this feature solve?**

MDX supports highlighting specific lines of code https://nextra.vercel.app/features/mdx

This is very useful for tutorials, where we need to draw the attention of the user to specific lines of code that may have changed.

Please check the Chroma [README](https://github.com/alecthomas/chroma) and command-line tool to ensure this isn't an already solved problem.

**What feature do you propose?**

Based on this syntax

` ` `jsx highlight=4,6-8
import useSWR from 'swr'
function Profile() {
  const { data, error } = useSWR('/api/user', fetcher)
  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>
  return <div>hello {data.name}!</div>
}
` ` `

allow specific lines to be highlighted

**Comment by alecthomas** [comment]
Chroma already supports this... run `chroma --help` and look for "highlight"
