### ISSUE TITLE
`diff` lexer adds new lines

### ISSUE THREAD

**Issue by hloeung** [alecthomas/chroma#716]
**Describe the bug**

I'm currently using chroma and the `quick.Highlight()` option to do per-line syntax highlighting (with plans to switch from per-line). The `diff` lexer seems to add a new line for each line:

![LCtttLb6Ys](https://user-images.githubusercontent.com/95021/204431007-d19af1c3-a0b8-4426-aa61-6607d91f4eca.png)

From the screenshot above, if the lexer is `plaintext` or `go` (or perhaps most of the others though untested) there's no new line added but for `diff` there is.

**To Reproduce**

1. Provide copyable *text* (not an image) that reproduces the issue.

I've uploaded a test script - https://gist.github.com/hloeung/58e46b0a14d89c0e7342956f8b7c10d3

3. Provide a `chroma` command-line invocation to reproduce the issue with the above input text. eg. for Hugo the (rough) equivalent would be `chroma -s monokailight --html --html-lines --html-lines-table --html-inline-styles <source>`

`go run haw-test.go`

**Comment by hloeung** [comment]
Outputting to a file, we can also see new lines after the reset ANSI code:

```
^[[1m^[[34mdiff --git a/go.mod b/go.mod
^[[0m^[[1m^[[34mindex f594e1f..b4e9c07 100644
^[[0m^[[31m--- a/go.mod
^[[0m^[[32m+++ b/go.mod
^[[0m^[[1m^[[35m@@ -1,6 +1,7 @@
...
```

**Comment by alecthomas** [comment]
That's deliberate due to https://github.com/alecthomas/chroma/blob/master/lexers/embedded/diff.xml#L10
Which is inherited from Pygments here: https://pygments.org/docs/lexers/

Chroma is not really intended for highlighting fragments, so it doesn't surprise me too much that some processing is required.

**Comment by hloeung** [comment]
Is it also deliberate to have the reset / normal (0m) after the new line? From the example above, we can also see it when using the "go" lexer with "// indirect".

Thanks for your time.

**Comment by alecthomas** [comment]
Yes, that setting pre-processes the raw text, adding newlines if there aren't any. I believe the intention from Pygments is to support lexer rules that require a newline to work correctly.

**Comment by alecthomas** [comment]
It's a bit of an annoying configuration option if I'm honest.

**Comment by hloeung** [comment]
Ah okay, thanks for explaining it. I'll go ahead and close off this issue.

Again, thanks for your time.
