### ISSUE TITLE
Gallery page is missing the catpuccin styles

### ISSUE THREAD

**Issue by walles** [alecthomas/chroma#719]
**Describe the bug**

The Gallery page linked to from your README.md is missing the catpuccin styles:

https://github.com/alecthomas/chroma/blob/45e3bfb671684372414f2ba3ed45439cc0193664/README.md?plain=1#L252

I would like this page specifically to be up to date:
https://xyproto.github.io/splash/docs/longer/all.html

**To Reproduce**

1. Go to your `README.md`: https://github.com/alecthomas/chroma/blob/master/README.md
2. Click the [Chroma Style Gallery](https://xyproto.github.io/splash/docs/) link
3. Scroll to the bottom
4. Click the [All styles on one page](https://xyproto.github.io/splash/docs/all.html) link
5. Search for `catpuccin`

# Current result

Not found

# Expected result

Catpuccin should be on that page since it's in the source code:
https://github.com/alecthomas/chroma/tree/master/styles

**Comment by alecthomas** [comment]
@xyproto maintains that page

**Comment by xyproto** [comment]
Thanks for reporting! I updated the style gallery to include `catpuccin`. :heavy_check_mark:

**Comment by xyproto** [comment]
However, it's not quite right yet, because the style gallery is unable to use the latest commit from master, or the latest tag. The go module system wants a "v2" directory to exist for version tags with a major number 2.

In the CI system that updates the gallery web page, I get:

```
go get github.com/alecthomas/chroma@$(git ls-remote --refs --heads https://github.com/alecthomas/chroma master | cut -f1)
go: github.com/alecthomas/chroma@45e3bfb671684372414f2ba3ed45439cc0193664: github.com/alecthomas/chroma@v0.10.1-0.20221211204142-45e3bfb67168: invalid version: go.mod has post-v0 module path "github.com/alecthomas/chroma/v2" at revision 45e3bfb67168
Error: Process completed with exit code 1.
```

https://github.com/xyproto/splash/actions/runs/3808417114/jobs/6478977475

**Comment by alecthomas** [comment]
You need to change `go get github.com/alecthomas/chroma@$...` to `go get github.com/alecthomas/chroma/v2@$...`

**Comment by xyproto** [comment]
https://xyproto.github.io/splash/docs/ has been updated.

I also setup a GH action so that it should be updated every 24 hours, if there are changes to the Chroma master branch.

**Comment by alecthomas** [comment]
Great idea, thanks @xyproto !
