### ISSUE TITLE
[raku] Distinguish between builtin types and builtin routines

### ISSUE THREAD

**Issue by habere-et-dispertire** [alecthomas/chroma#720]
When highlighting the following raku:

~~~raku
my Int $foo = 2.sqrt;
~~~

The `Int` and `sqrt` are lumped together as `NameBuiltin` -- which limits the styling options. In a monochome setting, I'd enjoy for example being able to style type as underlined and other builtins as bold.

This would be a lexical enhancement which I can try and contribute but I'd need some direction on the naming for the lexical distinction I am trying to make. I guess maybe a class of `NameType` could work?

Thank you for a wonderful and blindingly fast highlighter!
:-)

**Comment by habere-et-dispertire** [comment]
It looks like this is already handled in raku.go:

~~~
{builtinTypesPattern, NameBuiltin, nil},
{builtinRoutinesPattern, NameBuiltin, nil},
~~~

We just need to preserved the difference rather than amalgamate it.

**Comment by CIAvash** [comment]
There is no token for builtin routines, see [Builtin Tokens](https://pygments.org/docs/tokens/).

But maybe `Keyword.Type` can be used for builtin types.

**Comment by habere-et-dispertire** [comment]
: There is no token for builtin routines, see [Builtin Tokens](https://pygments.org/docs/tokens/).

I don't undertstand. What is being defined in raku.go if not just that?

~~~go
builtinTypes := []string{
    `False`, `True`, `Order`, ...

builtinRoutines := []string{
    `ACCEPTS`, `abs`, `abs2rel`, ...
~~~

**Comment by CIAvash** [comment]
Those are definitions and separations in the code. What is important is the type of the token, such as `NameBuiltin`.

**Comment by habere-et-dispertire** [comment]
Thank you @CIAvash 🌟🤩 !

( I tried it on the [playground](https://swapoff.org/chroma/playground/) but I guess that's not current. What is the release schedule for chroma ? )

**Comment by habere-et-dispertire** [comment]
I've got it working in nix. It seems the `bw` style now has a KeywordType available:

~~~css
/* KeywordType */ .chroma .kt {  }
~~~

I'd like to suggest a typographic change to the `bw` style:

~~~css
/* KeywordType */ .chroma .kt { border-bottom: thin solid }
~~~

Thanks @CIAvash !
