### ISSUE TITLE
I wrapped this lib to be ported to NPM/Node.js

### ISSUE THREAD

**Issue by krymel** [alecthomas/chroma#726]
Hey hey,

I didn't know how to reach out to you best, @alecthomas, so I'm opening a ticket here.
I've built a small wrapper lib for Node.js. The package does automatically download the binary for the target platform and just invokes the executable. Not a big thing... it's stable so far, but I didn't test much on different platforms. 

I'm planning to keep the package maintained/in sync with every new release of this package. 

https://github.com/krymel/chroma-highlight

Please let me know here how you feel about this, if you wish me to change anything for your liking and feel free to just contact me krymel@mailbox.org

Thanks for this amazing library and best!

**Comment by alecthomas** [comment]
Sounds awesome, love it 😍

**Comment by tarasis** [comment]
Just wanted to also say thank you to you both. I'm creating an 11ty plugin that uses both of your projects. WIP atm, works for  Markdown and NJK so far. Just need to do liquid.

Repo https://github.com/tarasis/eleventy-plugin-syntaxhighlighting-chroma
