### ISSUE TITLE
[QUESTION] Why is `<pre tabindex="0"...>` hardcoded?

### ISSUE THREAD

**Issue by itamarhaber** [alecthomas/chroma#731]
Blame: 5ed5054d7369706ea7c48993a254a833e194d289

Motivation: I don't want highlighted (Hugo) code samples tab-bable, and JavaScripting it as a workaround is meh.

**Comment by alecthomas** [comment]
> Motivation: I don't want highlighted (Hugo) code samples tab-bable

Why not?

**Comment by itamarhaber** [comment]
Hi @alecthomas - thanks for replying!

In my project, there's no value in having the chroma-fied content navigatable via the keyboard because there's no way to interact with the content. I believe the same applies in most use cases.

Also, by default/spec, the `<pre>` element doesn't come with the tabindex set (unlike interactive elements, e.g. `<input> and `<a>`), so I expect it to remain that way.

Hence my question: is there a reason for having it hardcoded to zero, rather than using the default?

**Comment by alecthomas** [comment]
I think it would be fine to remove, if you'd like to send a PR.

**Comment by alecthomas** [comment]
Thanks!
