### ISSUE TITLE
Run playground locally

### ISSUE THREAD

**Issue by MarkusAmshove** [alecthomas/chroma#747]
Hi,

I'm currently trying to add a new language to chroma but have some trouble testing.

I've created testdata with actual and expected output and go through it to create a regression test.
However, I'm not exactly sure what I'm syntax wise, so I thought it might be cool to run the playground locally (with the language added) and paste some actual programs in to go through what highlighting I'm missing.

I haven't found a way to do so in the README, is this something that is supported?

**Comment by alecthomas** [comment]
It is yes: `./bin/chromad`

**Comment by MarkusAmshove** [comment]
Awesome, that works, thank you :)
