### ISSUE TITLE
Should I report syntax highlighting issues?

### ISSUE THREAD

**Issue by kevinburke** [alecthomas/chroma#75]
For example, I have a Ruby snippet that I think could be highlighted differently. Is this the right place to report (vs. e.g. Pygments)? What should I include in a bug report, just "it looks bad and could look better"?

**Comment by alecthomas** [comment]
This is the right place, but the report should contain enough information to act on, or better yet, a pull-request. You can also use `chroma -l tokens` to output the raw tokens.
