### ISSUE TITLE
ruby snippet highlighted poorly

### ISSUE THREAD

**Issue by kevinburke** [alecthomas/chroma#76]
I came across this snippet while trying to highlight a Homebrew (brew.sh) formula. This code:

```ruby
bin_path = buildpath/"src/github.com/kevinburke/hostsfile"
```

gets highlighted as

![hostsfile](https://user-images.githubusercontent.com/234019/31869127-c10796b4-b75a-11e7-909a-5c58724da6f4.png)

My Vim ruby syntax highlighter does the right thing; it encompasses the data in the quotes as the correct color.

**Comment by alecthomas** [comment]
That is quite odd isn't it... unfortunately the Pygments Ruby lexer (as you can imagine) had a lot of manual code for handling heredocs and strings. I mostly just removed them and hoped for the best, but I'm guessing this is hitting one of those cases.

**Comment by alecthomas** [comment]
Interestingly, Sublime highlights this identically:
![image](https://user-images.githubusercontent.com/41767/33193039-d5630ebc-d119-11e7-848d-56e14f3454e9.png)

**Comment by ayosec** [comment]
I had a similar issue. When the `/` operator is used in multiple lines, Chroma thinks that it is a regular expression.

Pygments highlights it as expected.

Example:

----

![bad-color](https://user-images.githubusercontent.com/37484/38226786-d45e4176-36ea-11e8-824c-b33cbb9b8f37.png)


----

**Comment by davidfeng88** [comment]
Ah, this looks like https://github.com/alecthomas/chroma/issues/125: it integrates `/` as the beginning of a regex and try to find a second `/` as the regex's end.

**Comment by alecthomas** [comment]
![image](https://user-images.githubusercontent.com/41767/69488967-cda96b80-0ec5-11ea-9d39-8e87e36e0a03.png)

This appears to be fixed.
