### ISSUE TITLE
CFEngine3 and # characters in double and single quoted strings

### ISSUE THREAD

**Issue by miekg** [alecthomas/chroma#763]
**Describe the bug**

Putting a `#` (comment) in a double quoted string leads to different tokens then using it in a single quoted string.
 
Ie take this file:
~~~ cfengine3
bundle agent bla
{
    "installed_canoni#fied"
        slist => "aaa";
}
~~~
Printing the tokens (up to `slist`):
~~~
2023/03/11 23:40:18 chroma.Token {Keyword bundle}
2023/03/11 23:40:18 chroma.Token {Text  }
2023/03/11 23:40:18 chroma.Token {Keyword agent}
2023/03/11 23:40:18 chroma.Token {Text  }
2023/03/11 23:40:18 chroma.Token {NameFunction bla}
2023/03/11 23:40:18 chroma.Token {Text 
}
2023/03/11 23:40:18 chroma.Token {Punctuation {}
2023/03/11 23:40:18 chroma.Token {Text 
    }
2023/03/11 23:40:18 chroma.Token {Punctuation "}
2023/03/11 23:40:18 chroma.Token {NameVariable installed_canoni#fied}
2023/03/11 23:40:18 chroma.Token {Punctuation "}
2023/03/11 23:40:18 chroma.Token {Text 
        }
2023/03/11 23:40:18 chroma.Token {KeywordType slist}
~~~
Now changing the double quotes to single:
~~~ cfengine3
bundle agent bla
{
    'installed_canoni#fied'
        slist => "aaa";
}
~~~
tokens:
~~~ 
2023/03/11 23:41:19 chroma.Token {Keyword bundle}
2023/03/11 23:41:19 chroma.Token {Text  }
2023/03/11 23:41:19 chroma.Token {Keyword agent}
2023/03/11 23:41:19 chroma.Token {Text  }
2023/03/11 23:41:19 chroma.Token {NameFunction bla}
2023/03/11 23:41:19 chroma.Token {Text 
}
2023/03/11 23:41:19 chroma.Token {Punctuation {}
2023/03/11 23:41:19 chroma.Token {Text 
    }
2023/03/11 23:41:19 chroma.Token {Error '}
2023/03/11 23:41:19 chroma.Token {NameFunction installed_canoni}
2023/03/11 23:41:19 chroma.Token {Comment #fied'
}
2023/03/11 23:41:19 chroma.Token {Text         }
2023/03/11 23:41:19 chroma.Token {KeywordReserved slist}
~~~
Note the inserted `Comment` here. I looked a bit at the XML for the CFEngine3 parser, but that's looks OK. So I can't quickly figure out why there should a difference here?

CC @olehermanse (as you seen to be the contributor of this file). Do you have any insights?

Note: I'm using this awesome pkg to do the heavy lifting in: https://github.com/miekg/cf
Thanks for making this!

**Comment by olehermanse** [comment]
I took a look at the XML, and I also don't notice anything obviously wrong. In your output, this seems to indicate the problem:

```
2023/03/11 23:41:19 chroma.Token {Error '}
```

When it gets to the first single quote, it errors instead of going to the `singlequotestring` state. I don't understand why.

**Comment by miekg** [comment]
this is also a fun one
~~~ cfengine3
bundle agent example
{
    files:

    "$(input)"::
      "/tmp/web"        # Directory to monitor for changes.
        classes      => kept_repaired_failed("promise_kept", "promise_repaired", "promise_not_kept)");


}
~~~
the `"$(input)"` is correctly parsed, but the `:`'s show up as 2 `{Error: :}` instead of `{Punctuation: ::}`

**Comment by miekg** [comment]
ok, :facepalm: and sorry for the nice. Using chroma 0.10 instead of v2 - I blame go modules as they make it hard to see if there is an actual v2.

Closing this and see how the _actual_ XML steered parser works

**Comment by miekg** [comment]
meh... it's not better than the older parser :-(
`    "installed_names_canonified" slist => maplist(canonify("$(this)"), @(installed_names));`
`@(installed_names)` is seen as a `CommentPreproc` instead of a nakedvar

**Comment by alecthomas** [comment]
Your best bet for a solution is to send a PR with fixes to the XML file.
