### ISSUE TITLE
html: linkable line numbers cause empty lines when copy paste

### ISSUE THREAD

**Issue by TopiSenpai** [alecthomas/chroma#769]
**Describe the bug**
When using `html.WithLineNumbers` with `html.WithLinkableLineNumbers` copy pasting the generated html on a websites adds and empty line between each line

```go
package main

func main() {
    println("Hello World!")
}
```
copies as

```go

package main


func main() {

    println("Hello World!")

}

```

**To Reproduce**

```go
formatters.Register("html", html.New(
	html.Standalone(true),
	html.WithLineNumbers(true),
	html.WithLinkableLineNumbers(true, "L"),
))
```

- produce some html & open it in the browser
- copy paste the code

**Note**
My guess this issue is already known, but it's rather annoying
I fixed this in a kinda dirty way in my [fork](https://github.com/TopiSenpai/chroma/commit/97b7d41f24da55f5dd27744cdf16cc4a4cebd88c) for me, it would be nice if there was some sort of linkable line numbers mode which does not fuck up copy & paste

You can checkout my modified version for some inspiration here https://xgob.in/yd2og61c#L3

I might be able to make a pr to implement this properly with a bit of help

**Comment by CIAvash** [comment]
It's not about linkable line numbers, what causes the copy issue is `user-select: none;` in line numbers.

**Comment by jmooring** [comment]
@TopiSenpai Do you get the same results with both Firefox and Chrome?

**Comment by TopiSenpai** [comment]
@jmooring this only happens in firefox for me 🥲

**Comment by jmooring** [comment]
@TopiSenpai You are running into [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1273836) that was opened in 2016. Please close this issue.

**Comment by TopiSenpai** [comment]
Alright thanks
How is that still open after 7 years
