### ISSUE TITLE
tracking line and colums position?

### ISSUE THREAD

**Issue by miekg** [alecthomas/chroma#780]
**Describe the bug**

When lexing succeeds, but parsing fails I want to output a line/column number where the parsing stopped. However a chroma.Token doesn't have that info.

Either I'm missing some documentation or is the right way to roll your own? I.e. on every Text token with a newline increment a counter?

I could def. roll my own, but maybe some generic support for this would be nice?

**Comment by alecthomas** [comment]
You'll have to roll your own yep.

**Comment by miekg** [comment]
make sense, thanks.
