### ISSUE TITLE
Suggestion: Move the line range highlighter to the Formatter interface

### ISSUE THREAD

**Issue by bep** [alecthomas/chroma#8]
In my head I would do something like this:

```go
options := []html.Option{
		html.WithLineNumbers(),
		html.TabWidth(4)}

formatters.Register("html", html.New(options...))
```

Then for each highlighting (pseudo code):

```go
s := styles.Get(style)
if range {
  s = s.Clone().AddRange(...)
}
f := formatters.Get("html")
writer, err := f.Format(w, s)
if err != nil {
	return err
}
```

Note that your solution works fine, but the `Style` interface does have a `Clone` method and looks like the object that it meant to change over time, while the `Formatter` is more or less stable. I understand that this could be problematic if only the HTML formatter supports ranges, but then you could consider a ´Clone` method on `Formatter`.

**Comment by alecthomas** [comment]
I think there might be some confusion about the registry. You should generally only use it for very simple defaults. For the level of customisation you need, you're better off constructing a new HTML formatter for each instance:

```go
s := styles.Get(style)
f := html.New(append(options, html.HighlightRanges([][2]int{{1, 4}, {20, 25}}))...)
writer, err := f.Format(w, s)
if err != nil {
	return err
}
```

That said, being able to clone and reconfigure a HTMLFormatter  seems like it would be quite useful...

**Comment by bep** [comment]
>I think there might be some confusion about the registry.

Nah, the confusion is rooted in the role of the Formatter. The "only" thing that changes in my case is, sometimes, people want to highlight a range of lines for a particular code block, and to me that responsibility fits more nicely in your Style. 

But up to you. It works fine both ways.

**Comment by alecthomas** [comment]
Showing/hiding line numbers, and highlighting line ranges are both specific to the HTML formatter, so I'll keep them in there for now. If more than one formatter needs them I'll think about moving them to somewhere more central.

Semi-related, I think I might change the API for the HTML formatter to something like:

```go
formatter := html.New().HighlightRanges(...).WithLineNumbers().TabWidth(4)
```

The functional options are a bit unwieldy.
