### ISSUE TITLE
Feature request - inline PHP

### ISSUE THREAD

**Issue by martinbdz** [alecthomas/chroma#80]
Currently it is not possible to highlight PHP code that does not start with either `<?php` or `<?`. Pygments has the option _startinline_ to indicate this exact case. Would it be possible for chroma to support a similar feature? This is essential for PHP snippet highlighting.

I am happy to provide a PR and already had a quick look at the code. One solution might be to change the starting state in the `TokeniseOptions` for the `Tokenise` function from "root" (the default) to "php" in the client application. This inline starting rule could be a new configuration parameter in the lexer. It would not change the external API much but would still provide a relatively easy and generalized way of dealing with such cases.

**Comment by alecthomas** [comment]
Yes, this is definitely something I'd like to support. I have some code that is _somewhat_ working. Pygments uses a [DelegatingLexer](https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexer.py?at=default&fileviewer=file-view-default#lexer.py-209) to implement this feature. The logic to achieve this is actually quite complex, so my code isn't working correctly yet, and I haven't had the time to debug it.

If you'd like to take a crack at it, I'd be happy to accept it.
