### ISSUE TITLE
Heads up: problems with github.com/dlclark/regexp2 1.5.0 and later

### ISSUE THREAD

**Issue by jmooring** [alecthomas/chroma#805]
Chroma currently uses [github.com/dlclark/regexp2](https://github.com/dlclark/regexp2) 1.4.0, which is fine. At some point in the future, if we bump to 1.5.0 or later, there will be problems.

Highlighting this string with the Go lexer:

```
xəx := 0
```

With dlclark/regexp2 1.4.0 (PASS):

```html
<span class="nx">xəx</span>
```

With dlclark/regexp2 1.5.0 and later (FAIL):

```html
<span class="nx">x</span>
<span class="err">ə</span>
<span class="nx">x</span>
```

**Comment by alecthomas** [comment]
Interesting, have you filed a bug with regexp2?

**Comment by jmooring** [comment]
No.

**Comment by alecthomas** [comment]
This appears to be because dclark made RE2 compatibility mode (which Chroma uses) stricter. In particular, `\w` now only matches ASCII words.
