### ISSUE TITLE
Would you accept new lexers?

### ISSUE THREAD

**Issue by gandarez** [alecthomas/chroma#819]
**What problem does this feature solve?**

I have an standalone client written in Go that relies directly to the legacy version `v0.10.0` with some changes we've done in the couple years ago to support guessing the language by its file extension.  As it becomes so far from the current version we decided to start migrating to `v2.8.0` but many languages aren't already implemented in this version.

Here you can see the [retrofrit tests](https://github.com/wakatime/wakatime-cli/blob/develop/pkg/language/language_test.go#L258) we've done.

And also here, you can ssee the bunch of commits we pushed to master branch [here](https://github.com/wakatime/chroma/commits/master).

**What feature do you propose?**

Would you accept PRs where we add a new lexer without any rules only to get the advantage of file extensions? For example, `crontab`:

```
// Crontab lexer.
var Crontab = internal.Register(MustNewLexer(
	&Config{
		Name:      "Crontab",
		Aliases:   []string{"crontab"},
		Filenames: []string{"crontab"},
	},
	Rules{
		"root": {},
	},
))
```

That's the way I see to keep it compatible with the legacy version and don't break our usage.

As per reference we created a [TODO](https://github.com/wakatime/chroma/blob/master/lexers/TODO.md) list to control the implementations

**Comment by alecthomas** [comment]
No, I wouldn't accept empty lexers.

You shouldn't need to fork Chroma in order to add these for your own purposes though, you can  just register them with the Chroma lexer registry.
