### ISSUE TITLE
Sass issues

### ISSUE THREAD

**Issue by XhmikosR** [alecthomas/chroma#82]
Hi @alecthomas.

I'm in the process of switching Bootstrap docs to Hugo with chroma as the highlighter.

It works well generally except for these 2 issues:

1. the HTML `<` and `>` aren't the same color as the keyword. Compared to what we have now with Rouge, not sure which is right, or if this is a bug. Maybe I just need to update our highlighting script to include the `p` class. So that `.nt, .p` use the same style; please confirm if this affects more styles
2. When highlighting scss sometimes I get no highlighting. Example:
  ```markdown
  \```scss
  .selector-for-some-widget {
    box-sizing: content-box;
  }
  \```
  ```
  results in:

  ```html
  <div class="highlight"><pre class="chroma"><code class="language-scss" data-lang="scss">.selector-for-some-widget {
    box-sizing: content-box;
  }</code></pre></div>
  ```
Now this example is pure CSS but it's also valid scss syntax so it should be highlighted.

Another example is this:

```markdown
\```scss
$font-family-sans-serif:
  // Safari for OS X and iOS (San Francisco)
  -apple-system,
  // Chrome < 56 for OS X (San Francisco)
  BlinkMacSystemFont,
  // Windows
  "Segoe UI",
  // Android
  "Roboto",
  // Basic web fallback
  "Helvetica Neue", Arial, sans-serif,
  // Emoji fonts
  "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !default;
\```
```

I'm not sure if I'm missing something since this is still a work in progress, but I'd expect these to work.

Let me know if you need more info.

Thanks!

PS. I added the backslashes so that GitHub markdown doesn't break; they are not present in my markdown.

**Comment by danielpost** [comment]
I’m having the same issue. `\`\`\`css` works fine but `\`\`\`sass` or `\`\`\`scss` don’t. Any ideas?

**Comment by alecthomas** [comment]
`scss` is not supported. The lexer will need to be imported from Pygments. `sass` should be, to some degree, though I'm not sure how robust it is.

**Comment by alecthomas** [comment]
I imported the scss lexer from Pygments. Give it a shot.

**Comment by danielpost** [comment]
Thanks @alecthomas! I'm using Chroma through Hugo (static site generator) so I think I need to wait until the update gets implemented there? cc @bep @spf13

**Comment by alecthomas** [comment]
Ah yes. You can probably update the vendored version to test it if you're keen.

**Comment by danielpost** [comment]
I'll give it a shot. Thanks for the quick response and update!
