### ISSUE TITLE
Support EDN syntax highlighting

### ISSUE THREAD

**Issue by rome-user** [alecthomas/chroma#824]
**What problem does this feature solve?**

Clojure syntax highlighting is already done by Chroma. EDN is a subset of Clojure syntax that is commonly used in clojure projects. It is sufficient to treat `.edn` files as `.clj` files for the purposes of syntax highlighting. This will allow consumers of this library (such as Forgejo) to support syntax highlighting of EDN files.

**What feature do you propose?**
N/A

**Comment by alecthomas** [comment]
Your best bet is to find the xml file under lexers/embedded and add the extension yourself in a PR.
