### ISSUE TITLE
 Line feed following printable character is detected as an error for VimL

### ISSUE THREAD

**Issue by mmrwoods** [alecthomas/chroma#827]
I'm using [glow](https://github.com/charmbracelet/glow) to preview markdown within Vim and have noticed that for code blocks with the language set to vim, a line feed following a printable character is always shown as an error, e.g.

![Screenshot 2023-08-21 at 12 31 49](https://github.com/alecthomas/chroma/assets/138597/8e8ca8d4-13e0-45db-bd16-76269df2822a)

The first code block here has the language set to `vim`, the other set to `ruby`, line feed following a printable character is always shown as an error for `vim` code blocks.

Glow depends on [glamour](https://github.com/charmbracelet/glamour) to render markdown, and Glamour depends on Chroma to add syntax highlighting to code blocks.

It looks like the root cause of this issue is that Chroma is detecting a line feed following a printable character as an error, e.g.

```
$ echo "set foo" > foo.vim
$ chroma -f json foo.vim
[
  {"type":"NameOther","value":"set"},
  {"type":"Text","value":" "},
  {"type":"NameOther","value":"foo"},
  {"type":"Error","value":"\n"}
]
```

Glamour then highlights this as an error with a red background when rendering the code block, and that's what I end up seeing in the output from Glow. I can work around this telling glow to use custom styles and just override the rendering of errors in code blocks, but that's quite a nasty hack, so it would be really nice to see this fixed in Chroma (assuming Chroma is really the root cause here, and I may well have assumed incorrectly that Chroma is at fault).

I will try to find some time to fix this myself and open a PR, but I'm not familiar with this code at all, so It thought I'd open an issue first as this might be a simple fix for someone who knows the code.

**Comment by mmrwoods** [comment]
You can re-produce it in the playground, you will see the error span in the html output.

**Comment by alecthomas** [comment]
Ah sorry, I somehow missed your invocation from the command line 🤦

**Comment by mmrwoods** [comment]
Fantastic, thank you very much 👍
