### ISSUE TITLE
Duplicate lexer entry

### ISSUE THREAD

**Issue by jmooring** [alecthomas/chroma#843]
Running `chroma --list` shows a duplicate entry in the registry. Go HTML Template is listed twice.

![image](https://github.com/alecthomas/chroma/assets/335669/c5cb15fe-a954-4c11-9c7f-f623b5fb3f15)

**Comment by alecthomas** [comment]
I can't replicate this on master:

```
  Go
    aliases: go golang
    filenames: *.go
    mimetypes: text/x-gosrc
  Go HTML Template
    aliases: go-html-template
  Go Text Template
    aliases: go-text-template
```

**Comment by jmooring** [comment]
> I can't replicate this on master:

Neither can I. Please roll a release when you have some time. Thanks.

**Comment by jmooring** [comment]
This was resolved with https://github.com/alecthomas/chroma/pull/834.
