### ISSUE TITLE
Support WithLinkableLineNumberRanges()

### ISSUE THREAD

**Issue by Smithx10** [alecthomas/chroma#846]
Currently we can only Link to 1 Line.  I'd like to be able to provide a highlighted range, for example L4-L8.  

This is achieved by holding shift and clicking L4 and then L8 in github gists.

For example in a github gist:
https://gist.github.com/Smithx10/c5a6b0b30d59b51000868db74b9e7b73#file-gistfile1-txt-L4-L8

**Comment by alecthomas** [comment]
I don't think that's possible without JS, and that's out of scope for Chroma.
