### ISSUE TITLE
Support Justfile

### ISSUE THREAD

**Issue by SteveLauC** [alecthomas/chroma#847]
**What problem does this feature solve?**

Gitea uses `chroma` for syntax highlight, It would be great if `chroma` would support [justfile](https://github.com/casey/just) so that [Gitea could benefit from this](https://github.com/go-gitea/gitea/issues/27086)

**What feature do you propose?**

Support syntax highlight for justfile

**Comment by silverwind** [comment]
If it looks somewhat okay while highlighted as `Makefile`, it could be added as an alias to is as a temporary solution until full support is added.

**Comment by silverwind** [comment]
<img width="716" alt="image" src="https://github.com/alecthomas/chroma/assets/115237/7762f97a-fecb-44eb-95df-0fecb33b01e0">

Looks okay imho.

**Comment by SteveLauC** [comment]
Thanks for doing this!
