### ISSUE TITLE
Running tests with RECORD=true leaves a non-clean working tree

### ISSUE THREAD

**Issue by myitcv** [alecthomas/chroma#855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Running the lexer tests against https://github.com/alecthomas/chroma/commit/def00e9c22f4a5f971981fde65580a8d36843028 with `RECORD=true` leaves the git working tree in an non-clean state.

### To Reproduce

Against commit https://github.com/alecthomas/chroma/commit/def00e9c22f4a5f971981fde65580a8d36843028:

```
$ RECORD=true go test ./lexers
ok      github.com/alecthomas/chroma/v2/lexers  1.448s
$ go test ./lexers
ok      github.com/alecthomas/chroma/v2/lexers  1.581s
$ git status
HEAD detached at origin/master
Changes not staged for commit:
        modified:   lexers/testdata/analysis/bash.expected
        modified:   lexers/testdata/analysis/c.ifdef.expected
        modified:   lexers/testdata/analysis/c.ifndef.expected
        modified:   lexers/testdata/analysis/c.include.expected
        modified:   lexers/testdata/analysis/cpp.include.expected
        modified:   lexers/testdata/analysis/cpp.namespace.expected

no changes added to commit
```

So whilst the lexer tests pass, updating the expectations files results in changes.

This seems less than ideal for people making contributions to the repo, especially if they are updating expectations in specific files because they could easily include unrelated changes in others, without a clear understanding of why there are differences. 

According to my analysis there are two reasons behind this:

* Newlines are not consistently being written to expectation files.
* The comparison of expected vs actual happens after trimming of space and parsing of values, meaning different byte sequences can be considered equal.

I have a PR that includes a number of commits that propose a solution to this, which I will push up for discussion to complement this issue.

**Comment by alecthomas** [comment]
I don't think your analysis is correct. As far as I can tell `RECORD=true` isn't inconsistent with how it adds newlines. My guess is that someone manually updated the files before committing them (or rather their editor probably did it fort them), which added newlines.

Your PR would not fix that, but running `RECORD=true` in CI and checking for a dirty tree would. I think that is probably the correct solution to this issue.
