### ISSUE TITLE
Helping review change to the CUE lexer

### ISSUE THREAD

**Issue by myitcv** [alecthomas/chroma#859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What problem does this feature solve?

@alecthomas - thanks very much for helping to review and merge #858. 

I would like to explore how maintainers on the CUE project can help with changes to chroma's CUE lexer with a view to:

* Reducing the burden on you
* Helping to increase the confidence in changes made to the CUE lexer

### What feature do you propose?

One way that could be achieved is by adding `CODEOWNERS`:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

(you as the repo owner are implicitly one such `CODEOWNER` owner I believe).

A single file `CODEOWNERS` would be added to the root of the repo, with the following contents for CUE:

```CODEOWNERS
# Order is important in this file: the **last** matching line wins.

# CUE project: https://cuelang.org
/lexers/embedded/cue.xml              @myitcv @mvdan
/lexers/testdata/cue.*                @myitcv @mvdan
```

Would this be of help? As I mentioned above, the main goal here being to reduce the burden on you, but also increase the confidence in changes made to the lexer.

cc @mvdan who works with me on the CUE project and is referenced above.

**Comment by alecthomas** [comment]
I don't foresee significant burden, let's just see how it pans out for now.

PS. Hey @mvdan

**Comment by myitcv** [comment]
Ok thanks!

Please feel free to cc either me or @mvdan on any CUE change to help validate the correctness, completeness etc.

**Comment by mvdan** [comment]
Hey @alecthomas, small world :)
