### ISSUE TITLE
Language parameter to the playground

### ISSUE THREAD

**Issue by vanillajonathan** [alecthomas/chroma#865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What problem does this feature solve?

When linking to the Playground the user has to change the language.

### What feature do you propose?

Add a language parameter to the URL for the playground.

Example:
https://swapoff.org/chroma/playground/#lang=python

**Comment by alecthomas** [comment]
If you click the copy/paste button you'll get a link like [this](https://swapoff.org/chroma/playground/#eyJsYW5ndWFnZSI6IlB5dGhvbiIsInN0eWxlIjoibW9ub2thaWxpZ2h0IiwidGV4dCI6IiIsImNsYXNzZXMiOmZhbHNlfQ) that includes all of the state in the page.

**Comment by vanillajonathan** [comment]
It results in a bit long and ugly URL. Having just a `lang=python` parameter would be nice. If `lang` isn't found, it could fallback to base64 one.
