### ISSUE TITLE
Add lexer for Typst

### ISSUE THREAD

**Issue by miliog** [alecthomas/chroma#877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the missing lexer?

[Typst](https://github.com/typst/typst) is a new markup language and I've noticed that `chroma` doesn't support it.

The syntax documentation can be found here:
https://typst.app/docs/reference/syntax/

### Links to existing syntax definitions

Github Linguist uses the following:
https://github.com/michidk/typst-grammar/blob/master/grammars/tmlanguage.json

**Comment by jonaspleyer** [comment]
FYI I have looked at this problem and put some incremental work into the typst lexer at https://github.com/pygments/pygments It will probably be the easiest if we first develop there and then simply copy the lexer over just as you did before. Happy for feedback on my recent PR over there:
https://github.com/pygments/pygments/pull/2656

**Comment by oliverpool** [comment]
Pygment's MR just got merged, I just opened a PR here, feel free to test it locally: #1007
