### ISSUE TITLE
DNS / BIND9 Zone files are wrongly highlighted (`err` class)

### ISSUE THREAD

**Issue by tarneaux** [alecthomas/chroma#885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Steps to reproduce

[Playground link](https://swapoff.org/chroma/playground/#eyJsYW5ndWFnZSI6ImRucyIsInN0eWxlIjoibW9ub2thaWxpZ2h0IiwidGV4dCI6ImNoYXJlbm5lcy5vcmcgICAzNjAwICAgIElOICAgICAgU09BICAgICBucy5jaGFyZW5uZXMub3JnIGFkbWluLmNoYXJlbm5lcy5vcmcgMCAxMDgwMCAzNjAwIDYwNDgwMCAzNjAwIiwiY2xhc3NlcyI6ZmFsc2V9)

In the following perfectly valid zone file, the `err` class is applied to the `.org` in `charennes.org` and the `ns.charennes.org admin.charennes.org`.
```
charennes.org   3600    IN      SOA     ns.charennes.org admin.charennes.org 0 10800 3600 604800 3600
```

#### Expected behavior

The `err` class should not be applied to said parts of the text. The proper class is apparently `nc` for NameClass.

**Comment by tarneaux** [comment]
After a bit of trial and error, it seems like the following regex has just the right scope to detect only domain names:
```regex
([\w\d\.-]+\.[a-z-]{2,24}\.?|^(@|[\w\d-]+))
```

I have only tested it on a regex playground though, and this is why I am not submitting a PR yet (setting up the working environment is a bit of a hassle with go for me).

<details>
<summary>Git diff:</summary>

```diff
$ git diff origin/master
diff --git a/lexers/embedded/dns.xml b/lexers/embedded/dns.xml
index 5ac3c25..ef8f663 100644
--- a/lexers/embedded/dns.xml
+++ b/lexers/embedded/dns.xml
@@ -27,7 +27,7 @@
       <rule pattern="\b([\w\d.-])+\.($|\s)">
         <token type="NameProperty"/>
       </rule>
-      <rule pattern="^(@|[\w\d-]+)">
+      <rule pattern="([\w\d\.-]+\.[a-z-]{2,24}\.?|^(@|[\w\d-]+))">
         <token type="NameClass"/>
       </rule>
       <rule pattern="^\$(TTL|GENERATE|INCLUDE|ORIGIN)">
```

</details>

**Comment by alecthomas** [comment]
FYI you can test without the Go toolchain by downloading one of the release binaries and running it with:

```
chroma -l ./dns.xml <input>
```
