### ISSUE TITLE
`lexer.Match` does not work as intended

### ISSUE THREAD

**Issue by frapa** [alecthomas/chroma#909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A Lexer can define multiple glob pattern that it matches using the `<filename>` tag in the lexer XML config. However, this does not work as intended, it seems to be matching only the first defined glob pattern.

For instance I passed `"Dockerfile"` and it returned the correct lexer, however passing `"dev.Dockerfile"` did not.

Note that the lexer correctly defined the glob pattern [here](https://github.com/alecthomas/chroma/blob/master/lexers/embedded/docker.xml#L8C2-L8C2).

I could have a look if I manage to fix this myself, if you accept contributions.

### To Reproduce

`lexer.Match("dev.Dockerfile")` does not return the correct lexer.

**Comment by alecthomas** [comment]
I can't replicate this:

```go
func TestMatch(t *testing.T) {
	assert.NotZero(t, lexers.Match("foo.Dockerfile"))
}
```

Passes fine. Reopen if you can provide a test case that fails.

**Comment by frapa** [comment]
Hi @alecthomas,

Thanks for having a look! For me that test fails. Proof:

![image](https://github.com/alecthomas/chroma/assets/1306195/f5d097f1-d131-43ee-a6eb-299fe34f8094)

As text

```go
package main

import (
	"testing"

	"github.com/alecthomas/chroma/lexers"
	"github.com/stretchr/testify/assert"
)

func TestMatch(t *testing.T) {
        // First returns lexer (PASS)
	assert.NotEqual(t, nil, lexers.Match("Dockerfile"))
        // First SHOULD return lexer, but returns nil lexer (PASS)
	assert.Equal(t, nil, lexers.Match("foo.Dockerfile"))
        // Code from issue (FAILS)
	assert.NotZero(t, lexers.Match("foo.Dockerfile"))
}
```

I am currently on `go 1.21.6`.

**Comment by alecthomas** [comment]
You are using the old version of Chroma. The correct import is v2:

```
github.com/alecthomas/chroma/v2/lexers
```

**Comment by alecthomas** [comment]
I realised the README doesn't explicitly state this so I've [updated it](https://github.com/alecthomas/chroma/commit/f4788c0e9e139b7ac22e78fda970b5a11a85cb4e).

**Comment by frapa** [comment]
Oh, I did not know that! Thanks a lot and thanks for updating the Readme!
