### ISSUE TITLE
LineHighlight style is incorrect

### ISSUE THREAD

**Issue by jmooring** [alecthomas/chroma#910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There are currently 5 styles that specify `LineHighlight`:

- [styles/catppuccin-frappe.xml](https://github.com/alecthomas/chroma/blob/a8704a8f0b2c94b2396c93760a52bf494c56364c/styles/catppuccin-frappe.xml#L8)
- [styles/catppuccin-latte.xml](https://github.com/alecthomas/chroma/blob/a8704a8f0b2c94b2396c93760a52bf494c56364c/styles/catppuccin-latte.xml#L8)
- [styles/catppuccin-macchiato.xml](https://github.com/alecthomas/chroma/blob/a8704a8f0b2c94b2396c93760a52bf494c56364c/styles/catppuccin-macchiato.xml#L8)
- [styles/catppuccin-mocha.xml](https://github.com/alecthomas/chroma/blob/a8704a8f0b2c94b2396c93760a52bf494c56364c/styles/catppuccin-mocha.xml#L8)
- [styles/github-dark.xml](https://github.com/alecthomas/chroma/blob/a8704a8f0b2c94b2396c93760a52bf494c56364c/styles/github-dark.xml#L3)

In each case, the resulting style is `#HEXCODE` instead of `bg: #HEXCODE`.

cc: @icy-comet 

### To Reproduce

Not applicable because the playground does not allow you to specify which lines to highlight.

**Comment by alecthomas** [comment]
Contributions are welcome.

**Comment by jmooring** [comment]
@alecthomas Understood. My understanding is that these styles are generated, not hand coded. I don't spend enough time in the codebase to know where to start. I cc'd icy-comet because it looks like they were the last one to touch all five styles.

**Comment by alecthomas** [comment]
They're not generated, they're XML files in this directory: https://github.com/alecthomas/chroma/tree/master/styles

**Comment by jmooring** [comment]
<https://github.com/alecthomas/chroma/pull/797#issue-1789962165>

> These definitions have been dynamically created using a script to keep up with changes in the color pallete.

I'd hate to make changes just to have them overwritten the next time someone uses the script referenced above.

**Comment by icy-comet** [comment]
> the script referenced above

It's an external script I use to keep the styles up-to-date with the upstream color definitions and is entirely independent of `chroma`.

Anyways, I have updated the template in my repo and also opened a PR here.
