### ISSUE TITLE
Kotlin multi-line strings are not rendered correctly

### ISSUE THREAD

**Issue by helmbold** [alecthomas/chroma#92]
This code 

```Kotlin
val multiLine = """
    Es war einmal eine kleine süße Dirne, die hatte jedermann lieb,
    der sie nur ansah, am allerliebsten aber ihre Großmutter, die
    wußte gar nicht, was sie alles dem Kinde geben sollte. Einmal
    schenkte sie ihm ein Käppchen von rotem Sammet ...
    """
```
gets rendered like this:

![chroma4](https://user-images.githubusercontent.com/5079980/32702992-ae7404b0-c7ef-11e7-9f0e-2c8be64df9b9.PNG)

The string is not rendered like a string and the last double quotes are not rendered correctly.

**Comment by alecthomas** [comment]
Can you please consolidate these into one issue?

**Comment by helmbold** [comment]
I wonder why you prefer a single ticket for different bugs, but here is the consolidated [ticket](https://github.com/alecthomas/chroma/issues/93).
