### ISSUE TITLE
Several renderings bugs in Kotlin lexer

### ISSUE THREAD

**Issue by helmbold** [alecthomas/chroma#93]
## Kotlin multi-line strings are not rendered correctly

This code 

```Kotlin
val multiLine = """
    Es war einmal eine kleine süße Dirne, die hatte jedermann lieb,
    der sie nur ansah, am allerliebsten aber ihre Großmutter, die
    wußte gar nicht, was sie alles dem Kinde geben sollte. Einmal
    schenkte sie ihm ein Käppchen von rotem Sammet ...
    """
```
gets rendered like this:

![chroma4](https://user-images.githubusercontent.com/5079980/32702992-ae7404b0-c7ef-11e7-9f0e-2c8be64df9b9.PNG)

The string is not rendered like a string and the last double quotes are not rendered correctly.

## Angle bracket of Kotlin type parameter list is detected as ".err"

The following example shows the rendering of this method with type parameters:

```Kotlin
fun <A: AutoCloseable, B> doWithResource(resource: A, action: (resource: A) -> B): B {
    try {
        return action(resource)
    } finally {
        resource.close()
    }
}
```

![chroma3](https://user-images.githubusercontent.com/5079980/32702959-1ccdea26-c7ef-11e7-8896-b8ccdd6cea9e.PNG)

As you can see the first angle bracket is not rendered correctly. The css class is `.chroma .err`.

## curly braces detected as ".err"

In the following Kotlin example is the curly brace behind `companion object` detected as ".chroma .err":

![chroma2](https://user-images.githubusercontent.com/5079980/32702930-7bf62686-c7ee-11e7-8b7b-e81fce883d1f.PNG)

## comments not detected at the end of code snippet 

The following markdown source code is not rendered correctly with chroma (as included in [Hugo v0.30.2](https://github.com/gohugoio/hugo/releases/tag/v0.30.2)):

```kotlin
class A
class B : A() // Compiler-Fehler!

open class C
class D : C() // ok
```

The result looks like this:

![chroma1](https://user-images.githubusercontent.com/5079980/32699697-203b6524-c7ba-11e7-94eb-774ee476a2c0.PNG)

As you can see, the second comment is not detected. If I add another line with some code, the second comment is rendered correctly.

## Curly braces and brackets in Scala are recognized as operators

![chroma5](https://user-images.githubusercontent.com/5079980/32743666-5a33af5e-c8ad-11e7-9bba-cf253d5a4b65.PNG)

CSS class: `.chroma .o`

## PHP syntax not highlighted

This snippet 

    ```php
    if ( mysqli_stmt_fetch($stmt) ) {
      // wenn TRUE ...
    } else {
      // wenn FALSE ...
    }
    ```

leads to the following result where only the css class `.chroma .x` is used:

![chroma6](https://user-images.githubusercontent.com/5079980/32743880-0b83b0ba-c8ae-11e7-9bfc-7104d60bc538.PNG)

**Comment by alecthomas** [comment]
Thanks!

**Comment by helmbold** [comment]
I've added two more bugs, one with Scala and one with PHP.

**Comment by kropp** [comment]
@helmbold Please move Scala and PHP bugs to separate issues

**Comment by helmbold** [comment]
@kropp I created this issue from several separate issues as requested by @alecthomas . I would generally prefer to keep issues small and focused. Now this issue is closed although neither the Scala nor the PHP bugs are fixed. That wouldn't be the case with separate issues.
