### ISSUE TITLE
Aliases vs Filenames mismatch

### ISSUE THREAD

**Issue by bep** [alecthomas/chroma#94]
I saw the commit title in 9c81d25368bedda10b71f4cde071d6bae7312008 and pulled it into Hugo without thinking too hard, expecting it to just work.

I have not before looked at your lexer config and the apparent difference between `Aliases` and `Filenames`.

So, when Hugo asks Chroma for a lexer by the names `svg`, `wsdl` etc., it will not get one. 

It would be good if the extensions in `Filenames` could be somehow merged into the `Aliases` -- or maybe there is another way to get this to work as (I) expected?

https://github.com/gohugoio/hugo/issues/4087

**Comment by alecthomas** [comment]
Hmm, yeah that is odd. I attempted to base it off Pygments, do you know how it handles this situation?

**Comment by bep** [comment]
>do you know how it handles this situation?

No, I have no experience with filenames vs Pygments.

**Comment by bep** [comment]
I can do a quick check with Pygments and get back to you.

**Comment by bep** [comment]
OK, checked. Looks like Pygments behaves the same. But it would make a lot of sense to adjust this logic.

**Comment by alecthomas** [comment]
> OK, checked. Looks like Pygments behaves the same. But it would make a lot of sense to adjust this logic.

Agreed. I've changed `lexers.Get()` to also check filenames and file aliases.
