### ISSUE TITLE
Rendering of .diff code is incorrect when the last newline is missing

### ISSUE THREAD

**Issue by dmerejkowsky** [alecthomas/chroma#96]
# Steps to reproduce

* Create a `foo.diff` file looking like:

```diff
- foo
+ bar
```

*without* the trailing new line

* run `chroma` on it:

```console
$ go run cmd/chroma/main.go toto.diff --html > out.html
```

# Expected

`out.html` contains no errors

# Actual

`out.html` contains an error:

```html
<span class="gd"></span><span class="err">+ bar</span>
```

**Comment by dmerejkowsky** [comment]
Note: Cannot reproduce the bug with `pygmentize`

**Comment by kaushalmodi** [comment]
Related: https://github.com/alecthomas/chroma/issues/55
