### ISSUE TITLE
`lexers.DelegatingLexer` always does not highlight tokens correctly

### ISSUE THREAD

**Issue by Delta456** [alecthomas/chroma#960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am currently working on a feature for [`charmbracelet/freeze`](https://github.com/charmbracelet) which makes use of the `chroma` library and I am using the `DelegatingLexer` where I am passing two languages `py` and `go` as the `language` and `root` respectively. My PR implementation can be seen here: https://github.com/charmbracelet/freeze/pull/79

Using

- `./freeze --language py,go file.py` gives
![image](https://github.com/alecthomas/chroma/assets/28479139/2cc2c045-4363-41e3-8b02-e2683ea8e5a3)

- `./freeze --language go,py file.py` gives
![image](https://github.com/alecthomas/chroma/assets/28479139/0f5ee423-1343-4519-bbfb-81b77b8665b3)

As it can be seen `chroma` doesn't highlight the `root` of the `lexers.DelegatingLexer`. Only the `language` part is highlighted. However, this is not always the case.

- ` ./freeze --language jinja,html file.jinja` gives

![image](https://github.com/alecthomas/chroma/assets/28479139/b48d58e1-f61b-454c-aea4-0d5a1566cdf4)

- `./freeze --language jinja file.jinja` gives

![image](https://github.com/alecthomas/chroma/assets/28479139/1681ec74-8fcf-4d08-807d-35263222a5a3)

In this case, `jinja,html` languages correctly highlight the code snippet.

### To Reproduce

Chroma Playground doesn't support syntax highlighting of two languages at one time. 

To locally reproduce this:

- Clone https://github.com/Delta456/freeze/tree/multi_lang
- Run `go build .`
- Run `./freeze --language py,go file.py`

Contents of `file.py`:

```
def hello():
    print('hello world')

func Hello() {
    fmt.Println("Hello world")
} 
```

**Comment by isabelroses** [comment]
Also noticing the issue, particularly with PHP and html, with any any combination of PHP or html being the root.

**Comment by alecthomas** [comment]
@Delta456 the delegating lexer is working as intended. If you [read the documentation](https://github.com/alecthomas/chroma/blob/9347b550abb84248f8421e842ec50fb488cdbb57/delegate.go#L12-L19) it describes how it works, in that the root lexer must return a token type of `Other`. Neither Go or Python are designed for this, and I'm not sure how that would even work.

**Comment by alecthomas** [comment]
@isabelroses if you find a bug please file an issue. There are tests for the delegating lexer, and the "phtml" lexer uses it directly and nobody has filed any bugs for a few years, but anything's possible.

**Comment by Delta456** [comment]
> @Delta456 the delegating lexer is working as intended. If you [read the documentation](https://github.com/alecthomas/chroma/blob/9347b550abb84248f8421e842ec50fb488cdbb57/delegate.go#L12-L19) it describes how it works, in that the root lexer must return a token type of `Other`. Neither Go or Python are designed for this, and I'm not sure how that would even work.

That's true indeed. Can you add an explicit list of supported explicit languages for `DelegatingLexer`?

**Comment by alecthomas** [comment]
No, but if you wish to send a PR with an update to the README I'd consider it.
