### ISSUE TITLE
Chroma Playground v2.9.1 is outdated compared to the latest release

### ISSUE THREAD

**Issue by juanbomfim22** [alecthomas/chroma#967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The page header shows that the Chroma Playground has an outdated version, nominally 2.9.1, released in September 2023, almost a year ago.  

As a consequence, the Playground may behave differently from the latest version. For instance, some **tokyonight** themes from #957 have not been loaded into the page, as shown in the image below.

<img width="832" alt="image" src="https://github.com/alecthomas/chroma/assets/55420785/5b1c493b-2e4d-4ce3-8503-1431b21683e8">

### To Reproduce

Access https://swapoff.org/chroma/playground/.

**Comment by alecthomas** [comment]
Fixed
